/* MainWindow.c generated by valac 0.34.7, the Vala compiler
 * generated from MainWindow.vala, do not modify */

/* Copyright 2015 LuizAugustoMorais
*
* This file is part of Tomato.
*
* Tomato is free software: you can redistribute it
* and/or modify it under the terms of the GNU General Public License as
* published by the Free Software Foundation, either version 3 of the
* License, or (at your option) any later version.
*
* Tomato is distributed in the hope that it will be
* useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
* Public License for more details.
*
* You should have received a copy of the GNU General Public License along
* with Tomato. If not, see http://www.gnu.org/licenses/.
*/

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <granite.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gi18n-lib.h>
#include <gdk/gdk.h>
#include <stdio.h>


#define TOMATO_WINDOW_TYPE_MAIN_WINDOW (tomato_window_main_window_get_type ())
#define TOMATO_WINDOW_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TOMATO_WINDOW_TYPE_MAIN_WINDOW, TomatoWindowMainWindow))
#define TOMATO_WINDOW_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TOMATO_WINDOW_TYPE_MAIN_WINDOW, TomatoWindowMainWindowClass))
#define TOMATO_WINDOW_IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TOMATO_WINDOW_TYPE_MAIN_WINDOW))
#define TOMATO_WINDOW_IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TOMATO_WINDOW_TYPE_MAIN_WINDOW))
#define TOMATO_WINDOW_MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TOMATO_WINDOW_TYPE_MAIN_WINDOW, TomatoWindowMainWindowClass))

typedef struct _TomatoWindowMainWindow TomatoWindowMainWindow;
typedef struct _TomatoWindowMainWindowClass TomatoWindowMainWindowClass;
typedef struct _TomatoWindowMainWindowPrivate TomatoWindowMainWindowPrivate;

#define TOMATO_TYPE_TOMATO_APP (tomato_tomato_app_get_type ())
#define TOMATO_TOMATO_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TOMATO_TYPE_TOMATO_APP, TomatoTomatoApp))
#define TOMATO_TOMATO_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TOMATO_TYPE_TOMATO_APP, TomatoTomatoAppClass))
#define TOMATO_IS_TOMATO_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TOMATO_TYPE_TOMATO_APP))
#define TOMATO_IS_TOMATO_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TOMATO_TYPE_TOMATO_APP))
#define TOMATO_TOMATO_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TOMATO_TYPE_TOMATO_APP, TomatoTomatoAppClass))

typedef struct _TomatoTomatoApp TomatoTomatoApp;
typedef struct _TomatoTomatoAppClass TomatoTomatoAppClass;

#define TOMATO_WIDGET_TYPE_SLIDE (tomato_widget_slide_get_type ())
#define TOMATO_WIDGET_SLIDE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TOMATO_WIDGET_TYPE_SLIDE, TomatoWidgetSlide))
#define TOMATO_WIDGET_SLIDE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TOMATO_WIDGET_TYPE_SLIDE, TomatoWidgetSlideClass))
#define TOMATO_WIDGET_IS_SLIDE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TOMATO_WIDGET_TYPE_SLIDE))
#define TOMATO_WIDGET_IS_SLIDE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TOMATO_WIDGET_TYPE_SLIDE))
#define TOMATO_WIDGET_SLIDE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TOMATO_WIDGET_TYPE_SLIDE, TomatoWidgetSlideClass))

typedef struct _TomatoWidgetSlide TomatoWidgetSlide;
typedef struct _TomatoWidgetSlideClass TomatoWidgetSlideClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define TOMATO_SERVICES_TYPE_SAVED_STATE (tomato_services_saved_state_get_type ())
#define TOMATO_SERVICES_SAVED_STATE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TOMATO_SERVICES_TYPE_SAVED_STATE, TomatoServicesSavedState))
#define TOMATO_SERVICES_SAVED_STATE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TOMATO_SERVICES_TYPE_SAVED_STATE, TomatoServicesSavedStateClass))
#define TOMATO_SERVICES_IS_SAVED_STATE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TOMATO_SERVICES_TYPE_SAVED_STATE))
#define TOMATO_SERVICES_IS_SAVED_STATE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TOMATO_SERVICES_TYPE_SAVED_STATE))
#define TOMATO_SERVICES_SAVED_STATE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TOMATO_SERVICES_TYPE_SAVED_STATE, TomatoServicesSavedStateClass))

typedef struct _TomatoServicesSavedState TomatoServicesSavedState;
typedef struct _TomatoServicesSavedStateClass TomatoServicesSavedStateClass;

#define TOMATO_TYPE_STATUS (tomato_status_get_type ())
#define _g_free0(var) (var = (g_free (var), NULL))

#define TOMATO_WIDGET_TYPE_SCREEN (tomato_widget_screen_get_type ())
#define TOMATO_WIDGET_SCREEN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TOMATO_WIDGET_TYPE_SCREEN, TomatoWidgetScreen))
#define TOMATO_WIDGET_SCREEN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TOMATO_WIDGET_TYPE_SCREEN, TomatoWidgetScreenClass))
#define TOMATO_WIDGET_IS_SCREEN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TOMATO_WIDGET_TYPE_SCREEN))
#define TOMATO_WIDGET_IS_SCREEN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TOMATO_WIDGET_TYPE_SCREEN))
#define TOMATO_WIDGET_SCREEN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TOMATO_WIDGET_TYPE_SCREEN, TomatoWidgetScreenClass))

typedef struct _TomatoWidgetScreen TomatoWidgetScreen;
typedef struct _TomatoWidgetScreenClass TomatoWidgetScreenClass;

#define TOMATO_MANAGERS_TYPE_WORK_MANAGER (tomato_managers_work_manager_get_type ())
#define TOMATO_MANAGERS_WORK_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TOMATO_MANAGERS_TYPE_WORK_MANAGER, TomatoManagersWorkManager))
#define TOMATO_MANAGERS_WORK_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TOMATO_MANAGERS_TYPE_WORK_MANAGER, TomatoManagersWorkManagerClass))
#define TOMATO_MANAGERS_IS_WORK_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TOMATO_MANAGERS_TYPE_WORK_MANAGER))
#define TOMATO_MANAGERS_IS_WORK_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TOMATO_MANAGERS_TYPE_WORK_MANAGER))
#define TOMATO_MANAGERS_WORK_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TOMATO_MANAGERS_TYPE_WORK_MANAGER, TomatoManagersWorkManagerClass))

typedef struct _TomatoManagersWorkManager TomatoManagersWorkManager;
typedef struct _TomatoManagersWorkManagerClass TomatoManagersWorkManagerClass;
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _TomatoWindowMainWindow {
	GtkApplicationWindow parent_instance;
	TomatoWindowMainWindowPrivate * priv;
	gboolean is_hidden;
};

struct _TomatoWindowMainWindowClass {
	GtkApplicationWindowClass parent_class;
};

struct _TomatoWindowMainWindowPrivate {
	TomatoTomatoApp* app;
	GtkHeaderBar* headerbar;
	GtkMenuButton* appmenu;
	GtkMenuItem* preferences;
	TomatoWidgetSlide* slide;
	GtkLabel* countdown_label;
	GtkLabel* total_time_label;
	GtkButton* start;
	GtkButton* resume;
	GtkButton* pause;
	GtkButton* stop;
	GtkButton* skip;
};

typedef enum  {
	TOMATO_STATUS_START,
	TOMATO_STATUS_POMODORO,
	TOMATO_STATUS_SHORT_BREAK,
	TOMATO_STATUS_LONG_BREAK
} TomatoStatus;


static gpointer tomato_window_main_window_parent_class = NULL;
extern TomatoServicesSavedState* tomato_saved;
extern TomatoManagersWorkManager* tomato_work;
extern gboolean tomato_paused;

GType tomato_window_main_window_get_type (void) G_GNUC_CONST;
GType tomato_tomato_app_get_type (void) G_GNUC_CONST;
GType tomato_widget_slide_get_type (void) G_GNUC_CONST;
#define TOMATO_WINDOW_MAIN_WINDOW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TOMATO_WINDOW_TYPE_MAIN_WINDOW, TomatoWindowMainWindowPrivate))
enum  {
	TOMATO_WINDOW_MAIN_WINDOW_DUMMY_PROPERTY
};
TomatoWindowMainWindow* tomato_window_main_window_new (TomatoTomatoApp* app);
TomatoWindowMainWindow* tomato_window_main_window_construct (GType object_type, TomatoTomatoApp* app);
#define CONSTANTS_APP_NAME "Tomato"
TomatoWidgetSlide* tomato_widget_slide_new (void);
TomatoWidgetSlide* tomato_widget_slide_construct (GType object_type);
static void tomato_window_main_window_setup_layout (TomatoWindowMainWindow* self);
static void tomato_window_main_window_setup_style (TomatoWindowMainWindow* self);
void tomato_window_main_window_update_progress (TomatoWindowMainWindow* self);
void tomato_window_main_window_set_pause (TomatoWindowMainWindow* self, gboolean topause);
void tomato_window_main_window_next_status (TomatoWindowMainWindow* self, GtkStackTransitionType transition);
static void tomato_window_main_window_connect_signals (TomatoWindowMainWindow* self);
GType tomato_services_saved_state_get_type (void) G_GNUC_CONST;
GType tomato_status_get_type (void) G_GNUC_CONST;
TomatoStatus tomato_services_saved_state_get_status (TomatoServicesSavedState* self);
void tomato_widget_slide_set_visible_screen (TomatoWidgetSlide* self, const gchar* name, GtkStackTransitionType transition);
gint tomato_services_saved_state_get_pomodoro_count (TomatoServicesSavedState* self);
GType tomato_widget_screen_get_type (void) G_GNUC_CONST;
TomatoWidgetScreen* tomato_widget_slide_get_visible_screen (TomatoWidgetSlide* self);
gchar* tomato_widget_screen_get_name (TomatoWidgetScreen* self);
void tomato_widget_screen_add_progress (TomatoWidgetScreen* self, GtkLabel* countdown, GtkLabel* total_time);
void tomato_window_main_window_update_countdown (TomatoWindowMainWindow* self);
void tomato_window_main_window_update_total_time (TomatoWindowMainWindow* self);
gpointer tomato_managers_work_manager_ref (gpointer instance);
void tomato_managers_work_manager_unref (gpointer instance);
GParamSpec* tomato_managers_param_spec_work_manager (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void tomato_managers_value_set_work_manager (GValue* value, gpointer v_object);
void tomato_managers_value_take_work_manager (GValue* value, gpointer v_object);
gpointer tomato_managers_value_get_work_manager (const GValue* value);
GType tomato_managers_work_manager_get_type (void) G_GNUC_CONST;
gchar* tomato_managers_work_manager_formatted_countdown (TomatoManagersWorkManager* self);
void tomato_window_main_window_update_stop (TomatoWindowMainWindow* self, const gchar* text);
gint tomato_services_saved_state_get_total_time (TomatoServicesSavedState* self);
gchar* tomato_managers_work_manager_formatted_total_time (TomatoManagersWorkManager* self);
static void tomato_window_main_window_setup_headerbar (TomatoWindowMainWindow* self);
static void tomato_window_main_window_setup_stack (TomatoWindowMainWindow* self);
TomatoWidgetScreen* tomato_widget_screen_new (const gchar* name);
TomatoWidgetScreen* tomato_widget_screen_construct (GType object_type, const gchar* name);
void tomato_widget_screen_add_control (TomatoWidgetScreen* self, GtkWidget* control);
void tomato_widget_screen_add_controls (TomatoWidgetScreen* self, GtkWidget** controls, int controls_length1);
void tomato_widget_slide_add_screen (TomatoWidgetSlide* self, TomatoWidgetScreen* screen);
#define CONSTANTS_PKG_DATADIR "/usr/share/tomato"
static void __lambda19_ (TomatoWindowMainWindow* self);
static void ___lambda19__gtk_button_clicked (GtkButton* _sender, gpointer self);
static void __lambda20_ (TomatoWindowMainWindow* self);
static void ___lambda20__gtk_button_clicked (GtkButton* _sender, gpointer self);
static void __lambda21_ (TomatoWindowMainWindow* self);
static void ___lambda21__gtk_button_clicked (GtkButton* _sender, gpointer self);
static void __lambda22_ (TomatoWindowMainWindow* self);
static void ___lambda22__gtk_button_clicked (GtkButton* _sender, gpointer self);
static void __lambda23_ (TomatoWindowMainWindow* self);
static void ___lambda23__gtk_button_clicked (GtkButton* _sender, gpointer self);
static void __lambda24_ (TomatoWindowMainWindow* self);
static void ___lambda24__gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self);
static gboolean __lambda25_ (TomatoWindowMainWindow* self);
static gboolean ___lambda25__gtk_widget_delete_event (GtkWidget* _sender, GdkEventAny* event, gpointer self);
static void tomato_window_main_window_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


static gpointer _g_object_ref0 (gpointer self) {
#line 51 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	return self ? g_object_ref (self) : NULL;
#line 208 "MainWindow.c"
}


TomatoWindowMainWindow* tomato_window_main_window_construct (GType object_type, TomatoTomatoApp* app) {
	TomatoWindowMainWindow * self = NULL;
	TomatoTomatoApp* _tmp0_ = NULL;
	TomatoTomatoApp* _tmp1_ = NULL;
	GtkHeaderBar* _tmp2_ = NULL;
	TomatoWidgetSlide* _tmp3_ = NULL;
	GtkLabel* _tmp4_ = NULL;
	GtkLabel* _tmp5_ = NULL;
	const gchar* _tmp6_ = NULL;
	GtkButton* _tmp7_ = NULL;
	const gchar* _tmp8_ = NULL;
	GtkButton* _tmp9_ = NULL;
	const gchar* _tmp10_ = NULL;
	GtkButton* _tmp11_ = NULL;
	const gchar* _tmp12_ = NULL;
	GtkButton* _tmp13_ = NULL;
	const gchar* _tmp14_ = NULL;
	GtkButton* _tmp15_ = NULL;
#line 49 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_return_val_if_fail (app != NULL, NULL);
#line 49 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	self = (TomatoWindowMainWindow*) g_object_new (object_type, NULL);
#line 51 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp0_ = app;
#line 51 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 51 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_g_object_unref0 (self->priv->app);
#line 51 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	self->priv->app = _tmp1_;
#line 52 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	gtk_window_set_title ((GtkWindow*) self, CONSTANTS_APP_NAME);
#line 53 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	gtk_window_set_position ((GtkWindow*) self, GTK_WIN_POS_CENTER);
#line 54 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	gtk_window_set_resizable ((GtkWindow*) self, FALSE);
#line 55 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	gtk_widget_set_size_request ((GtkWidget*) self, 450, 410);
#line 58 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp2_ = (GtkHeaderBar*) gtk_header_bar_new ();
#line 58 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_object_ref_sink (_tmp2_);
#line 58 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_g_object_unref0 (self->priv->headerbar);
#line 58 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	self->priv->headerbar = _tmp2_;
#line 59 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp3_ = tomato_widget_slide_new ();
#line 59 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_object_ref_sink (_tmp3_);
#line 59 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_g_object_unref0 (self->priv->slide);
#line 59 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	self->priv->slide = _tmp3_;
#line 61 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp4_ = (GtkLabel*) gtk_label_new ("");
#line 61 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_object_ref_sink (_tmp4_);
#line 61 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_g_object_unref0 (self->priv->countdown_label);
#line 61 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	self->priv->countdown_label = _tmp4_;
#line 62 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp5_ = (GtkLabel*) gtk_label_new ("");
#line 62 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_object_ref_sink (_tmp5_);
#line 62 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_g_object_unref0 (self->priv->total_time_label);
#line 62 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	self->priv->total_time_label = _tmp5_;
#line 63 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp6_ = _ ("Start");
#line 63 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp7_ = (GtkButton*) gtk_button_new_with_label (_tmp6_);
#line 63 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_object_ref_sink (_tmp7_);
#line 63 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_g_object_unref0 (self->priv->start);
#line 63 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	self->priv->start = _tmp7_;
#line 64 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp8_ = _ ("Resume");
#line 64 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp9_ = (GtkButton*) gtk_button_new_with_label (_tmp8_);
#line 64 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_object_ref_sink (_tmp9_);
#line 64 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_g_object_unref0 (self->priv->resume);
#line 64 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	self->priv->resume = _tmp9_;
#line 65 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp10_ = _ ("Pause");
#line 65 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp11_ = (GtkButton*) gtk_button_new_with_label (_tmp10_);
#line 65 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_object_ref_sink (_tmp11_);
#line 65 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_g_object_unref0 (self->priv->pause);
#line 65 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	self->priv->pause = _tmp11_;
#line 66 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp12_ = _ ("Stop");
#line 66 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp13_ = (GtkButton*) gtk_button_new_with_label (_tmp12_);
#line 66 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_object_ref_sink (_tmp13_);
#line 66 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_g_object_unref0 (self->priv->stop);
#line 66 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	self->priv->stop = _tmp13_;
#line 67 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp14_ = _ ("Skip");
#line 67 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp15_ = (GtkButton*) gtk_button_new_with_label (_tmp14_);
#line 67 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_object_ref_sink (_tmp15_);
#line 67 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_g_object_unref0 (self->priv->skip);
#line 67 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	self->priv->skip = _tmp15_;
#line 69 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	tomato_window_main_window_setup_layout (self);
#line 70 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	tomato_window_main_window_setup_style (self);
#line 72 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	gtk_widget_show_all ((GtkWidget*) self);
#line 73 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	tomato_window_main_window_update_progress (self);
#line 75 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	tomato_window_main_window_set_pause (self, TRUE);
#line 76 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	tomato_window_main_window_next_status (self, GTK_STACK_TRANSITION_TYPE_NONE);
#line 78 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	tomato_window_main_window_connect_signals (self);
#line 49 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	return self;
#line 348 "MainWindow.c"
}


TomatoWindowMainWindow* tomato_window_main_window_new (TomatoTomatoApp* app) {
#line 49 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	return tomato_window_main_window_construct (TOMATO_WINDOW_TYPE_MAIN_WINDOW, app);
#line 355 "MainWindow.c"
}


void tomato_window_main_window_set_pause (TomatoWindowMainWindow* self, gboolean topause) {
	gboolean _tmp0_ = FALSE;
#line 81 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 82 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp0_ = topause;
#line 82 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	if (_tmp0_) {
#line 367 "MainWindow.c"
		GtkButton* _tmp1_ = NULL;
		GtkButton* _tmp2_ = NULL;
		GtkButton* _tmp3_ = NULL;
#line 83 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp1_ = self->priv->resume;
#line 83 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		gtk_widget_show ((GtkWidget*) _tmp1_);
#line 84 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp2_ = self->priv->resume;
#line 84 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		gtk_widget_grab_focus ((GtkWidget*) _tmp2_);
#line 85 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp3_ = self->priv->pause;
#line 85 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		gtk_widget_hide ((GtkWidget*) _tmp3_);
#line 383 "MainWindow.c"
	} else {
		GtkButton* _tmp4_ = NULL;
		GtkButton* _tmp5_ = NULL;
		GtkButton* _tmp6_ = NULL;
#line 87 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp4_ = self->priv->resume;
#line 87 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		gtk_widget_hide ((GtkWidget*) _tmp4_);
#line 88 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp5_ = self->priv->pause;
#line 88 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		gtk_widget_show ((GtkWidget*) _tmp5_);
#line 89 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp6_ = self->priv->pause;
#line 89 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		gtk_widget_grab_focus ((GtkWidget*) _tmp6_);
#line 400 "MainWindow.c"
	}
}


void tomato_window_main_window_next_status (TomatoWindowMainWindow* self, GtkStackTransitionType transition) {
	TomatoServicesSavedState* _tmp0_ = NULL;
	TomatoStatus _tmp1_ = 0;
	TomatoStatus _tmp2_ = 0;
	TomatoWidgetScreen* screen = NULL;
	TomatoWidgetSlide* _tmp37_ = NULL;
	TomatoWidgetScreen* _tmp38_ = NULL;
	TomatoWidgetScreen* _tmp39_ = NULL;
#line 93 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 95 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp0_ = tomato_saved;
#line 95 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp1_ = tomato_services_saved_state_get_status (_tmp0_);
#line 95 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp2_ = _tmp1_;
#line 95 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	if (_tmp2_ == TOMATO_STATUS_START) {
#line 423 "MainWindow.c"
		TomatoWidgetSlide* _tmp3_ = NULL;
		GtkStackTransitionType _tmp4_ = 0;
		GtkHeaderBar* _tmp5_ = NULL;
		TomatoServicesSavedState* _tmp6_ = NULL;
		gint _tmp7_ = 0;
		gint _tmp8_ = 0;
		gchar* _tmp9_ = NULL;
		gchar* _tmp10_ = NULL;
		GtkMenuButton* _tmp11_ = NULL;
#line 96 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp3_ = self->priv->slide;
#line 96 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp4_ = transition;
#line 96 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		tomato_widget_slide_set_visible_screen (_tmp3_, "start", _tmp4_);
#line 97 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp5_ = self->priv->headerbar;
#line 97 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp6_ = tomato_saved;
#line 97 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp7_ = tomato_services_saved_state_get_pomodoro_count (_tmp6_);
#line 97 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp8_ = _tmp7_;
#line 97 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp9_ = g_strdup_printf ("Pomodoro %d", _tmp8_ + 1);
#line 97 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp10_ = _tmp9_;
#line 97 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		gtk_header_bar_set_title (_tmp5_, _tmp10_);
#line 97 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_g_free0 (_tmp10_);
#line 98 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp11_ = self->priv->appmenu;
#line 98 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		gtk_widget_set_sensitive ((GtkWidget*) _tmp11_, TRUE);
#line 459 "MainWindow.c"
	} else {
		TomatoServicesSavedState* _tmp12_ = NULL;
		TomatoStatus _tmp13_ = 0;
		TomatoStatus _tmp14_ = 0;
#line 99 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp12_ = tomato_saved;
#line 99 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp13_ = tomato_services_saved_state_get_status (_tmp12_);
#line 99 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp14_ = _tmp13_;
#line 99 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		if (_tmp14_ == TOMATO_STATUS_SHORT_BREAK) {
#line 472 "MainWindow.c"
			TomatoWidgetSlide* _tmp15_ = NULL;
			GtkStackTransitionType _tmp16_ = 0;
			GtkHeaderBar* _tmp17_ = NULL;
			const gchar* _tmp18_ = NULL;
			GtkMenuButton* _tmp19_ = NULL;
#line 100 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
			_tmp15_ = self->priv->slide;
#line 100 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
			_tmp16_ = transition;
#line 100 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
			tomato_widget_slide_set_visible_screen (_tmp15_, "break", _tmp16_);
#line 101 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
			_tmp17_ = self->priv->headerbar;
#line 101 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
			_tmp18_ = _ ("Short Break");
#line 101 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
			gtk_header_bar_set_title (_tmp17_, _tmp18_);
#line 102 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
			_tmp19_ = self->priv->appmenu;
#line 102 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
			gtk_widget_set_sensitive ((GtkWidget*) _tmp19_, TRUE);
#line 494 "MainWindow.c"
		} else {
			TomatoServicesSavedState* _tmp20_ = NULL;
			TomatoStatus _tmp21_ = 0;
			TomatoStatus _tmp22_ = 0;
#line 103 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
			_tmp20_ = tomato_saved;
#line 103 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
			_tmp21_ = tomato_services_saved_state_get_status (_tmp20_);
#line 103 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
			_tmp22_ = _tmp21_;
#line 103 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
			if (_tmp22_ == TOMATO_STATUS_LONG_BREAK) {
#line 507 "MainWindow.c"
				TomatoWidgetSlide* _tmp23_ = NULL;
				GtkStackTransitionType _tmp24_ = 0;
				GtkHeaderBar* _tmp25_ = NULL;
				const gchar* _tmp26_ = NULL;
				GtkMenuButton* _tmp27_ = NULL;
#line 104 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
				_tmp23_ = self->priv->slide;
#line 104 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
				_tmp24_ = transition;
#line 104 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
				tomato_widget_slide_set_visible_screen (_tmp23_, "break", _tmp24_);
#line 105 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
				_tmp25_ = self->priv->headerbar;
#line 105 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
				_tmp26_ = _ ("Long Break");
#line 105 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
				gtk_header_bar_set_title (_tmp25_, _tmp26_);
#line 106 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
				_tmp27_ = self->priv->appmenu;
#line 106 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
				gtk_widget_set_sensitive ((GtkWidget*) _tmp27_, TRUE);
#line 529 "MainWindow.c"
			} else {
				TomatoWidgetSlide* _tmp28_ = NULL;
				GtkStackTransitionType _tmp29_ = 0;
				GtkHeaderBar* _tmp30_ = NULL;
				TomatoServicesSavedState* _tmp31_ = NULL;
				gint _tmp32_ = 0;
				gint _tmp33_ = 0;
				gchar* _tmp34_ = NULL;
				gchar* _tmp35_ = NULL;
				GtkMenuButton* _tmp36_ = NULL;
#line 108 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
				_tmp28_ = self->priv->slide;
#line 108 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
				_tmp29_ = transition;
#line 108 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
				tomato_widget_slide_set_visible_screen (_tmp28_, "pomodoro", _tmp29_);
#line 109 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
				_tmp30_ = self->priv->headerbar;
#line 109 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
				_tmp31_ = tomato_saved;
#line 109 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
				_tmp32_ = tomato_services_saved_state_get_pomodoro_count (_tmp31_);
#line 109 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
				_tmp33_ = _tmp32_;
#line 109 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
				_tmp34_ = g_strdup_printf ("Pomodoro %d", _tmp33_ + 1);
#line 109 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
				_tmp35_ = _tmp34_;
#line 109 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
				gtk_header_bar_set_title (_tmp30_, _tmp35_);
#line 109 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
				_g_free0 (_tmp35_);
#line 110 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
				_tmp36_ = self->priv->appmenu;
#line 110 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
				gtk_widget_set_sensitive ((GtkWidget*) _tmp36_, FALSE);
#line 566 "MainWindow.c"
			}
		}
	}
#line 113 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp37_ = self->priv->slide;
#line 113 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp38_ = tomato_widget_slide_get_visible_screen (_tmp37_);
#line 113 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	screen = _tmp38_;
#line 114 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp39_ = screen;
#line 114 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	if (_tmp39_ != NULL) {
#line 580 "MainWindow.c"
		TomatoWidgetScreen* _tmp40_ = NULL;
		gchar* _tmp41_ = NULL;
		gchar* _tmp42_ = NULL;
		gchar* _tmp43_ = NULL;
		gchar* _tmp44_ = NULL;
		TomatoWidgetScreen* _tmp45_ = NULL;
		GtkLabel* _tmp46_ = NULL;
		GtkLabel* _tmp47_ = NULL;
#line 115 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp40_ = screen;
#line 115 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp41_ = tomato_widget_screen_get_name (_tmp40_);
#line 115 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp42_ = _tmp41_;
#line 115 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp43_ = g_strdup_printf ("Current screen: %s", _tmp42_);
#line 115 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp44_ = _tmp43_;
#line 115 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		g_message ("MainWindow.vala:115: %s", _tmp44_);
#line 115 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_g_free0 (_tmp44_);
#line 115 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_g_free0 (_tmp42_);
#line 116 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp45_ = screen;
#line 116 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp46_ = self->priv->countdown_label;
#line 116 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp47_ = self->priv->total_time_label;
#line 116 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		tomato_widget_screen_add_progress (_tmp45_, _tmp46_, _tmp47_);
#line 613 "MainWindow.c"
	} else {
#line 118 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		g_warning ("MainWindow.vala:118: There's no visible screen!");
#line 617 "MainWindow.c"
	}
#line 121 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	tomato_window_main_window_update_progress (self);
#line 93 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_g_object_unref0 (screen);
#line 623 "MainWindow.c"
}


void tomato_window_main_window_update_progress (TomatoWindowMainWindow* self) {
#line 124 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 125 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	tomato_window_main_window_update_countdown (self);
#line 126 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	tomato_window_main_window_update_total_time (self);
#line 634 "MainWindow.c"
}


void tomato_window_main_window_update_countdown (TomatoWindowMainWindow* self) {
	GtkLabel* _tmp0_ = NULL;
	TomatoManagersWorkManager* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
#line 129 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 130 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp0_ = self->priv->countdown_label;
#line 130 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp1_ = tomato_work;
#line 130 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp2_ = tomato_managers_work_manager_formatted_countdown (_tmp1_);
#line 130 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp3_ = _tmp2_;
#line 130 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	gtk_label_set_label (_tmp0_, _tmp3_);
#line 130 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_g_free0 (_tmp3_);
#line 657 "MainWindow.c"
}


void tomato_window_main_window_update_stop (TomatoWindowMainWindow* self, const gchar* text) {
	GtkButton* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
#line 133 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 133 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_return_if_fail (text != NULL);
#line 134 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp0_ = self->priv->stop;
#line 134 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp1_ = text;
#line 134 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	gtk_button_set_label (_tmp0_, _tmp1_);
#line 674 "MainWindow.c"
}


void tomato_window_main_window_update_total_time (TomatoWindowMainWindow* self) {
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
	TomatoServicesSavedState* _tmp4_ = NULL;
	TomatoStatus _tmp5_ = 0;
	TomatoStatus _tmp6_ = 0;
#line 137 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 138 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp4_ = tomato_saved;
#line 138 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp5_ = tomato_services_saved_state_get_status (_tmp4_);
#line 138 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp6_ = _tmp5_;
#line 138 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	if (_tmp6_ == TOMATO_STATUS_START) {
#line 138 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp3_ = TRUE;
#line 698 "MainWindow.c"
	} else {
		TomatoServicesSavedState* _tmp7_ = NULL;
		TomatoStatus _tmp8_ = 0;
		TomatoStatus _tmp9_ = 0;
#line 138 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp7_ = tomato_saved;
#line 138 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp8_ = tomato_services_saved_state_get_status (_tmp7_);
#line 138 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp9_ = _tmp8_;
#line 138 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp3_ = _tmp9_ == TOMATO_STATUS_SHORT_BREAK;
#line 711 "MainWindow.c"
	}
#line 138 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	if (_tmp3_) {
#line 138 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp2_ = TRUE;
#line 717 "MainWindow.c"
	} else {
		TomatoServicesSavedState* _tmp10_ = NULL;
		TomatoStatus _tmp11_ = 0;
		TomatoStatus _tmp12_ = 0;
#line 138 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp10_ = tomato_saved;
#line 138 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp11_ = tomato_services_saved_state_get_status (_tmp10_);
#line 138 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp12_ = _tmp11_;
#line 138 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp2_ = _tmp12_ == TOMATO_STATUS_LONG_BREAK;
#line 730 "MainWindow.c"
	}
#line 138 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	if (_tmp2_) {
#line 138 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp1_ = TRUE;
#line 736 "MainWindow.c"
	} else {
		gboolean _tmp13_ = FALSE;
#line 138 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp13_ = tomato_paused;
#line 138 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp1_ = _tmp13_;
#line 743 "MainWindow.c"
	}
#line 138 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	if (_tmp1_) {
#line 747 "MainWindow.c"
		TomatoServicesSavedState* _tmp14_ = NULL;
		gint _tmp15_ = 0;
		gint _tmp16_ = 0;
#line 138 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp14_ = tomato_saved;
#line 138 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp15_ = tomato_services_saved_state_get_total_time (_tmp14_);
#line 138 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp16_ = _tmp15_;
#line 138 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp0_ = _tmp16_ != 0;
#line 759 "MainWindow.c"
	} else {
#line 138 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp0_ = FALSE;
#line 763 "MainWindow.c"
	}
#line 138 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	if (_tmp0_) {
#line 767 "MainWindow.c"
		GtkLabel* _tmp17_ = NULL;
		TomatoManagersWorkManager* _tmp18_ = NULL;
		gchar* _tmp19_ = NULL;
		gchar* _tmp20_ = NULL;
		const gchar* _tmp21_ = NULL;
		gchar* _tmp22_ = NULL;
		gchar* _tmp23_ = NULL;
#line 139 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp17_ = self->priv->total_time_label;
#line 139 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp18_ = tomato_work;
#line 139 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp19_ = tomato_managers_work_manager_formatted_total_time (_tmp18_);
#line 139 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp20_ = _tmp19_;
#line 139 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp21_ = _ (" of work");
#line 139 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp22_ = g_strconcat (_tmp20_, _tmp21_, NULL);
#line 139 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp23_ = _tmp22_;
#line 139 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		gtk_label_set_label (_tmp17_, _tmp23_);
#line 139 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_g_free0 (_tmp23_);
#line 139 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_g_free0 (_tmp20_);
#line 795 "MainWindow.c"
	} else {
		GtkLabel* _tmp24_ = NULL;
#line 141 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp24_ = self->priv->total_time_label;
#line 141 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		gtk_label_set_label (_tmp24_, "");
#line 802 "MainWindow.c"
	}
}


static void tomato_window_main_window_setup_headerbar (TomatoWindowMainWindow* self) {
	GtkMenuButton* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	GtkMenuItem* _tmp2_ = NULL;
	GtkMenu* menu = NULL;
	GtkMenu* _tmp3_ = NULL;
	GtkMenuItem* _tmp4_ = NULL;
	GtkImage* menu_icon = NULL;
	GtkImage* _tmp5_ = NULL;
	GtkMenuButton* _tmp6_ = NULL;
	GtkMenuButton* _tmp7_ = NULL;
	GtkHeaderBar* _tmp8_ = NULL;
	GtkMenuButton* _tmp9_ = NULL;
	GtkHeaderBar* _tmp10_ = NULL;
	GtkHeaderBar* _tmp11_ = NULL;
#line 145 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 146 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp0_ = (GtkMenuButton*) gtk_menu_button_new ();
#line 146 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_object_ref_sink (_tmp0_);
#line 146 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_g_object_unref0 (self->priv->appmenu);
#line 146 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	self->priv->appmenu = _tmp0_;
#line 147 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp1_ = _ ("Preferences…");
#line 147 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp2_ = (GtkMenuItem*) gtk_menu_item_new_with_label (_tmp1_);
#line 147 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_object_ref_sink (_tmp2_);
#line 147 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_g_object_unref0 (self->priv->preferences);
#line 147 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	self->priv->preferences = _tmp2_;
#line 148 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp3_ = (GtkMenu*) gtk_menu_new ();
#line 148 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_object_ref_sink (_tmp3_);
#line 148 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	menu = _tmp3_;
#line 150 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp4_ = self->priv->preferences;
#line 150 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	gtk_menu_shell_append ((GtkMenuShell*) menu, (GtkWidget*) _tmp4_);
#line 151 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	gtk_widget_show_all ((GtkWidget*) menu);
#line 153 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp5_ = (GtkImage*) gtk_image_new_from_icon_name ("open-menu", GTK_ICON_SIZE_LARGE_TOOLBAR);
#line 153 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_object_ref_sink (_tmp5_);
#line 153 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	menu_icon = _tmp5_;
#line 154 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp6_ = self->priv->appmenu;
#line 154 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	gtk_button_set_image ((GtkButton*) _tmp6_, (GtkWidget*) menu_icon);
#line 155 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp7_ = self->priv->appmenu;
#line 155 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	gtk_menu_button_set_popup (_tmp7_, menu);
#line 157 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp8_ = self->priv->headerbar;
#line 157 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp9_ = self->priv->appmenu;
#line 157 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	gtk_header_bar_pack_end (_tmp8_, (GtkWidget*) _tmp9_);
#line 158 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp10_ = self->priv->headerbar;
#line 158 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	gtk_header_bar_set_show_close_button (_tmp10_, TRUE);
#line 159 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp11_ = self->priv->headerbar;
#line 159 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	gtk_window_set_titlebar ((GtkWindow*) self, (GtkWidget*) _tmp11_);
#line 145 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_g_object_unref0 (menu_icon);
#line 145 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_g_object_unref0 (menu);
#line 886 "MainWindow.c"
}


static void tomato_window_main_window_setup_stack (TomatoWindowMainWindow* self) {
	TomatoWidgetScreen* start_screen = NULL;
	TomatoWidgetScreen* _tmp0_ = NULL;
	GtkButton* _tmp1_ = NULL;
	TomatoWidgetScreen* break_screen = NULL;
	TomatoWidgetScreen* _tmp2_ = NULL;
	GtkButton* _tmp3_ = NULL;
	TomatoWidgetScreen* pomodoro_screen = NULL;
	TomatoWidgetScreen* _tmp4_ = NULL;
	GtkButton* _tmp5_ = NULL;
	GtkWidget* _tmp6_ = NULL;
	GtkButton* _tmp7_ = NULL;
	GtkWidget* _tmp8_ = NULL;
	GtkButton* _tmp9_ = NULL;
	GtkWidget* _tmp10_ = NULL;
	GtkWidget** _tmp11_ = NULL;
	GtkWidget** _tmp12_ = NULL;
	gint _tmp12__length1 = 0;
	TomatoWidgetSlide* _tmp13_ = NULL;
	TomatoWidgetSlide* _tmp14_ = NULL;
	TomatoWidgetSlide* _tmp15_ = NULL;
#line 162 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 163 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp0_ = tomato_widget_screen_new ("start");
#line 163 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_object_ref_sink (_tmp0_);
#line 163 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	start_screen = _tmp0_;
#line 164 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp1_ = self->priv->start;
#line 164 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	tomato_widget_screen_add_control (start_screen, (GtkWidget*) _tmp1_);
#line 166 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp2_ = tomato_widget_screen_new ("break");
#line 166 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_object_ref_sink (_tmp2_);
#line 166 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	break_screen = _tmp2_;
#line 167 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp3_ = self->priv->skip;
#line 167 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	tomato_widget_screen_add_control (break_screen, (GtkWidget*) _tmp3_);
#line 169 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp4_ = tomato_widget_screen_new ("pomodoro");
#line 169 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_object_ref_sink (_tmp4_);
#line 169 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	pomodoro_screen = _tmp4_;
#line 170 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp5_ = self->priv->resume;
#line 170 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp6_ = _g_object_ref0 ((GtkWidget*) _tmp5_);
#line 170 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp7_ = self->priv->pause;
#line 170 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp8_ = _g_object_ref0 ((GtkWidget*) _tmp7_);
#line 170 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp9_ = self->priv->stop;
#line 170 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp10_ = _g_object_ref0 ((GtkWidget*) _tmp9_);
#line 170 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp11_ = g_new0 (GtkWidget*, 3 + 1);
#line 170 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp11_[0] = _tmp6_;
#line 170 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp11_[1] = _tmp8_;
#line 170 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp11_[2] = _tmp10_;
#line 170 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp12_ = _tmp11_;
#line 170 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp12__length1 = 3;
#line 170 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	tomato_widget_screen_add_controls (pomodoro_screen, _tmp12_, 3);
#line 170 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp12_ = (_vala_array_free (_tmp12_, _tmp12__length1, (GDestroyNotify) g_object_unref), NULL);
#line 172 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp13_ = self->priv->slide;
#line 172 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	tomato_widget_slide_add_screen (_tmp13_, start_screen);
#line 173 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp14_ = self->priv->slide;
#line 173 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	tomato_widget_slide_add_screen (_tmp14_, break_screen);
#line 174 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp15_ = self->priv->slide;
#line 174 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	tomato_widget_slide_add_screen (_tmp15_, pomodoro_screen);
#line 162 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_g_object_unref0 (pomodoro_screen);
#line 162 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_g_object_unref0 (break_screen);
#line 162 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_g_object_unref0 (start_screen);
#line 985 "MainWindow.c"
}


static void tomato_window_main_window_setup_layout (TomatoWindowMainWindow* self) {
	TomatoWidgetSlide* _tmp0_ = NULL;
#line 177 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 178 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	tomato_window_main_window_setup_headerbar (self);
#line 179 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	tomato_window_main_window_setup_stack (self);
#line 180 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp0_ = self->priv->slide;
#line 180 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp0_);
#line 1001 "MainWindow.c"
}


static void tomato_window_main_window_setup_style (TomatoWindowMainWindow* self) {
	gchar* css_file = NULL;
	gchar* _tmp0_ = NULL;
	GtkCssProvider* provider = NULL;
	GtkCssProvider* _tmp1_ = NULL;
	GtkLabel* _tmp6_ = NULL;
	GtkStyleContext* _tmp7_ = NULL;
	GtkLabel* _tmp8_ = NULL;
	GtkStyleContext* _tmp9_ = NULL;
	GtkButton* _tmp10_ = NULL;
	GtkStyleContext* _tmp11_ = NULL;
	GtkButton* _tmp12_ = NULL;
	GtkStyleContext* _tmp13_ = NULL;
	GtkButton* _tmp14_ = NULL;
	GtkStyleContext* _tmp15_ = NULL;
	GtkButton* _tmp16_ = NULL;
	GtkStyleContext* _tmp17_ = NULL;
	GtkButton* _tmp18_ = NULL;
	GtkStyleContext* _tmp19_ = NULL;
	TomatoWidgetSlide* _tmp20_ = NULL;
	GtkWidget* _tmp21_ = NULL;
	GtkStyleContext* _tmp22_ = NULL;
	TomatoWidgetSlide* _tmp23_ = NULL;
	GtkWidget* _tmp24_ = NULL;
	GtkStyleContext* _tmp25_ = NULL;
	TomatoWidgetSlide* _tmp26_ = NULL;
	GtkWidget* _tmp27_ = NULL;
	GtkStyleContext* _tmp28_ = NULL;
	GError * _inner_error_ = NULL;
#line 183 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 185 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp0_ = g_strdup (CONSTANTS_PKG_DATADIR "/style/window.css");
#line 185 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	css_file = _tmp0_;
#line 186 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp1_ = gtk_css_provider_new ();
#line 186 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	provider = _tmp1_;
#line 1044 "MainWindow.c"
	{
		GdkScreen* _tmp2_ = NULL;
#line 188 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		gtk_css_provider_load_from_path (provider, css_file, &_inner_error_);
#line 188 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 1051 "MainWindow.c"
			goto __catch0_g_error;
		}
#line 189 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp2_ = gdk_screen_get_default ();
#line 189 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		gtk_style_context_add_provider_for_screen (_tmp2_, (GtkStyleProvider*) provider, (guint) GTK_STYLE_PROVIDER_PRIORITY_USER);
#line 1058 "MainWindow.c"
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		FILE* _tmp3_ = NULL;
		GError* _tmp4_ = NULL;
		const gchar* _tmp5_ = NULL;
#line 187 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		e = _inner_error_;
#line 187 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_inner_error_ = NULL;
#line 192 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp3_ = stderr;
#line 192 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp4_ = e;
#line 192 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_tmp5_ = _tmp4_->message;
#line 192 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		fprintf (_tmp3_, "Error: %s", _tmp5_);
#line 187 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_g_error_free0 (e);
#line 1081 "MainWindow.c"
	}
	__finally0:
#line 187 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 187 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_g_object_unref0 (provider);
#line 187 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		_g_free0 (css_file);
#line 187 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 187 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		g_clear_error (&_inner_error_);
#line 187 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		return;
#line 1096 "MainWindow.c"
	}
#line 196 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp6_ = self->priv->countdown_label;
#line 196 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp7_ = gtk_widget_get_style_context ((GtkWidget*) _tmp6_);
#line 196 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	gtk_style_context_add_class (_tmp7_, "countdown");
#line 197 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp8_ = self->priv->total_time_label;
#line 197 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp9_ = gtk_widget_get_style_context ((GtkWidget*) _tmp8_);
#line 197 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	gtk_style_context_add_class (_tmp9_, "total-time");
#line 199 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp10_ = self->priv->start;
#line 199 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp11_ = gtk_widget_get_style_context ((GtkWidget*) _tmp10_);
#line 199 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	gtk_style_context_add_class (_tmp11_, "start-button");
#line 200 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp12_ = self->priv->skip;
#line 200 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp13_ = gtk_widget_get_style_context ((GtkWidget*) _tmp12_);
#line 200 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	gtk_style_context_add_class (_tmp13_, "break-button");
#line 201 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp14_ = self->priv->resume;
#line 201 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp15_ = gtk_widget_get_style_context ((GtkWidget*) _tmp14_);
#line 201 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	gtk_style_context_add_class (_tmp15_, "pomodoro-button");
#line 202 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp16_ = self->priv->pause;
#line 202 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp17_ = gtk_widget_get_style_context ((GtkWidget*) _tmp16_);
#line 202 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	gtk_style_context_add_class (_tmp17_, "pomodoro-button");
#line 203 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp18_ = self->priv->stop;
#line 203 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp19_ = gtk_widget_get_style_context ((GtkWidget*) _tmp18_);
#line 203 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	gtk_style_context_add_class (_tmp19_, "pomodoro-button");
#line 205 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp20_ = self->priv->slide;
#line 205 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp21_ = gtk_stack_get_child_by_name ((GtkStack*) _tmp20_, "start");
#line 205 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp22_ = gtk_widget_get_style_context (_tmp21_);
#line 205 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	gtk_style_context_add_class (_tmp22_, "start-window");
#line 206 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp23_ = self->priv->slide;
#line 206 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp24_ = gtk_stack_get_child_by_name ((GtkStack*) _tmp23_, "pomodoro");
#line 206 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp25_ = gtk_widget_get_style_context (_tmp24_);
#line 206 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	gtk_style_context_add_class (_tmp25_, "pomodoro-window");
#line 207 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp26_ = self->priv->slide;
#line 207 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp27_ = gtk_stack_get_child_by_name ((GtkStack*) _tmp26_, "break");
#line 207 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp28_ = gtk_widget_get_style_context (_tmp27_);
#line 207 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	gtk_style_context_add_class (_tmp28_, "break-window");
#line 183 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_g_object_unref0 (provider);
#line 183 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_g_free0 (css_file);
#line 1168 "MainWindow.c"
}


static void __lambda19_ (TomatoWindowMainWindow* self) {
#line 211 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_signal_emit_by_name (self, "start-clicked");
#line 1175 "MainWindow.c"
}


static void ___lambda19__gtk_button_clicked (GtkButton* _sender, gpointer self) {
#line 211 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	__lambda19_ ((TomatoWindowMainWindow*) self);
#line 1182 "MainWindow.c"
}


static void __lambda20_ (TomatoWindowMainWindow* self) {
#line 212 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_signal_emit_by_name (self, "resume-clicked");
#line 1189 "MainWindow.c"
}


static void ___lambda20__gtk_button_clicked (GtkButton* _sender, gpointer self) {
#line 212 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	__lambda20_ ((TomatoWindowMainWindow*) self);
#line 1196 "MainWindow.c"
}


static void __lambda21_ (TomatoWindowMainWindow* self) {
#line 213 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_signal_emit_by_name (self, "pause-clicked");
#line 1203 "MainWindow.c"
}


static void ___lambda21__gtk_button_clicked (GtkButton* _sender, gpointer self) {
#line 213 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	__lambda21_ ((TomatoWindowMainWindow*) self);
#line 1210 "MainWindow.c"
}


static void __lambda22_ (TomatoWindowMainWindow* self) {
#line 214 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_signal_emit_by_name (self, "stop-clicked");
#line 1217 "MainWindow.c"
}


static void ___lambda22__gtk_button_clicked (GtkButton* _sender, gpointer self) {
#line 214 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	__lambda22_ ((TomatoWindowMainWindow*) self);
#line 1224 "MainWindow.c"
}


static void __lambda23_ (TomatoWindowMainWindow* self) {
#line 215 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_signal_emit_by_name (self, "skip-clicked");
#line 1231 "MainWindow.c"
}


static void ___lambda23__gtk_button_clicked (GtkButton* _sender, gpointer self) {
#line 215 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	__lambda23_ ((TomatoWindowMainWindow*) self);
#line 1238 "MainWindow.c"
}


static void __lambda24_ (TomatoWindowMainWindow* self) {
#line 216 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_signal_emit_by_name (self, "preferences-clicked");
#line 1245 "MainWindow.c"
}


static void ___lambda24__gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self) {
#line 216 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	__lambda24_ ((TomatoWindowMainWindow*) self);
#line 1252 "MainWindow.c"
}


static gboolean __lambda25_ (TomatoWindowMainWindow* self) {
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
#line 219 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp0_ = tomato_paused;
#line 219 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	if (!_tmp0_) {
#line 220 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		gtk_widget_hide ((GtkWidget*) self);
#line 221 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		result = TRUE;
#line 221 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
		return result;
#line 1269 "MainWindow.c"
	}
#line 223 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	gtk_main_quit ();
#line 224 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	result = FALSE;
#line 224 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	return result;
#line 1277 "MainWindow.c"
}


static gboolean ___lambda25__gtk_widget_delete_event (GtkWidget* _sender, GdkEventAny* event, gpointer self) {
	gboolean result;
	result = __lambda25_ ((TomatoWindowMainWindow*) self);
#line 218 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	return result;
#line 1286 "MainWindow.c"
}


static void tomato_window_main_window_connect_signals (TomatoWindowMainWindow* self) {
	GtkButton* _tmp0_ = NULL;
	GtkButton* _tmp1_ = NULL;
	GtkButton* _tmp2_ = NULL;
	GtkButton* _tmp3_ = NULL;
	GtkButton* _tmp4_ = NULL;
	GtkMenuItem* _tmp5_ = NULL;
#line 210 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 211 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp0_ = self->priv->start;
#line 211 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_signal_connect_object (_tmp0_, "clicked", (GCallback) ___lambda19__gtk_button_clicked, self, 0);
#line 212 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp1_ = self->priv->resume;
#line 212 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_signal_connect_object (_tmp1_, "clicked", (GCallback) ___lambda20__gtk_button_clicked, self, 0);
#line 213 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp2_ = self->priv->pause;
#line 213 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_signal_connect_object (_tmp2_, "clicked", (GCallback) ___lambda21__gtk_button_clicked, self, 0);
#line 214 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp3_ = self->priv->stop;
#line 214 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_signal_connect_object (_tmp3_, "clicked", (GCallback) ___lambda22__gtk_button_clicked, self, 0);
#line 215 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp4_ = self->priv->skip;
#line 215 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_signal_connect_object (_tmp4_, "clicked", (GCallback) ___lambda23__gtk_button_clicked, self, 0);
#line 216 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_tmp5_ = self->priv->preferences;
#line 216 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_signal_connect_object (_tmp5_, "activate", (GCallback) ___lambda24__gtk_menu_item_activate, self, 0);
#line 218 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_signal_connect_object ((GtkWidget*) self, "delete-event", (GCallback) ___lambda25__gtk_widget_delete_event, self, 0);
#line 1325 "MainWindow.c"
}


static void tomato_window_main_window_class_init (TomatoWindowMainWindowClass * klass) {
#line 21 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	tomato_window_main_window_parent_class = g_type_class_peek_parent (klass);
#line 21 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_type_class_add_private (klass, sizeof (TomatoWindowMainWindowPrivate));
#line 21 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	G_OBJECT_CLASS (klass)->finalize = tomato_window_main_window_finalize;
#line 21 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_signal_new ("preferences_clicked", TOMATO_WINDOW_TYPE_MAIN_WINDOW, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
#line 21 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_signal_new ("start_clicked", TOMATO_WINDOW_TYPE_MAIN_WINDOW, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
#line 21 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_signal_new ("resume_clicked", TOMATO_WINDOW_TYPE_MAIN_WINDOW, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
#line 21 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_signal_new ("pause_clicked", TOMATO_WINDOW_TYPE_MAIN_WINDOW, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
#line 21 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_signal_new ("stop_clicked", TOMATO_WINDOW_TYPE_MAIN_WINDOW, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
#line 21 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_signal_new ("skip_clicked", TOMATO_WINDOW_TYPE_MAIN_WINDOW, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
#line 21 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	g_signal_new ("closed", TOMATO_WINDOW_TYPE_MAIN_WINDOW, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
#line 1350 "MainWindow.c"
}


static void tomato_window_main_window_instance_init (TomatoWindowMainWindow * self) {
#line 21 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	self->priv = TOMATO_WINDOW_MAIN_WINDOW_GET_PRIVATE (self);
#line 23 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	self->is_hidden = FALSE;
#line 1359 "MainWindow.c"
}


static void tomato_window_main_window_finalize (GObject* obj) {
	TomatoWindowMainWindow * self;
#line 21 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TOMATO_WINDOW_TYPE_MAIN_WINDOW, TomatoWindowMainWindow);
#line 33 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_g_object_unref0 (self->priv->app);
#line 35 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_g_object_unref0 (self->priv->headerbar);
#line 36 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_g_object_unref0 (self->priv->appmenu);
#line 37 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_g_object_unref0 (self->priv->preferences);
#line 38 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_g_object_unref0 (self->priv->slide);
#line 40 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_g_object_unref0 (self->priv->countdown_label);
#line 41 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_g_object_unref0 (self->priv->total_time_label);
#line 42 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_g_object_unref0 (self->priv->start);
#line 43 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_g_object_unref0 (self->priv->resume);
#line 44 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_g_object_unref0 (self->priv->pause);
#line 45 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_g_object_unref0 (self->priv->stop);
#line 46 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	_g_object_unref0 (self->priv->skip);
#line 21 "/home/lamm/Projetos/tomato/src/Windows/MainWindow.vala"
	G_OBJECT_CLASS (tomato_window_main_window_parent_class)->finalize (obj);
#line 1393 "MainWindow.c"
}


GType tomato_window_main_window_get_type (void) {
	static volatile gsize tomato_window_main_window_type_id__volatile = 0;
	if (g_once_init_enter (&tomato_window_main_window_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (TomatoWindowMainWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) tomato_window_main_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TomatoWindowMainWindow), 0, (GInstanceInitFunc) tomato_window_main_window_instance_init, NULL };
		GType tomato_window_main_window_type_id;
		tomato_window_main_window_type_id = g_type_register_static (gtk_application_window_get_type (), "TomatoWindowMainWindow", &g_define_type_info, 0);
		g_once_init_leave (&tomato_window_main_window_type_id__volatile, tomato_window_main_window_type_id);
	}
	return tomato_window_main_window_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



