/* PreferencesDialog.c generated by valac 0.34.7, the Vala compiler
 * generated from PreferencesDialog.vala, do not modify */

/* Copyright 2015 LuizAugustoMorais
*
* This file is part of Tomato.
*
* Tomato is free software: you can redistribute it
* and/or modify it under the terms of the GNU General Public License as
* published by the Free Software Foundation, either version 3 of the
* License, or (at your option) any later version.
*
* Tomato is distributed in the hope that it will be
* useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
* Public License for more details.
*
* You should have received a copy of the GNU General Public License along
* with Tomato. If not, see http://www.gnu.org/licenses/.
*/

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <glib/gi18n-lib.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <granite.h>
#include <gio/gio.h>


#define TOMATO_WINDOW_TYPE_PREFERENCES_DIALOG (tomato_window_preferences_dialog_get_type ())
#define TOMATO_WINDOW_PREFERENCES_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TOMATO_WINDOW_TYPE_PREFERENCES_DIALOG, TomatoWindowPreferencesDialog))
#define TOMATO_WINDOW_PREFERENCES_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TOMATO_WINDOW_TYPE_PREFERENCES_DIALOG, TomatoWindowPreferencesDialogClass))
#define TOMATO_WINDOW_IS_PREFERENCES_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TOMATO_WINDOW_TYPE_PREFERENCES_DIALOG))
#define TOMATO_WINDOW_IS_PREFERENCES_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TOMATO_WINDOW_TYPE_PREFERENCES_DIALOG))
#define TOMATO_WINDOW_PREFERENCES_DIALOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TOMATO_WINDOW_TYPE_PREFERENCES_DIALOG, TomatoWindowPreferencesDialogClass))

typedef struct _TomatoWindowPreferencesDialog TomatoWindowPreferencesDialog;
typedef struct _TomatoWindowPreferencesDialogClass TomatoWindowPreferencesDialogClass;
typedef struct _TomatoWindowPreferencesDialogPrivate TomatoWindowPreferencesDialogPrivate;

#define TOMATO_WIDGET_TYPE_VALUE_RANGE (tomato_widget_value_range_get_type ())
#define TOMATO_WIDGET_VALUE_RANGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TOMATO_WIDGET_TYPE_VALUE_RANGE, TomatoWidgetValueRange))
#define TOMATO_WIDGET_VALUE_RANGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TOMATO_WIDGET_TYPE_VALUE_RANGE, TomatoWidgetValueRangeClass))
#define TOMATO_WIDGET_IS_VALUE_RANGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TOMATO_WIDGET_TYPE_VALUE_RANGE))
#define TOMATO_WIDGET_IS_VALUE_RANGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TOMATO_WIDGET_TYPE_VALUE_RANGE))
#define TOMATO_WIDGET_VALUE_RANGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TOMATO_WIDGET_TYPE_VALUE_RANGE, TomatoWidgetValueRangeClass))

typedef struct _TomatoWidgetValueRange TomatoWidgetValueRange;
typedef struct _TomatoWidgetValueRangeClass TomatoWidgetValueRangeClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define TOMATO_SERVICES_TYPE_SETTINGS (tomato_services_settings_get_type ())
#define TOMATO_SERVICES_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TOMATO_SERVICES_TYPE_SETTINGS, TomatoServicesSettings))
#define TOMATO_SERVICES_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TOMATO_SERVICES_TYPE_SETTINGS, TomatoServicesSettingsClass))
#define TOMATO_SERVICES_IS_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TOMATO_SERVICES_TYPE_SETTINGS))
#define TOMATO_SERVICES_IS_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TOMATO_SERVICES_TYPE_SETTINGS))
#define TOMATO_SERVICES_SETTINGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TOMATO_SERVICES_TYPE_SETTINGS, TomatoServicesSettingsClass))

typedef struct _TomatoServicesSettings TomatoServicesSettings;
typedef struct _TomatoServicesSettingsClass TomatoServicesSettingsClass;

#define TOMATO_SERVICES_TYPE_PREFERENCES (tomato_services_preferences_get_type ())
#define TOMATO_SERVICES_PREFERENCES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TOMATO_SERVICES_TYPE_PREFERENCES, TomatoServicesPreferences))
#define TOMATO_SERVICES_PREFERENCES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TOMATO_SERVICES_TYPE_PREFERENCES, TomatoServicesPreferencesClass))
#define TOMATO_SERVICES_IS_PREFERENCES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TOMATO_SERVICES_TYPE_PREFERENCES))
#define TOMATO_SERVICES_IS_PREFERENCES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TOMATO_SERVICES_TYPE_PREFERENCES))
#define TOMATO_SERVICES_PREFERENCES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TOMATO_SERVICES_TYPE_PREFERENCES, TomatoServicesPreferencesClass))

typedef struct _TomatoServicesPreferences TomatoServicesPreferences;
typedef struct _TomatoServicesPreferencesClass TomatoServicesPreferencesClass;

#define TOMATO_SERVICES_TYPE_SAVED_STATE (tomato_services_saved_state_get_type ())
#define TOMATO_SERVICES_SAVED_STATE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TOMATO_SERVICES_TYPE_SAVED_STATE, TomatoServicesSavedState))
#define TOMATO_SERVICES_SAVED_STATE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TOMATO_SERVICES_TYPE_SAVED_STATE, TomatoServicesSavedStateClass))
#define TOMATO_SERVICES_IS_SAVED_STATE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TOMATO_SERVICES_TYPE_SAVED_STATE))
#define TOMATO_SERVICES_IS_SAVED_STATE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TOMATO_SERVICES_TYPE_SAVED_STATE))
#define TOMATO_SERVICES_SAVED_STATE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TOMATO_SERVICES_TYPE_SAVED_STATE, TomatoServicesSavedStateClass))

typedef struct _TomatoServicesSavedState TomatoServicesSavedState;
typedef struct _TomatoServicesSavedStateClass TomatoServicesSavedStateClass;

#define TOMATO_TYPE_STATUS (tomato_status_get_type ())
#define _g_free0(var) (var = (g_free (var), NULL))

struct _TomatoWindowPreferencesDialog {
	GtkDialog parent_instance;
	TomatoWindowPreferencesDialogPrivate * priv;
};

struct _TomatoWindowPreferencesDialogClass {
	GtkDialogClass parent_class;
};

struct _TomatoWindowPreferencesDialogPrivate {
	GtkStack* stack;
	GtkStackSwitcher* stackswitcher;
	TomatoWidgetValueRange* pomodoro_scale;
	TomatoWidgetValueRange* short_break_scale;
	TomatoWidgetValueRange* long_break_scale;
	TomatoWidgetValueRange* long_break_delay_scale;
	GtkSwitch* reset_work_everyday;
	GtkSwitch* pause_after_break;
	GtkSwitch* auto_stop_enabled;
	GtkSwitch* pomodoro_sound_enabled;
	GtkSwitch* debug_switch;
	GtkButton* reset_timings;
	GtkButton* reset_work;
};

typedef enum  {
	TOMATO_STATUS_START,
	TOMATO_STATUS_POMODORO,
	TOMATO_STATUS_SHORT_BREAK,
	TOMATO_STATUS_LONG_BREAK
} TomatoStatus;


static gpointer tomato_window_preferences_dialog_parent_class = NULL;
extern TomatoServicesSettings* tomato_settings;
extern TomatoServicesPreferences* tomato_preferences;
extern TomatoServicesSavedState* tomato_saved;

GType tomato_window_preferences_dialog_get_type (void) G_GNUC_CONST;
GType tomato_widget_value_range_get_type (void) G_GNUC_CONST;
#define TOMATO_WINDOW_PREFERENCES_DIALOG_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TOMATO_WINDOW_TYPE_PREFERENCES_DIALOG, TomatoWindowPreferencesDialogPrivate))
enum  {
	TOMATO_WINDOW_PREFERENCES_DIALOG_DUMMY_PROPERTY
};
TomatoWindowPreferencesDialog* tomato_window_preferences_dialog_new (GtkWindow* parent);
TomatoWindowPreferencesDialog* tomato_window_preferences_dialog_construct (GType object_type, GtkWindow* parent);
static void tomato_window_preferences_dialog_bind_and_init_options (TomatoWindowPreferencesDialog* self);
static void tomato_window_preferences_dialog_create_ui (TomatoWindowPreferencesDialog* self);
void tomato_window_preferences_dialog_update_timing_sensitivity (TomatoWindowPreferencesDialog* self);
void tomato_window_preferences_dialog_update_work_sensitivity (TomatoWindowPreferencesDialog* self);
static void tomato_window_preferences_dialog_connect_signals (TomatoWindowPreferencesDialog* self);
TomatoWidgetValueRange* tomato_widget_value_range_new (gdouble min, gdouble max, gdouble step, const gchar* display, const gchar* plural);
TomatoWidgetValueRange* tomato_widget_value_range_construct (GType object_type, gdouble min, gdouble max, gdouble step, const gchar* display, const gchar* plural);
GType tomato_services_settings_get_type (void) G_GNUC_CONST;
GType tomato_services_preferences_get_type (void) G_GNUC_CONST;
gboolean tomato_services_preferences_get_debug_mode (TomatoServicesPreferences* self);
static GtkWidget* tomato_window_preferences_dialog_get_timing_box (TomatoWindowPreferencesDialog* self);
static GtkWidget* tomato_window_preferences_dialog_get_misc_box (TomatoWindowPreferencesDialog* self);
static void __lambda6_ (TomatoWindowPreferencesDialog* self);
static void ___lambda6__gtk_button_clicked (GtkButton* _sender, gpointer self);
static GtkGrid* tomato_window_preferences_dialog_make_grid (TomatoWindowPreferencesDialog* self);
static void tomato_window_preferences_dialog_add_option (TomatoWindowPreferencesDialog* self, GtkGrid* grid, GtkWidget* label, GtkWidget* switcher, gint* row, gint margin_top);
static void tomato_window_preferences_dialog_add_section (TomatoWindowPreferencesDialog* self, GtkGrid* grid, GtkLabel* name, gint* row);
static void tomato_window_preferences_dialog_reset_scales (TomatoWindowPreferencesDialog* self);
#define DEFAULT_POMODORO_DURATION 25
void tomato_widget_value_range_set_current_value (TomatoWidgetValueRange* self, gint value);
#define DEFAULT_SHORT_BREAK_DURATION 5
#define DEFAULT_LONG_BREAK_DURATION 15
#define DEFAULT_LONG_BREAK_DELAY 4
gint tomato_widget_value_range_get_current_value (TomatoWidgetValueRange* self);
GType tomato_services_saved_state_get_type (void) G_GNUC_CONST;
gint tomato_services_saved_state_get_pomodoro_count (TomatoServicesSavedState* self);
gint tomato_services_saved_state_get_total_time (TomatoServicesSavedState* self);
GType tomato_status_get_type (void) G_GNUC_CONST;
TomatoStatus tomato_services_saved_state_get_status (TomatoServicesSavedState* self);
static void __lambda7_ (TomatoWindowPreferencesDialog* self);
static void ___lambda7__tomato_widget_value_range_changed (TomatoWidgetValueRange* _sender, gpointer self);
static void __lambda8_ (TomatoWindowPreferencesDialog* self);
static void ___lambda8__tomato_widget_value_range_changed (TomatoWidgetValueRange* _sender, gpointer self);
static void __lambda9_ (TomatoWindowPreferencesDialog* self);
static void ___lambda9__tomato_widget_value_range_changed (TomatoWidgetValueRange* _sender, gpointer self);
static void __lambda10_ (TomatoWindowPreferencesDialog* self);
static void ___lambda10__tomato_widget_value_range_changed (TomatoWidgetValueRange* _sender, gpointer self);
static void _tomato_window_preferences_dialog_reset_scales_gtk_button_clicked (GtkButton* _sender, gpointer self);
static void __lambda11_ (TomatoWindowPreferencesDialog* self);
static void ___lambda11__gtk_button_clicked (GtkButton* _sender, gpointer self);
static void tomato_window_preferences_dialog_finalize (GObject* obj);


TomatoWindowPreferencesDialog* tomato_window_preferences_dialog_construct (GType object_type, GtkWindow* parent) {
	TomatoWindowPreferencesDialog * self = NULL;
	GtkWindow* _tmp0_ = NULL;
	const gchar* _tmp2_ = NULL;
	GtkStack* _tmp3_ = NULL;
	GtkStackSwitcher* _tmp4_ = NULL;
	GtkStackSwitcher* _tmp5_ = NULL;
	GtkStack* _tmp6_ = NULL;
	GtkStackSwitcher* _tmp7_ = NULL;
#line 52 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	self = (TomatoWindowPreferencesDialog*) g_object_new (object_type, NULL);
#line 54 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp0_ = parent;
#line 54 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	if (_tmp0_ != NULL) {
#line 194 "PreferencesDialog.c"
		GtkWindow* _tmp1_ = NULL;
#line 55 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp1_ = parent;
#line 55 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		gtk_window_set_transient_for ((GtkWindow*) self, _tmp1_);
#line 200 "PreferencesDialog.c"
	}
#line 59 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp2_ = _ ("Preferences");
#line 59 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	gtk_window_set_title ((GtkWindow*) self, _tmp2_);
#line 60 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	gtk_window_set_resizable ((GtkWindow*) self, FALSE);
#line 61 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	gtk_window_set_deletable ((GtkWindow*) self, FALSE);
#line 62 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	gtk_window_set_modal ((GtkWindow*) self, TRUE);
#line 66 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp3_ = (GtkStack*) gtk_stack_new ();
#line 66 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_object_ref_sink (_tmp3_);
#line 66 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_g_object_unref0 (self->priv->stack);
#line 66 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	self->priv->stack = _tmp3_;
#line 67 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp4_ = (GtkStackSwitcher*) gtk_stack_switcher_new ();
#line 67 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_object_ref_sink (_tmp4_);
#line 67 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_g_object_unref0 (self->priv->stackswitcher);
#line 67 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	self->priv->stackswitcher = _tmp4_;
#line 69 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp5_ = self->priv->stackswitcher;
#line 69 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp6_ = self->priv->stack;
#line 69 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	gtk_stack_switcher_set_stack (_tmp5_, _tmp6_);
#line 70 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp7_ = self->priv->stackswitcher;
#line 70 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	gtk_widget_set_halign ((GtkWidget*) _tmp7_, GTK_ALIGN_CENTER);
#line 72 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	tomato_window_preferences_dialog_bind_and_init_options (self);
#line 73 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	tomato_window_preferences_dialog_create_ui (self);
#line 74 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	tomato_window_preferences_dialog_update_timing_sensitivity (self);
#line 75 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	tomato_window_preferences_dialog_update_work_sensitivity (self);
#line 76 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	tomato_window_preferences_dialog_connect_signals (self);
#line 52 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	return self;
#line 250 "PreferencesDialog.c"
}


TomatoWindowPreferencesDialog* tomato_window_preferences_dialog_new (GtkWindow* parent) {
#line 52 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	return tomato_window_preferences_dialog_construct (TOMATO_WINDOW_TYPE_PREFERENCES_DIALOG, parent);
#line 257 "PreferencesDialog.c"
}


static void tomato_window_preferences_dialog_bind_and_init_options (TomatoWindowPreferencesDialog* self) {
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	TomatoWidgetValueRange* _tmp2_ = NULL;
	TomatoServicesSettings* _tmp3_ = NULL;
	GSettings* _tmp4_ = NULL;
	GSettings* _tmp5_ = NULL;
	TomatoWidgetValueRange* _tmp6_ = NULL;
	const gchar* _tmp7_ = NULL;
	const gchar* _tmp8_ = NULL;
	TomatoWidgetValueRange* _tmp9_ = NULL;
	TomatoServicesSettings* _tmp10_ = NULL;
	GSettings* _tmp11_ = NULL;
	GSettings* _tmp12_ = NULL;
	TomatoWidgetValueRange* _tmp13_ = NULL;
	const gchar* _tmp14_ = NULL;
	const gchar* _tmp15_ = NULL;
	TomatoWidgetValueRange* _tmp16_ = NULL;
	TomatoServicesSettings* _tmp17_ = NULL;
	GSettings* _tmp18_ = NULL;
	GSettings* _tmp19_ = NULL;
	TomatoWidgetValueRange* _tmp20_ = NULL;
	const gchar* _tmp21_ = NULL;
	const gchar* _tmp22_ = NULL;
	TomatoWidgetValueRange* _tmp23_ = NULL;
	TomatoServicesSettings* _tmp24_ = NULL;
	GSettings* _tmp25_ = NULL;
	GSettings* _tmp26_ = NULL;
	TomatoWidgetValueRange* _tmp27_ = NULL;
	GtkSwitch* _tmp28_ = NULL;
	TomatoServicesPreferences* _tmp29_ = NULL;
	GSettings* _tmp30_ = NULL;
	GSettings* _tmp31_ = NULL;
	GtkSwitch* _tmp32_ = NULL;
	GtkSwitch* _tmp33_ = NULL;
	TomatoServicesPreferences* _tmp34_ = NULL;
	GSettings* _tmp35_ = NULL;
	GSettings* _tmp36_ = NULL;
	GtkSwitch* _tmp37_ = NULL;
	GtkSwitch* _tmp38_ = NULL;
	TomatoServicesPreferences* _tmp39_ = NULL;
	GSettings* _tmp40_ = NULL;
	GSettings* _tmp41_ = NULL;
	GtkSwitch* _tmp42_ = NULL;
	GtkSwitch* _tmp43_ = NULL;
	TomatoServicesPreferences* _tmp44_ = NULL;
	GSettings* _tmp45_ = NULL;
	GSettings* _tmp46_ = NULL;
	GtkSwitch* _tmp47_ = NULL;
	TomatoServicesPreferences* _tmp48_ = NULL;
	gboolean _tmp49_ = FALSE;
	gboolean _tmp50_ = FALSE;
	const gchar* _tmp70_ = NULL;
	GtkButton* _tmp71_ = NULL;
	const gchar* _tmp72_ = NULL;
	GtkButton* _tmp73_ = NULL;
#line 79 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_return_if_fail (self != NULL);
#line 82 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp0_ = _ ("minute");
#line 82 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp1_ = _ ("minutes");
#line 82 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp2_ = tomato_widget_value_range_new ((gdouble) 5, (gdouble) 60, (gdouble) 1, _tmp0_, _tmp1_);
#line 82 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_object_ref_sink (_tmp2_);
#line 82 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_g_object_unref0 (self->priv->pomodoro_scale);
#line 82 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	self->priv->pomodoro_scale = _tmp2_;
#line 83 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp3_ = tomato_settings;
#line 83 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp4_ = granite_services_settings_get_schema ((GraniteServicesSettings*) _tmp3_);
#line 83 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp5_ = _tmp4_;
#line 83 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp6_ = self->priv->pomodoro_scale;
#line 83 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_settings_bind (_tmp5_, "pomodoro-duration", (GObject*) _tmp6_, "current-value", G_SETTINGS_BIND_DEFAULT);
#line 85 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp7_ = _ ("minute");
#line 85 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp8_ = _ ("minutes");
#line 85 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp9_ = tomato_widget_value_range_new ((gdouble) 1, (gdouble) 10, (gdouble) 1, _tmp7_, _tmp8_);
#line 85 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_object_ref_sink (_tmp9_);
#line 85 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_g_object_unref0 (self->priv->short_break_scale);
#line 85 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	self->priv->short_break_scale = _tmp9_;
#line 86 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp10_ = tomato_settings;
#line 86 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp11_ = granite_services_settings_get_schema ((GraniteServicesSettings*) _tmp10_);
#line 86 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp12_ = _tmp11_;
#line 86 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp13_ = self->priv->short_break_scale;
#line 86 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_settings_bind (_tmp12_, "short-break-duration", (GObject*) _tmp13_, "current-value", G_SETTINGS_BIND_DEFAULT);
#line 88 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp14_ = _ ("minute");
#line 88 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp15_ = _ ("minutes");
#line 88 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp16_ = tomato_widget_value_range_new ((gdouble) 10, (gdouble) 30, (gdouble) 1, _tmp14_, _tmp15_);
#line 88 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_object_ref_sink (_tmp16_);
#line 88 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_g_object_unref0 (self->priv->long_break_scale);
#line 88 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	self->priv->long_break_scale = _tmp16_;
#line 89 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp17_ = tomato_settings;
#line 89 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp18_ = granite_services_settings_get_schema ((GraniteServicesSettings*) _tmp17_);
#line 89 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp19_ = _tmp18_;
#line 89 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp20_ = self->priv->long_break_scale;
#line 89 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_settings_bind (_tmp19_, "long-break-duration", (GObject*) _tmp20_, "current-value", G_SETTINGS_BIND_DEFAULT);
#line 91 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp21_ = _ ("pomodoro");
#line 91 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp22_ = _ ("pomodoros");
#line 91 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp23_ = tomato_widget_value_range_new ((gdouble) 2, (gdouble) 8, (gdouble) 1, _tmp21_, _tmp22_);
#line 91 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_object_ref_sink (_tmp23_);
#line 91 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_g_object_unref0 (self->priv->long_break_delay_scale);
#line 91 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	self->priv->long_break_delay_scale = _tmp23_;
#line 92 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp24_ = tomato_settings;
#line 92 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp25_ = granite_services_settings_get_schema ((GraniteServicesSettings*) _tmp24_);
#line 92 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp26_ = _tmp25_;
#line 92 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp27_ = self->priv->long_break_delay_scale;
#line 92 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_settings_bind (_tmp26_, "long-break-delay", (GObject*) _tmp27_, "current-value", G_SETTINGS_BIND_DEFAULT);
#line 95 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp28_ = (GtkSwitch*) gtk_switch_new ();
#line 95 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_object_ref_sink (_tmp28_);
#line 95 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_g_object_unref0 (self->priv->reset_work_everyday);
#line 95 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	self->priv->reset_work_everyday = _tmp28_;
#line 96 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp29_ = tomato_preferences;
#line 96 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp30_ = granite_services_settings_get_schema ((GraniteServicesSettings*) _tmp29_);
#line 96 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp31_ = _tmp30_;
#line 96 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp32_ = self->priv->reset_work_everyday;
#line 96 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_settings_bind (_tmp31_, "reset-work-everyday", (GObject*) _tmp32_, "active", G_SETTINGS_BIND_DEFAULT);
#line 98 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp33_ = (GtkSwitch*) gtk_switch_new ();
#line 98 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_object_ref_sink (_tmp33_);
#line 98 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_g_object_unref0 (self->priv->pause_after_break);
#line 98 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	self->priv->pause_after_break = _tmp33_;
#line 99 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp34_ = tomato_preferences;
#line 99 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp35_ = granite_services_settings_get_schema ((GraniteServicesSettings*) _tmp34_);
#line 99 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp36_ = _tmp35_;
#line 99 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp37_ = self->priv->pause_after_break;
#line 99 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_settings_bind (_tmp36_, "pause-after-break", (GObject*) _tmp37_, "active", G_SETTINGS_BIND_DEFAULT);
#line 101 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp38_ = (GtkSwitch*) gtk_switch_new ();
#line 101 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_object_ref_sink (_tmp38_);
#line 101 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_g_object_unref0 (self->priv->auto_stop_enabled);
#line 101 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	self->priv->auto_stop_enabled = _tmp38_;
#line 102 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp39_ = tomato_preferences;
#line 102 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp40_ = granite_services_settings_get_schema ((GraniteServicesSettings*) _tmp39_);
#line 102 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp41_ = _tmp40_;
#line 102 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp42_ = self->priv->auto_stop_enabled;
#line 102 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_settings_bind (_tmp41_, "auto-stop", (GObject*) _tmp42_, "active", G_SETTINGS_BIND_DEFAULT);
#line 104 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp43_ = (GtkSwitch*) gtk_switch_new ();
#line 104 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_object_ref_sink (_tmp43_);
#line 104 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_g_object_unref0 (self->priv->pomodoro_sound_enabled);
#line 104 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	self->priv->pomodoro_sound_enabled = _tmp43_;
#line 105 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp44_ = tomato_preferences;
#line 105 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp45_ = granite_services_settings_get_schema ((GraniteServicesSettings*) _tmp44_);
#line 105 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp46_ = _tmp45_;
#line 105 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp47_ = self->priv->pomodoro_sound_enabled;
#line 105 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_settings_bind (_tmp46_, "pomodoro-sound-enabled", (GObject*) _tmp47_, "active", G_SETTINGS_BIND_DEFAULT);
#line 107 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp48_ = tomato_preferences;
#line 107 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp49_ = tomato_services_preferences_get_debug_mode (_tmp48_);
#line 107 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp50_ = _tmp49_;
#line 107 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	if (_tmp50_) {
#line 487 "PreferencesDialog.c"
		const gchar* _tmp51_ = NULL;
		const gchar* _tmp52_ = NULL;
		TomatoWidgetValueRange* _tmp53_ = NULL;
		TomatoServicesSettings* _tmp54_ = NULL;
		GSettings* _tmp55_ = NULL;
		GSettings* _tmp56_ = NULL;
		TomatoWidgetValueRange* _tmp57_ = NULL;
		const gchar* _tmp58_ = NULL;
		const gchar* _tmp59_ = NULL;
		TomatoWidgetValueRange* _tmp60_ = NULL;
		TomatoServicesSettings* _tmp61_ = NULL;
		GSettings* _tmp62_ = NULL;
		GSettings* _tmp63_ = NULL;
		TomatoWidgetValueRange* _tmp64_ = NULL;
		GtkSwitch* _tmp65_ = NULL;
		TomatoServicesPreferences* _tmp66_ = NULL;
		GSettings* _tmp67_ = NULL;
		GSettings* _tmp68_ = NULL;
		GtkSwitch* _tmp69_ = NULL;
#line 108 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp51_ = _ ("minute");
#line 108 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp52_ = _ ("minutes");
#line 108 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp53_ = tomato_widget_value_range_new ((gdouble) 1, (gdouble) 60, (gdouble) 1, _tmp51_, _tmp52_);
#line 108 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		g_object_ref_sink (_tmp53_);
#line 108 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_g_object_unref0 (self->priv->pomodoro_scale);
#line 108 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		self->priv->pomodoro_scale = _tmp53_;
#line 109 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp54_ = tomato_settings;
#line 109 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp55_ = granite_services_settings_get_schema ((GraniteServicesSettings*) _tmp54_);
#line 109 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp56_ = _tmp55_;
#line 109 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp57_ = self->priv->pomodoro_scale;
#line 109 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		g_settings_bind (_tmp56_, "pomodoro-duration", (GObject*) _tmp57_, "current-value", G_SETTINGS_BIND_DEFAULT);
#line 111 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp58_ = _ ("minute");
#line 111 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp59_ = _ ("minutes");
#line 111 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp60_ = tomato_widget_value_range_new ((gdouble) 2, (gdouble) 30, (gdouble) 1, _tmp58_, _tmp59_);
#line 111 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		g_object_ref_sink (_tmp60_);
#line 111 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_g_object_unref0 (self->priv->long_break_scale);
#line 111 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		self->priv->long_break_scale = _tmp60_;
#line 112 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp61_ = tomato_settings;
#line 112 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp62_ = granite_services_settings_get_schema ((GraniteServicesSettings*) _tmp61_);
#line 112 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp63_ = _tmp62_;
#line 112 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp64_ = self->priv->long_break_scale;
#line 112 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		g_settings_bind (_tmp63_, "long-break-duration", (GObject*) _tmp64_, "current-value", G_SETTINGS_BIND_DEFAULT);
#line 114 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp65_ = (GtkSwitch*) gtk_switch_new ();
#line 114 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		g_object_ref_sink (_tmp65_);
#line 114 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_g_object_unref0 (self->priv->debug_switch);
#line 114 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		self->priv->debug_switch = _tmp65_;
#line 115 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp66_ = tomato_preferences;
#line 115 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp67_ = granite_services_settings_get_schema ((GraniteServicesSettings*) _tmp66_);
#line 115 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp68_ = _tmp67_;
#line 115 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp69_ = self->priv->debug_switch;
#line 115 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		g_settings_bind (_tmp68_, "debug-mode", (GObject*) _tmp69_, "active", G_SETTINGS_BIND_DEFAULT);
#line 569 "PreferencesDialog.c"
	}
#line 119 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp70_ = _ ("Default Settings");
#line 119 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp71_ = (GtkButton*) gtk_button_new_with_label (_tmp70_);
#line 119 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_object_ref_sink (_tmp71_);
#line 119 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_g_object_unref0 (self->priv->reset_timings);
#line 119 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	self->priv->reset_timings = _tmp71_;
#line 120 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp72_ = _ ("Reset Work");
#line 120 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp73_ = (GtkButton*) gtk_button_new_with_label (_tmp72_);
#line 120 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_object_ref_sink (_tmp73_);
#line 120 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_g_object_unref0 (self->priv->reset_work);
#line 120 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	self->priv->reset_work = _tmp73_;
#line 591 "PreferencesDialog.c"
}


static void __lambda6_ (TomatoWindowPreferencesDialog* self) {
#line 138 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	gtk_widget_destroy ((GtkWidget*) self);
#line 598 "PreferencesDialog.c"
}


static void ___lambda6__gtk_button_clicked (GtkButton* _sender, gpointer self) {
#line 138 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	__lambda6_ ((TomatoWindowPreferencesDialog*) self);
#line 605 "PreferencesDialog.c"
}


static void tomato_window_preferences_dialog_create_ui (TomatoWindowPreferencesDialog* self) {
	GtkStack* _tmp0_ = NULL;
	GtkStack* _tmp1_ = NULL;
	GtkWidget* _tmp2_ = NULL;
	GtkWidget* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	GtkStack* _tmp5_ = NULL;
	GtkWidget* _tmp6_ = NULL;
	GtkWidget* _tmp7_ = NULL;
	const gchar* _tmp8_ = NULL;
	GtkButton* close_button = NULL;
	const gchar* _tmp9_ = NULL;
	GtkButton* _tmp10_ = NULL;
	GtkHButtonBox* button_box = NULL;
	GtkHButtonBox* _tmp11_ = NULL;
	GtkGrid* main_grid = NULL;
	GtkGrid* _tmp12_ = NULL;
	GtkStackSwitcher* _tmp13_ = NULL;
	GtkStack* _tmp14_ = NULL;
	GtkBox* _tmp15_ = NULL;
#line 123 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_return_if_fail (self != NULL);
#line 125 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp0_ = self->priv->stack;
#line 125 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	gtk_stack_set_transition_type (_tmp0_, GTK_STACK_TRANSITION_TYPE_SLIDE_LEFT_RIGHT);
#line 128 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp1_ = self->priv->stack;
#line 128 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp2_ = tomato_window_preferences_dialog_get_timing_box (self);
#line 128 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp3_ = _tmp2_;
#line 128 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp4_ = _ ("Timing");
#line 128 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	gtk_stack_add_titled (_tmp1_, _tmp3_, "timing", _tmp4_);
#line 128 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_g_object_unref0 (_tmp3_);
#line 132 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp5_ = self->priv->stack;
#line 132 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp6_ = tomato_window_preferences_dialog_get_misc_box (self);
#line 132 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp7_ = _tmp6_;
#line 132 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp8_ = _ ("Preferences");
#line 132 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	gtk_stack_add_titled (_tmp5_, _tmp7_, "misc", _tmp8_);
#line 132 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_g_object_unref0 (_tmp7_);
#line 137 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp9_ = _ ("Close");
#line 137 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp10_ = (GtkButton*) gtk_button_new_with_label (_tmp9_);
#line 137 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_object_ref_sink (_tmp10_);
#line 137 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	close_button = _tmp10_;
#line 138 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_signal_connect_object (close_button, "clicked", (GCallback) ___lambda6__gtk_button_clicked, self, 0);
#line 141 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp11_ = (GtkHButtonBox*) gtk_hbutton_box_new ();
#line 141 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_object_ref_sink (_tmp11_);
#line 141 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	button_box = _tmp11_;
#line 142 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	gtk_button_box_set_layout ((GtkButtonBox*) button_box, GTK_BUTTONBOX_END);
#line 143 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	gtk_box_pack_end ((GtkBox*) button_box, (GtkWidget*) close_button, TRUE, TRUE, (guint) 0);
#line 144 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	gtk_widget_set_margin_right ((GtkWidget*) button_box, 12);
#line 147 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp12_ = (GtkGrid*) gtk_grid_new ();
#line 147 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_object_ref_sink (_tmp12_);
#line 147 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	main_grid = _tmp12_;
#line 148 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp13_ = self->priv->stackswitcher;
#line 148 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	gtk_grid_attach (main_grid, (GtkWidget*) _tmp13_, 0, 0, 1, 1);
#line 149 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp14_ = self->priv->stack;
#line 149 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	gtk_grid_attach (main_grid, (GtkWidget*) _tmp14_, 0, 1, 1, 1);
#line 151 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	gtk_grid_attach (main_grid, (GtkWidget*) button_box, 0, 2, 1, 1);
#line 154 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp15_ = (GtkBox*) gtk_dialog_get_content_area ((GtkDialog*) self);
#line 154 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	gtk_container_add ((GtkContainer*) _tmp15_, (GtkWidget*) main_grid);
#line 123 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_g_object_unref0 (main_grid);
#line 123 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_g_object_unref0 (button_box);
#line 123 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_g_object_unref0 (close_button);
#line 707 "PreferencesDialog.c"
}


static GtkWidget* tomato_window_preferences_dialog_get_timing_box (TomatoWindowPreferencesDialog* self) {
	GtkWidget* result = NULL;
	GtkGrid* grid = NULL;
	GtkGrid* _tmp0_ = NULL;
	gint row = 0;
	GtkLabel* label = NULL;
	const gchar* _tmp1_ = NULL;
	GtkLabel* _tmp2_ = NULL;
	GtkLabel* _tmp3_ = NULL;
	TomatoWidgetValueRange* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
	GtkLabel* _tmp6_ = NULL;
	GtkLabel* _tmp7_ = NULL;
	TomatoWidgetValueRange* _tmp8_ = NULL;
	const gchar* _tmp9_ = NULL;
	GtkLabel* _tmp10_ = NULL;
	GtkLabel* _tmp11_ = NULL;
	TomatoWidgetValueRange* _tmp12_ = NULL;
	const gchar* _tmp13_ = NULL;
	GtkLabel* _tmp14_ = NULL;
	GtkLabel* _tmp15_ = NULL;
	TomatoWidgetValueRange* _tmp16_ = NULL;
	GtkGrid* reset_grid = NULL;
	GtkGrid* _tmp17_ = NULL;
	GtkButton* _tmp18_ = NULL;
	GtkButton* _tmp19_ = NULL;
	const gchar* _tmp20_ = NULL;
	GtkLabel* _tmp21_ = NULL;
	GtkLabel* _tmp22_ = NULL;
#line 157 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 159 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp0_ = tomato_window_preferences_dialog_make_grid (self);
#line 159 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	grid = _tmp0_;
#line 161 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	row = 0;
#line 167 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp1_ = _ ("Pomodoro duration:");
#line 167 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp2_ = (GtkLabel*) gtk_label_new (_tmp1_);
#line 167 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_object_ref_sink (_tmp2_);
#line 167 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	label = _tmp2_;
#line 168 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp3_ = label;
#line 168 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp4_ = self->priv->pomodoro_scale;
#line 168 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	tomato_window_preferences_dialog_add_option (self, grid, (GtkWidget*) _tmp3_, (GtkWidget*) _tmp4_, &row, 0);
#line 171 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp5_ = _ ("Short break duration:");
#line 171 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp6_ = (GtkLabel*) gtk_label_new (_tmp5_);
#line 171 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_object_ref_sink (_tmp6_);
#line 171 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_g_object_unref0 (label);
#line 171 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	label = _tmp6_;
#line 172 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp7_ = label;
#line 172 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp8_ = self->priv->short_break_scale;
#line 172 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	tomato_window_preferences_dialog_add_option (self, grid, (GtkWidget*) _tmp7_, (GtkWidget*) _tmp8_, &row, 0);
#line 175 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp9_ = _ ("Long break duration:");
#line 175 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp10_ = (GtkLabel*) gtk_label_new (_tmp9_);
#line 175 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_object_ref_sink (_tmp10_);
#line 175 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_g_object_unref0 (label);
#line 175 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	label = _tmp10_;
#line 176 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp11_ = label;
#line 176 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp12_ = self->priv->long_break_scale;
#line 176 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	tomato_window_preferences_dialog_add_option (self, grid, (GtkWidget*) _tmp11_, (GtkWidget*) _tmp12_, &row, 0);
#line 179 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp13_ = _ ("Long break delay:");
#line 179 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp14_ = (GtkLabel*) gtk_label_new (_tmp13_);
#line 179 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_object_ref_sink (_tmp14_);
#line 179 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_g_object_unref0 (label);
#line 179 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	label = _tmp14_;
#line 180 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp15_ = label;
#line 180 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp16_ = self->priv->long_break_delay_scale;
#line 180 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	tomato_window_preferences_dialog_add_option (self, grid, (GtkWidget*) _tmp15_, (GtkWidget*) _tmp16_, &row, 0);
#line 183 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp17_ = (GtkGrid*) gtk_grid_new ();
#line 183 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_object_ref_sink (_tmp17_);
#line 183 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	reset_grid = _tmp17_;
#line 184 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	gtk_grid_set_column_spacing (reset_grid, 5);
#line 185 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp18_ = self->priv->reset_timings;
#line 185 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	gtk_container_add ((GtkContainer*) reset_grid, (GtkWidget*) _tmp18_);
#line 186 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp19_ = self->priv->reset_work;
#line 186 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	gtk_container_add ((GtkContainer*) reset_grid, (GtkWidget*) _tmp19_);
#line 187 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp20_ = _ ("Reset:");
#line 187 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp21_ = (GtkLabel*) gtk_label_new (_tmp20_);
#line 187 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_object_ref_sink (_tmp21_);
#line 187 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_g_object_unref0 (label);
#line 187 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	label = _tmp21_;
#line 188 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp22_ = label;
#line 188 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	tomato_window_preferences_dialog_add_option (self, grid, (GtkWidget*) _tmp22_, (GtkWidget*) reset_grid, &row, 15);
#line 190 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	result = (GtkWidget*) grid;
#line 190 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_g_object_unref0 (reset_grid);
#line 190 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_g_object_unref0 (label);
#line 190 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	return result;
#line 848 "PreferencesDialog.c"
}


static GtkWidget* tomato_window_preferences_dialog_get_misc_box (TomatoWindowPreferencesDialog* self) {
	GtkWidget* result = NULL;
	GtkGrid* grid = NULL;
	GtkGrid* _tmp0_ = NULL;
	gint row = 0;
	GtkLabel* label = NULL;
	const gchar* _tmp1_ = NULL;
	GtkLabel* _tmp2_ = NULL;
	GtkGrid* _tmp3_ = NULL;
	GtkLabel* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
	GtkLabel* _tmp6_ = NULL;
	GtkGrid* _tmp7_ = NULL;
	GtkLabel* _tmp8_ = NULL;
	GtkSwitch* _tmp9_ = NULL;
	const gchar* _tmp10_ = NULL;
	GtkLabel* _tmp11_ = NULL;
	GtkGrid* _tmp12_ = NULL;
	GtkLabel* _tmp13_ = NULL;
	GtkSwitch* _tmp14_ = NULL;
	const gchar* _tmp15_ = NULL;
	GtkLabel* _tmp16_ = NULL;
	GtkGrid* _tmp17_ = NULL;
	GtkLabel* _tmp18_ = NULL;
	GtkSwitch* _tmp19_ = NULL;
	const gchar* _tmp20_ = NULL;
	GtkLabel* _tmp21_ = NULL;
	GtkGrid* _tmp22_ = NULL;
	GtkLabel* _tmp23_ = NULL;
	const gchar* _tmp24_ = NULL;
	GtkLabel* _tmp25_ = NULL;
	GtkGrid* _tmp26_ = NULL;
	GtkLabel* _tmp27_ = NULL;
	GtkSwitch* _tmp28_ = NULL;
	TomatoServicesPreferences* _tmp29_ = NULL;
	gboolean _tmp30_ = FALSE;
	gboolean _tmp31_ = FALSE;
#line 193 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 195 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp0_ = tomato_window_preferences_dialog_make_grid (self);
#line 195 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	grid = _tmp0_;
#line 197 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	row = 0;
#line 199 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp1_ = _ ("Behavior:");
#line 199 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp2_ = (GtkLabel*) gtk_label_new (_tmp1_);
#line 199 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_object_ref_sink (_tmp2_);
#line 199 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	label = _tmp2_;
#line 200 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp3_ = grid;
#line 200 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp4_ = label;
#line 200 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	tomato_window_preferences_dialog_add_section (self, _tmp3_, _tmp4_, &row);
#line 202 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp5_ = _ ("Reset work everyday:");
#line 202 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp6_ = (GtkLabel*) gtk_label_new (_tmp5_);
#line 202 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_object_ref_sink (_tmp6_);
#line 202 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_g_object_unref0 (label);
#line 202 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	label = _tmp6_;
#line 203 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp7_ = grid;
#line 203 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp8_ = label;
#line 203 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp9_ = self->priv->reset_work_everyday;
#line 203 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	tomato_window_preferences_dialog_add_option (self, _tmp7_, (GtkWidget*) _tmp8_, (GtkWidget*) _tmp9_, &row, 0);
#line 205 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp10_ = _ ("Start new pomodoro manually:");
#line 205 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp11_ = (GtkLabel*) gtk_label_new (_tmp10_);
#line 205 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_object_ref_sink (_tmp11_);
#line 205 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_g_object_unref0 (label);
#line 205 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	label = _tmp11_;
#line 206 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp12_ = grid;
#line 206 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp13_ = label;
#line 206 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp14_ = self->priv->pause_after_break;
#line 206 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	tomato_window_preferences_dialog_add_option (self, _tmp12_, (GtkWidget*) _tmp13_, (GtkWidget*) _tmp14_, &row, 0);
#line 208 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp15_ = _ ("Auto stop:");
#line 208 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp16_ = (GtkLabel*) gtk_label_new (_tmp15_);
#line 208 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_object_ref_sink (_tmp16_);
#line 208 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_g_object_unref0 (label);
#line 208 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	label = _tmp16_;
#line 209 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp17_ = grid;
#line 209 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp18_ = label;
#line 209 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp19_ = self->priv->auto_stop_enabled;
#line 209 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	tomato_window_preferences_dialog_add_option (self, _tmp17_, (GtkWidget*) _tmp18_, (GtkWidget*) _tmp19_, &row, 0);
#line 211 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp20_ = _ ("Sound:");
#line 211 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp21_ = (GtkLabel*) gtk_label_new (_tmp20_);
#line 211 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_object_ref_sink (_tmp21_);
#line 211 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_g_object_unref0 (label);
#line 211 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	label = _tmp21_;
#line 212 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp22_ = grid;
#line 212 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp23_ = label;
#line 212 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	tomato_window_preferences_dialog_add_section (self, _tmp22_, _tmp23_, &row);
#line 214 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp24_ = _ ("Pomodoro sound:");
#line 214 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp25_ = (GtkLabel*) gtk_label_new (_tmp24_);
#line 214 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_object_ref_sink (_tmp25_);
#line 214 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_g_object_unref0 (label);
#line 214 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	label = _tmp25_;
#line 215 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp26_ = grid;
#line 215 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp27_ = label;
#line 215 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp28_ = self->priv->pomodoro_sound_enabled;
#line 215 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	tomato_window_preferences_dialog_add_option (self, _tmp26_, (GtkWidget*) _tmp27_, (GtkWidget*) _tmp28_, &row, 0);
#line 217 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp29_ = tomato_preferences;
#line 217 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp30_ = tomato_services_preferences_get_debug_mode (_tmp29_);
#line 217 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp31_ = _tmp30_;
#line 217 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	if (_tmp31_) {
#line 1007 "PreferencesDialog.c"
		const gchar* _tmp32_ = NULL;
		GtkLabel* _tmp33_ = NULL;
		GtkGrid* _tmp34_ = NULL;
		GtkLabel* _tmp35_ = NULL;
		GtkLabel* _tmp36_ = NULL;
		GtkGrid* _tmp37_ = NULL;
		GtkLabel* _tmp38_ = NULL;
		GtkSwitch* _tmp39_ = NULL;
#line 218 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp32_ = _ ("Extras:");
#line 218 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp33_ = (GtkLabel*) gtk_label_new (_tmp32_);
#line 218 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		g_object_ref_sink (_tmp33_);
#line 218 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_g_object_unref0 (label);
#line 218 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		label = _tmp33_;
#line 219 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp34_ = grid;
#line 219 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp35_ = label;
#line 219 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		tomato_window_preferences_dialog_add_section (self, _tmp34_, _tmp35_, &row);
#line 221 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp36_ = (GtkLabel*) gtk_label_new ("Debug mode:");
#line 221 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		g_object_ref_sink (_tmp36_);
#line 221 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_g_object_unref0 (label);
#line 221 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		label = _tmp36_;
#line 222 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp37_ = grid;
#line 222 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp38_ = label;
#line 222 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp39_ = self->priv->debug_switch;
#line 222 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		tomato_window_preferences_dialog_add_option (self, _tmp37_, (GtkWidget*) _tmp38_, (GtkWidget*) _tmp39_, &row, 0);
#line 1048 "PreferencesDialog.c"
	}
#line 225 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	result = (GtkWidget*) grid;
#line 225 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_g_object_unref0 (label);
#line 225 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	return result;
#line 1056 "PreferencesDialog.c"
}


static void tomato_window_preferences_dialog_reset_scales (TomatoWindowPreferencesDialog* self) {
	TomatoWidgetValueRange* _tmp0_ = NULL;
	TomatoWidgetValueRange* _tmp1_ = NULL;
	TomatoWidgetValueRange* _tmp2_ = NULL;
	TomatoWidgetValueRange* _tmp3_ = NULL;
#line 228 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_return_if_fail (self != NULL);
#line 229 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp0_ = self->priv->pomodoro_scale;
#line 229 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	tomato_widget_value_range_set_current_value (_tmp0_, DEFAULT_POMODORO_DURATION);
#line 230 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp1_ = self->priv->short_break_scale;
#line 230 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	tomato_widget_value_range_set_current_value (_tmp1_, DEFAULT_SHORT_BREAK_DURATION);
#line 231 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp2_ = self->priv->long_break_scale;
#line 231 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	tomato_widget_value_range_set_current_value (_tmp2_, DEFAULT_LONG_BREAK_DURATION);
#line 232 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp3_ = self->priv->long_break_delay_scale;
#line 232 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	tomato_widget_value_range_set_current_value (_tmp3_, DEFAULT_LONG_BREAK_DELAY);
#line 1083 "PreferencesDialog.c"
}


void tomato_window_preferences_dialog_update_timing_sensitivity (TomatoWindowPreferencesDialog* self) {
	gboolean sensitive = FALSE;
	TomatoWidgetValueRange* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	GtkButton* _tmp12_ = NULL;
	gboolean _tmp13_ = FALSE;
#line 235 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_return_if_fail (self != NULL);
#line 236 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	sensitive = FALSE;
#line 237 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp0_ = self->priv->pomodoro_scale;
#line 237 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp1_ = tomato_widget_value_range_get_current_value (_tmp0_);
#line 237 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp2_ = _tmp1_;
#line 237 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	if (_tmp2_ != DEFAULT_POMODORO_DURATION) {
#line 238 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		sensitive = TRUE;
#line 1108 "PreferencesDialog.c"
	} else {
		TomatoWidgetValueRange* _tmp3_ = NULL;
		gint _tmp4_ = 0;
		gint _tmp5_ = 0;
#line 239 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp3_ = self->priv->short_break_scale;
#line 239 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp4_ = tomato_widget_value_range_get_current_value (_tmp3_);
#line 239 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp5_ = _tmp4_;
#line 239 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		if (_tmp5_ != DEFAULT_SHORT_BREAK_DURATION) {
#line 240 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
			sensitive = TRUE;
#line 1123 "PreferencesDialog.c"
		} else {
			TomatoWidgetValueRange* _tmp6_ = NULL;
			gint _tmp7_ = 0;
			gint _tmp8_ = 0;
#line 241 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
			_tmp6_ = self->priv->long_break_scale;
#line 241 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
			_tmp7_ = tomato_widget_value_range_get_current_value (_tmp6_);
#line 241 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
			_tmp8_ = _tmp7_;
#line 241 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
			if (_tmp8_ != DEFAULT_LONG_BREAK_DURATION) {
#line 242 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
				sensitive = TRUE;
#line 1138 "PreferencesDialog.c"
			} else {
				TomatoWidgetValueRange* _tmp9_ = NULL;
				gint _tmp10_ = 0;
				gint _tmp11_ = 0;
#line 243 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
				_tmp9_ = self->priv->long_break_delay_scale;
#line 243 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
				_tmp10_ = tomato_widget_value_range_get_current_value (_tmp9_);
#line 243 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
				_tmp11_ = _tmp10_;
#line 243 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
				if (_tmp11_ != DEFAULT_LONG_BREAK_DELAY) {
#line 244 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
					sensitive = TRUE;
#line 1153 "PreferencesDialog.c"
				}
			}
		}
	}
#line 246 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp12_ = self->priv->reset_timings;
#line 246 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp13_ = sensitive;
#line 246 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	gtk_widget_set_sensitive ((GtkWidget*) _tmp12_, _tmp13_);
#line 1164 "PreferencesDialog.c"
}


void tomato_window_preferences_dialog_update_work_sensitivity (TomatoWindowPreferencesDialog* self) {
	gboolean sensitive = FALSE;
	TomatoServicesSavedState* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	GtkButton* _tmp9_ = NULL;
	gboolean _tmp10_ = FALSE;
#line 250 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_return_if_fail (self != NULL);
#line 251 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	sensitive = FALSE;
#line 252 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp0_ = tomato_saved;
#line 252 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp1_ = tomato_services_saved_state_get_pomodoro_count (_tmp0_);
#line 252 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp2_ = _tmp1_;
#line 252 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	if (_tmp2_ != 0) {
#line 253 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		sensitive = TRUE;
#line 1189 "PreferencesDialog.c"
	} else {
		TomatoServicesSavedState* _tmp3_ = NULL;
		gint _tmp4_ = 0;
		gint _tmp5_ = 0;
#line 254 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp3_ = tomato_saved;
#line 254 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp4_ = tomato_services_saved_state_get_total_time (_tmp3_);
#line 254 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp5_ = _tmp4_;
#line 254 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		if (_tmp5_ != 0) {
#line 255 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
			sensitive = TRUE;
#line 1204 "PreferencesDialog.c"
		} else {
			TomatoServicesSavedState* _tmp6_ = NULL;
			TomatoStatus _tmp7_ = 0;
			TomatoStatus _tmp8_ = 0;
#line 256 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
			_tmp6_ = tomato_saved;
#line 256 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
			_tmp7_ = tomato_services_saved_state_get_status (_tmp6_);
#line 256 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
			_tmp8_ = _tmp7_;
#line 256 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
			if (_tmp8_ != TOMATO_STATUS_START) {
#line 257 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
				sensitive = TRUE;
#line 1219 "PreferencesDialog.c"
			}
		}
	}
#line 259 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp9_ = self->priv->reset_work;
#line 259 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp10_ = sensitive;
#line 259 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	gtk_widget_set_sensitive ((GtkWidget*) _tmp9_, _tmp10_);
#line 1229 "PreferencesDialog.c"
}


static void tomato_window_preferences_dialog_add_section (TomatoWindowPreferencesDialog* self, GtkGrid* grid, GtkLabel* name, gint* row) {
	GtkLabel* _tmp0_ = NULL;
	GtkLabel* _tmp1_ = NULL;
	GtkLabel* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	GtkLabel* _tmp6_ = NULL;
	GtkGrid* _tmp7_ = NULL;
	GtkLabel* _tmp8_ = NULL;
	gint _tmp9_ = 0;
	gint _tmp10_ = 0;
#line 262 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_return_if_fail (self != NULL);
#line 262 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_return_if_fail (grid != NULL);
#line 262 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_return_if_fail (name != NULL);
#line 263 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp0_ = name;
#line 263 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	gtk_label_set_use_markup (_tmp0_, TRUE);
#line 264 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp1_ = name;
#line 264 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp2_ = name;
#line 264 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp3_ = gtk_label_get_text (_tmp2_);
#line 264 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp4_ = g_strdup_printf ("<b>%s</b>", _tmp3_);
#line 264 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp5_ = _tmp4_;
#line 264 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	gtk_label_set_markup (_tmp1_, _tmp5_);
#line 264 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_g_free0 (_tmp5_);
#line 265 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp6_ = name;
#line 265 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	gtk_widget_set_halign ((GtkWidget*) _tmp6_, GTK_ALIGN_START);
#line 266 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp7_ = grid;
#line 266 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp8_ = name;
#line 266 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp9_ = *row;
#line 266 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	gtk_grid_attach (_tmp7_, (GtkWidget*) _tmp8_, 0, _tmp9_, 1, 1);
#line 268 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp10_ = *row;
#line 268 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	*row = _tmp10_ + 1;
#line 1285 "PreferencesDialog.c"
}


static void tomato_window_preferences_dialog_add_option (TomatoWindowPreferencesDialog* self, GtkGrid* grid, GtkWidget* label, GtkWidget* switcher, gint* row, gint margin_top) {
	GtkWidget* _tmp0_ = NULL;
	GtkWidget* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	GtkWidget* _tmp3_ = NULL;
	GtkWidget* _tmp6_ = NULL;
	GtkWidget* _tmp7_ = NULL;
	gint _tmp8_ = 0;
	GtkWidget* _tmp9_ = NULL;
	gint _tmp10_ = 0;
	GtkWidget* _tmp11_ = NULL;
	GtkWidget* _tmp12_ = NULL;
	gboolean _tmp13_ = FALSE;
	GtkWidget* _tmp14_ = NULL;
	gboolean _tmp17_ = FALSE;
	GtkWidget* _tmp18_ = NULL;
	GtkGrid* _tmp21_ = NULL;
	GtkWidget* _tmp22_ = NULL;
	gint _tmp23_ = 0;
	GtkGrid* _tmp24_ = NULL;
	GtkWidget* _tmp25_ = NULL;
	GtkWidget* _tmp26_ = NULL;
	gint _tmp27_ = 0;
#line 271 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_return_if_fail (self != NULL);
#line 271 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_return_if_fail (grid != NULL);
#line 271 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_return_if_fail (label != NULL);
#line 271 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_return_if_fail (switcher != NULL);
#line 272 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp0_ = label;
#line 272 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	gtk_widget_set_hexpand (_tmp0_, TRUE);
#line 273 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp1_ = label;
#line 273 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	gtk_widget_set_halign (_tmp1_, GTK_ALIGN_END);
#line 274 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp3_ = switcher;
#line 274 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp3_, gtk_scale_get_type ())) {
#line 274 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp2_ = TRUE;
#line 1334 "PreferencesDialog.c"
	} else {
		GtkWidget* _tmp4_ = NULL;
#line 274 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp4_ = switcher;
#line 274 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp2_ = G_TYPE_CHECK_INSTANCE_TYPE (_tmp4_, TOMATO_WIDGET_TYPE_VALUE_RANGE);
#line 1341 "PreferencesDialog.c"
	}
#line 274 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	if (_tmp2_) {
#line 1345 "PreferencesDialog.c"
		GtkWidget* _tmp5_ = NULL;
#line 274 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp5_ = label;
#line 274 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		gtk_widget_set_valign (_tmp5_, GTK_ALIGN_END);
#line 1351 "PreferencesDialog.c"
	}
#line 275 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp6_ = label;
#line 275 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	gtk_widget_set_margin_left (_tmp6_, 20);
#line 276 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp7_ = label;
#line 276 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp8_ = margin_top;
#line 276 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	gtk_widget_set_margin_top (_tmp7_, _tmp8_);
#line 277 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp9_ = switcher;
#line 277 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp10_ = margin_top;
#line 277 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	gtk_widget_set_margin_top (_tmp9_, _tmp10_);
#line 278 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp11_ = switcher;
#line 278 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	gtk_widget_set_hexpand (_tmp11_, TRUE);
#line 279 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp12_ = switcher;
#line 279 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	gtk_widget_set_halign (_tmp12_, GTK_ALIGN_FILL);
#line 280 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp14_ = switcher;
#line 280 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp14_, gtk_scale_get_type ())) {
#line 280 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp13_ = TRUE;
#line 1383 "PreferencesDialog.c"
	} else {
		GtkWidget* _tmp15_ = NULL;
#line 280 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp15_ = switcher;
#line 280 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp13_ = G_TYPE_CHECK_INSTANCE_TYPE (_tmp15_, TOMATO_WIDGET_TYPE_VALUE_RANGE);
#line 1390 "PreferencesDialog.c"
	}
#line 280 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	if (_tmp13_) {
#line 1394 "PreferencesDialog.c"
		GtkWidget* _tmp16_ = NULL;
#line 280 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp16_ = switcher;
#line 280 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		gtk_widget_set_valign (_tmp16_, GTK_ALIGN_CENTER);
#line 1400 "PreferencesDialog.c"
	}
#line 283 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp18_ = switcher;
#line 283 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp18_, gtk_switch_get_type ())) {
#line 283 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp17_ = TRUE;
#line 1408 "PreferencesDialog.c"
	} else {
		GtkWidget* _tmp19_ = NULL;
#line 283 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp19_ = switcher;
#line 283 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp17_ = G_TYPE_CHECK_INSTANCE_TYPE (_tmp19_, gtk_entry_get_type ());
#line 1415 "PreferencesDialog.c"
	}
#line 283 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	if (_tmp17_) {
#line 1419 "PreferencesDialog.c"
		GtkWidget* _tmp20_ = NULL;
#line 284 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		_tmp20_ = switcher;
#line 284 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
		gtk_widget_set_halign (_tmp20_, GTK_ALIGN_START);
#line 1425 "PreferencesDialog.c"
	}
#line 287 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp21_ = grid;
#line 287 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp22_ = label;
#line 287 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp23_ = *row;
#line 287 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	gtk_grid_attach (_tmp21_, _tmp22_, 0, _tmp23_, 1, 1);
#line 288 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp24_ = grid;
#line 288 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp25_ = switcher;
#line 288 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp26_ = label;
#line 288 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	gtk_grid_attach_next_to (_tmp24_, _tmp25_, _tmp26_, GTK_POS_RIGHT, 3, 1);
#line 290 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp27_ = *row;
#line 290 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	*row = _tmp27_ + 1;
#line 1447 "PreferencesDialog.c"
}


static GtkGrid* tomato_window_preferences_dialog_make_grid (TomatoWindowPreferencesDialog* self) {
	GtkGrid* result = NULL;
	GtkGrid* grid = NULL;
	GtkGrid* _tmp0_ = NULL;
#line 293 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 294 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp0_ = (GtkGrid*) gtk_grid_new ();
#line 294 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_object_ref_sink (_tmp0_);
#line 294 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	grid = _tmp0_;
#line 295 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	gtk_grid_set_row_spacing (grid, 5);
#line 296 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	gtk_grid_set_column_spacing (grid, 5);
#line 297 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	gtk_widget_set_margin_left ((GtkWidget*) grid, 12);
#line 298 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	gtk_widget_set_margin_right ((GtkWidget*) grid, 12);
#line 299 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	gtk_widget_set_margin_top ((GtkWidget*) grid, 12);
#line 300 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	gtk_widget_set_margin_bottom ((GtkWidget*) grid, 12);
#line 301 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	result = grid;
#line 301 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	return result;
#line 1479 "PreferencesDialog.c"
}


static void __lambda7_ (TomatoWindowPreferencesDialog* self) {
#line 306 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_signal_emit_by_name (self, "pomodoro-changed");
#line 1486 "PreferencesDialog.c"
}


static void ___lambda7__tomato_widget_value_range_changed (TomatoWidgetValueRange* _sender, gpointer self) {
#line 305 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	__lambda7_ ((TomatoWindowPreferencesDialog*) self);
#line 1493 "PreferencesDialog.c"
}


static void __lambda8_ (TomatoWindowPreferencesDialog* self) {
#line 310 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_signal_emit_by_name (self, "short-break-changed");
#line 1500 "PreferencesDialog.c"
}


static void ___lambda8__tomato_widget_value_range_changed (TomatoWidgetValueRange* _sender, gpointer self) {
#line 309 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	__lambda8_ ((TomatoWindowPreferencesDialog*) self);
#line 1507 "PreferencesDialog.c"
}


static void __lambda9_ (TomatoWindowPreferencesDialog* self) {
#line 314 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_signal_emit_by_name (self, "long-break-changed");
#line 1514 "PreferencesDialog.c"
}


static void ___lambda9__tomato_widget_value_range_changed (TomatoWidgetValueRange* _sender, gpointer self) {
#line 313 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	__lambda9_ ((TomatoWindowPreferencesDialog*) self);
#line 1521 "PreferencesDialog.c"
}


static void __lambda10_ (TomatoWindowPreferencesDialog* self) {
#line 318 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_signal_emit_by_name (self, "long-break-delay-changed");
#line 1528 "PreferencesDialog.c"
}


static void ___lambda10__tomato_widget_value_range_changed (TomatoWidgetValueRange* _sender, gpointer self) {
#line 317 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	__lambda10_ ((TomatoWindowPreferencesDialog*) self);
#line 1535 "PreferencesDialog.c"
}


static void _tomato_window_preferences_dialog_reset_scales_gtk_button_clicked (GtkButton* _sender, gpointer self) {
#line 321 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	tomato_window_preferences_dialog_reset_scales ((TomatoWindowPreferencesDialog*) self);
#line 1542 "PreferencesDialog.c"
}


static void __lambda11_ (TomatoWindowPreferencesDialog* self) {
#line 324 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_signal_emit_by_name (self, "reset-work-clicked");
#line 1549 "PreferencesDialog.c"
}


static void ___lambda11__gtk_button_clicked (GtkButton* _sender, gpointer self) {
#line 323 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	__lambda11_ ((TomatoWindowPreferencesDialog*) self);
#line 1556 "PreferencesDialog.c"
}


static void tomato_window_preferences_dialog_connect_signals (TomatoWindowPreferencesDialog* self) {
	TomatoWidgetValueRange* _tmp0_ = NULL;
	TomatoWidgetValueRange* _tmp1_ = NULL;
	TomatoWidgetValueRange* _tmp2_ = NULL;
	TomatoWidgetValueRange* _tmp3_ = NULL;
	GtkButton* _tmp4_ = NULL;
	GtkButton* _tmp5_ = NULL;
#line 304 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_return_if_fail (self != NULL);
#line 305 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp0_ = self->priv->pomodoro_scale;
#line 305 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_signal_connect_object (_tmp0_, "changed", (GCallback) ___lambda7__tomato_widget_value_range_changed, self, 0);
#line 309 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp1_ = self->priv->short_break_scale;
#line 309 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_signal_connect_object (_tmp1_, "changed", (GCallback) ___lambda8__tomato_widget_value_range_changed, self, 0);
#line 313 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp2_ = self->priv->long_break_scale;
#line 313 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_signal_connect_object (_tmp2_, "changed", (GCallback) ___lambda9__tomato_widget_value_range_changed, self, 0);
#line 317 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp3_ = self->priv->long_break_delay_scale;
#line 317 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_signal_connect_object (_tmp3_, "changed", (GCallback) ___lambda10__tomato_widget_value_range_changed, self, 0);
#line 321 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp4_ = self->priv->reset_timings;
#line 321 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_signal_connect_object (_tmp4_, "clicked", (GCallback) _tomato_window_preferences_dialog_reset_scales_gtk_button_clicked, self, 0);
#line 323 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_tmp5_ = self->priv->reset_work;
#line 323 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_signal_connect_object (_tmp5_, "clicked", (GCallback) ___lambda11__gtk_button_clicked, self, 0);
#line 1593 "PreferencesDialog.c"
}


static void tomato_window_preferences_dialog_class_init (TomatoWindowPreferencesDialogClass * klass) {
#line 21 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	tomato_window_preferences_dialog_parent_class = g_type_class_peek_parent (klass);
#line 21 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_type_class_add_private (klass, sizeof (TomatoWindowPreferencesDialogPrivate));
#line 21 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	G_OBJECT_CLASS (klass)->finalize = tomato_window_preferences_dialog_finalize;
#line 21 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_signal_new ("reset_work_clicked", TOMATO_WINDOW_TYPE_PREFERENCES_DIALOG, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
#line 21 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_signal_new ("pomodoro_changed", TOMATO_WINDOW_TYPE_PREFERENCES_DIALOG, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
#line 21 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_signal_new ("short_break_changed", TOMATO_WINDOW_TYPE_PREFERENCES_DIALOG, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
#line 21 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_signal_new ("long_break_changed", TOMATO_WINDOW_TYPE_PREFERENCES_DIALOG, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
#line 21 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	g_signal_new ("long_break_delay_changed", TOMATO_WINDOW_TYPE_PREFERENCES_DIALOG, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
#line 1614 "PreferencesDialog.c"
}


static void tomato_window_preferences_dialog_instance_init (TomatoWindowPreferencesDialog * self) {
#line 21 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	self->priv = TOMATO_WINDOW_PREFERENCES_DIALOG_GET_PRIVATE (self);
#line 1621 "PreferencesDialog.c"
}


static void tomato_window_preferences_dialog_finalize (GObject* obj) {
	TomatoWindowPreferencesDialog * self;
#line 21 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TOMATO_WINDOW_TYPE_PREFERENCES_DIALOG, TomatoWindowPreferencesDialog);
#line 24 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_g_object_unref0 (self->priv->stack);
#line 25 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_g_object_unref0 (self->priv->stackswitcher);
#line 28 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_g_object_unref0 (self->priv->pomodoro_scale);
#line 29 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_g_object_unref0 (self->priv->short_break_scale);
#line 30 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_g_object_unref0 (self->priv->long_break_scale);
#line 31 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_g_object_unref0 (self->priv->long_break_delay_scale);
#line 34 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_g_object_unref0 (self->priv->reset_work_everyday);
#line 35 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_g_object_unref0 (self->priv->pause_after_break);
#line 36 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_g_object_unref0 (self->priv->auto_stop_enabled);
#line 37 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_g_object_unref0 (self->priv->pomodoro_sound_enabled);
#line 38 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_g_object_unref0 (self->priv->debug_switch);
#line 41 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_g_object_unref0 (self->priv->reset_timings);
#line 42 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	_g_object_unref0 (self->priv->reset_work);
#line 21 "/home/lamm/Projetos/tomato/src/Windows/PreferencesDialog.vala"
	G_OBJECT_CLASS (tomato_window_preferences_dialog_parent_class)->finalize (obj);
#line 1657 "PreferencesDialog.c"
}


GType tomato_window_preferences_dialog_get_type (void) {
	static volatile gsize tomato_window_preferences_dialog_type_id__volatile = 0;
	if (g_once_init_enter (&tomato_window_preferences_dialog_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (TomatoWindowPreferencesDialogClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) tomato_window_preferences_dialog_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TomatoWindowPreferencesDialog), 0, (GInstanceInitFunc) tomato_window_preferences_dialog_instance_init, NULL };
		GType tomato_window_preferences_dialog_type_id;
		tomato_window_preferences_dialog_type_id = g_type_register_static (gtk_dialog_get_type (), "TomatoWindowPreferencesDialog", &g_define_type_info, 0);
		g_once_init_leave (&tomato_window_preferences_dialog_type_id__volatile, tomato_window_preferences_dialog_type_id);
	}
	return tomato_window_preferences_dialog_type_id__volatile;
}



