/* Screen.c generated by valac 0.34.7, the Vala compiler
 * generated from Screen.vala, do not modify */

/* Copyright 2015 LuizAugustoMorais
*
* This file is part of Tomato.
*
* Tomato is free software: you can redistribute it
* and/or modify it under the terms of the GNU General Public License as
* published by the Free Software Foundation, either version 3 of the
* License, or (at your option) any later version.
*
* Tomato is distributed in the hope that it will be
* useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
* Public License for more details.
*
* You should have received a copy of the GNU General Public License along
* with Tomato. If not, see http://www.gnu.org/licenses/.
*/

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>


#define TOMATO_WIDGET_TYPE_SCREEN (tomato_widget_screen_get_type ())
#define TOMATO_WIDGET_SCREEN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TOMATO_WIDGET_TYPE_SCREEN, TomatoWidgetScreen))
#define TOMATO_WIDGET_SCREEN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TOMATO_WIDGET_TYPE_SCREEN, TomatoWidgetScreenClass))
#define TOMATO_WIDGET_IS_SCREEN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TOMATO_WIDGET_TYPE_SCREEN))
#define TOMATO_WIDGET_IS_SCREEN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TOMATO_WIDGET_TYPE_SCREEN))
#define TOMATO_WIDGET_SCREEN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TOMATO_WIDGET_TYPE_SCREEN, TomatoWidgetScreenClass))

typedef struct _TomatoWidgetScreen TomatoWidgetScreen;
typedef struct _TomatoWidgetScreenClass TomatoWidgetScreenClass;
typedef struct _TomatoWidgetScreenPrivate TomatoWidgetScreenPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _TomatoWidgetScreen {
	GtkFrame parent_instance;
	TomatoWidgetScreenPrivate * priv;
};

struct _TomatoWidgetScreenClass {
	GtkFrameClass parent_class;
};

struct _TomatoWidgetScreenPrivate {
	GtkBox* elements;
	GtkBox* progress_box;
	GtkButtonBox* control_box;
};


static gpointer tomato_widget_screen_parent_class = NULL;

GType tomato_widget_screen_get_type (void) G_GNUC_CONST;
#define TOMATO_WIDGET_SCREEN_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TOMATO_WIDGET_TYPE_SCREEN, TomatoWidgetScreenPrivate))
enum  {
	TOMATO_WIDGET_SCREEN_DUMMY_PROPERTY
};
TomatoWidgetScreen* tomato_widget_screen_new (const gchar* name);
TomatoWidgetScreen* tomato_widget_screen_construct (GType object_type, const gchar* name);
static void tomato_widget_screen_setup_control_box (TomatoWidgetScreen* self);
static void tomato_widget_screen_setup_elements (TomatoWidgetScreen* self);
gchar* tomato_widget_screen_get_name (TomatoWidgetScreen* self);
void tomato_widget_screen_add_progress (TomatoWidgetScreen* self, GtkLabel* countdown, GtkLabel* total_time);
static void tomato_widget_screen_clear_progress (TomatoWidgetScreen* self, GtkLabel* progress);
void tomato_widget_screen_add_control (TomatoWidgetScreen* self, GtkWidget* control);
void tomato_widget_screen_add_controls (TomatoWidgetScreen* self, GtkWidget** controls, int controls_length1);
static void tomato_widget_screen_finalize (GObject* obj);


TomatoWidgetScreen* tomato_widget_screen_construct (GType object_type, const gchar* name) {
	TomatoWidgetScreen * self = NULL;
	const gchar* _tmp0_ = NULL;
	GtkBox* _tmp1_ = NULL;
	GtkBox* _tmp2_ = NULL;
	GtkButtonBox* _tmp3_ = NULL;
	GtkBox* _tmp4_ = NULL;
#line 27 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	g_return_val_if_fail (name != NULL, NULL);
#line 27 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	self = (TomatoWidgetScreen*) g_object_new (object_type, NULL);
#line 28 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	_tmp0_ = name;
#line 28 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	gtk_widget_set_name ((GtkWidget*) self, _tmp0_);
#line 30 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	_tmp1_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 0);
#line 30 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	g_object_ref_sink (_tmp1_);
#line 30 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	_g_object_unref0 (self->priv->elements);
#line 30 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	self->priv->elements = _tmp1_;
#line 31 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	_tmp2_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 0);
#line 31 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	g_object_ref_sink (_tmp2_);
#line 31 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	_g_object_unref0 (self->priv->progress_box);
#line 31 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	self->priv->progress_box = _tmp2_;
#line 32 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	_tmp3_ = (GtkButtonBox*) gtk_button_box_new (GTK_ORIENTATION_HORIZONTAL);
#line 32 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	g_object_ref_sink (_tmp3_);
#line 32 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	_g_object_unref0 (self->priv->control_box);
#line 32 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	self->priv->control_box = _tmp3_;
#line 34 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	tomato_widget_screen_setup_control_box (self);
#line 35 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	tomato_widget_screen_setup_elements (self);
#line 37 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	_tmp4_ = self->priv->elements;
#line 37 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp4_);
#line 38 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	gtk_frame_set_shadow_type ((GtkFrame*) self, GTK_SHADOW_NONE);
#line 27 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	return self;
#line 128 "Screen.c"
}


TomatoWidgetScreen* tomato_widget_screen_new (const gchar* name) {
#line 27 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	return tomato_widget_screen_construct (TOMATO_WIDGET_TYPE_SCREEN, name);
#line 135 "Screen.c"
}


gchar* tomato_widget_screen_get_name (TomatoWidgetScreen* self) {
	gchar* result = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
#line 41 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 42 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	_tmp0_ = gtk_widget_get_name ((GtkWidget*) self);
#line 42 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	_tmp1_ = _tmp0_;
#line 42 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	_tmp2_ = g_strdup (_tmp1_);
#line 42 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	result = _tmp2_;
#line 42 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	return result;
#line 156 "Screen.c"
}


void tomato_widget_screen_add_progress (TomatoWidgetScreen* self, GtkLabel* countdown, GtkLabel* total_time) {
	GtkLabel* _tmp0_ = NULL;
	GtkBox* _tmp1_ = NULL;
	GtkLabel* _tmp2_ = NULL;
	GtkLabel* _tmp3_ = NULL;
	GtkLabel* _tmp4_ = NULL;
	GtkBox* _tmp5_ = NULL;
	GtkLabel* _tmp6_ = NULL;
	GtkLabel* _tmp7_ = NULL;
#line 45 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	g_return_if_fail (self != NULL);
#line 45 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	g_return_if_fail (countdown != NULL);
#line 45 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	g_return_if_fail (total_time != NULL);
#line 46 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	_tmp0_ = countdown;
#line 46 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	tomato_widget_screen_clear_progress (self, _tmp0_);
#line 47 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	_tmp1_ = self->priv->progress_box;
#line 47 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	_tmp2_ = countdown;
#line 47 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	gtk_box_pack_start (_tmp1_, (GtkWidget*) _tmp2_, TRUE, TRUE, (guint) 0);
#line 48 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	_tmp3_ = countdown;
#line 48 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	gtk_widget_show ((GtkWidget*) _tmp3_);
#line 50 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	_tmp4_ = total_time;
#line 50 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	tomato_widget_screen_clear_progress (self, _tmp4_);
#line 51 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	_tmp5_ = self->priv->progress_box;
#line 51 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	_tmp6_ = total_time;
#line 51 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	gtk_box_pack_start (_tmp5_, (GtkWidget*) _tmp6_, TRUE, TRUE, (guint) 0);
#line 52 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	_tmp7_ = total_time;
#line 52 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	gtk_widget_show ((GtkWidget*) _tmp7_);
#line 203 "Screen.c"
}


void tomato_widget_screen_add_control (TomatoWidgetScreen* self, GtkWidget* control) {
	GtkButtonBox* _tmp0_ = NULL;
	GtkWidget* _tmp1_ = NULL;
#line 55 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	g_return_if_fail (self != NULL);
#line 55 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	g_return_if_fail (control != NULL);
#line 56 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	_tmp0_ = self->priv->control_box;
#line 56 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	_tmp1_ = control;
#line 56 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	gtk_container_add ((GtkContainer*) _tmp0_, _tmp1_);
#line 220 "Screen.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 60 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	return self ? g_object_ref (self) : NULL;
#line 227 "Screen.c"
}


void tomato_widget_screen_add_controls (TomatoWidgetScreen* self, GtkWidget** controls, int controls_length1) {
	GtkWidget** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
#line 59 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	g_return_if_fail (self != NULL);
#line 60 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	_tmp0_ = controls;
#line 60 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	_tmp0__length1 = controls_length1;
#line 240 "Screen.c"
	{
		GtkWidget** control_collection = NULL;
		gint control_collection_length1 = 0;
		gint _control_collection_size_ = 0;
		gint control_it = 0;
#line 60 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
		control_collection = _tmp0_;
#line 60 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
		control_collection_length1 = _tmp0__length1;
#line 60 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
		for (control_it = 0; control_it < _tmp0__length1; control_it = control_it + 1) {
#line 252 "Screen.c"
			GtkWidget* _tmp1_ = NULL;
			GtkWidget* control = NULL;
#line 60 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
			_tmp1_ = _g_object_ref0 (control_collection[control_it]);
#line 60 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
			control = _tmp1_;
#line 259 "Screen.c"
			{
				GtkButtonBox* _tmp2_ = NULL;
				GtkWidget* _tmp3_ = NULL;
#line 61 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
				_tmp2_ = self->priv->control_box;
#line 61 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
				_tmp3_ = control;
#line 61 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
				gtk_container_add ((GtkContainer*) _tmp2_, _tmp3_);
#line 60 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
				_g_object_unref0 (control);
#line 271 "Screen.c"
			}
		}
	}
}


static void tomato_widget_screen_clear_progress (TomatoWidgetScreen* self, GtkLabel* progress) {
	GtkContainer* progress_parent = NULL;
	GtkLabel* _tmp0_ = NULL;
	GtkContainer* _tmp1_ = NULL;
	GtkContainer* _tmp2_ = NULL;
	GtkContainer* _tmp3_ = NULL;
#line 65 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	g_return_if_fail (self != NULL);
#line 65 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	g_return_if_fail (progress != NULL);
#line 66 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	_tmp0_ = progress;
#line 66 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	_tmp1_ = (GtkContainer*) gtk_widget_get_parent ((GtkWidget*) _tmp0_);
#line 66 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	_tmp2_ = _g_object_ref0 (_tmp1_);
#line 66 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	progress_parent = _tmp2_;
#line 67 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	_tmp3_ = progress_parent;
#line 67 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	if (_tmp3_ != NULL) {
#line 300 "Screen.c"
		GtkContainer* _tmp4_ = NULL;
		GtkLabel* _tmp5_ = NULL;
#line 68 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
		_tmp4_ = progress_parent;
#line 68 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
		_tmp5_ = progress;
#line 68 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
		gtk_container_remove (_tmp4_, (GtkWidget*) _tmp5_);
#line 309 "Screen.c"
	}
#line 65 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	_g_object_unref0 (progress_parent);
#line 313 "Screen.c"
}


static void tomato_widget_screen_setup_elements (TomatoWidgetScreen* self) {
	GtkBox* _tmp0_ = NULL;
	GtkBox* _tmp1_ = NULL;
	GtkBox* _tmp2_ = NULL;
	GtkBox* _tmp3_ = NULL;
	GtkButtonBox* _tmp4_ = NULL;
#line 72 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	g_return_if_fail (self != NULL);
#line 73 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	_tmp0_ = self->priv->elements;
#line 73 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	gtk_container_set_border_width ((GtkContainer*) _tmp0_, (guint) 12);
#line 74 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	_tmp1_ = self->priv->elements;
#line 74 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	_tmp2_ = self->priv->progress_box;
#line 74 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	gtk_box_pack_start (_tmp1_, (GtkWidget*) _tmp2_, TRUE, TRUE, (guint) 0);
#line 75 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	_tmp3_ = self->priv->elements;
#line 75 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	_tmp4_ = self->priv->control_box;
#line 75 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	gtk_box_pack_start (_tmp3_, (GtkWidget*) _tmp4_, TRUE, TRUE, (guint) 0);
#line 341 "Screen.c"
}


static void tomato_widget_screen_setup_control_box (TomatoWidgetScreen* self) {
	GtkButtonBox* _tmp0_ = NULL;
	GtkButtonBox* _tmp1_ = NULL;
	GtkButtonBox* _tmp2_ = NULL;
#line 78 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	g_return_if_fail (self != NULL);
#line 79 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	_tmp0_ = self->priv->control_box;
#line 79 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	gtk_button_box_set_layout (_tmp0_, GTK_BUTTONBOX_CENTER);
#line 80 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	_tmp1_ = self->priv->control_box;
#line 80 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	gtk_box_set_spacing ((GtkBox*) _tmp1_, 6);
#line 81 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	_tmp2_ = self->priv->control_box;
#line 81 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	gtk_container_set_border_width ((GtkContainer*) _tmp2_, (guint) 12);
#line 363 "Screen.c"
}


static void tomato_widget_screen_class_init (TomatoWidgetScreenClass * klass) {
#line 21 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	tomato_widget_screen_parent_class = g_type_class_peek_parent (klass);
#line 21 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	g_type_class_add_private (klass, sizeof (TomatoWidgetScreenPrivate));
#line 21 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	G_OBJECT_CLASS (klass)->finalize = tomato_widget_screen_finalize;
#line 374 "Screen.c"
}


static void tomato_widget_screen_instance_init (TomatoWidgetScreen * self) {
#line 21 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	self->priv = TOMATO_WIDGET_SCREEN_GET_PRIVATE (self);
#line 381 "Screen.c"
}


static void tomato_widget_screen_finalize (GObject* obj) {
	TomatoWidgetScreen * self;
#line 21 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TOMATO_WIDGET_TYPE_SCREEN, TomatoWidgetScreen);
#line 23 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	_g_object_unref0 (self->priv->elements);
#line 24 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	_g_object_unref0 (self->priv->progress_box);
#line 25 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	_g_object_unref0 (self->priv->control_box);
#line 21 "/home/lamm/Projetos/tomato/src/Widgets/Screen.vala"
	G_OBJECT_CLASS (tomato_widget_screen_parent_class)->finalize (obj);
#line 397 "Screen.c"
}


GType tomato_widget_screen_get_type (void) {
	static volatile gsize tomato_widget_screen_type_id__volatile = 0;
	if (g_once_init_enter (&tomato_widget_screen_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (TomatoWidgetScreenClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) tomato_widget_screen_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TomatoWidgetScreen), 0, (GInstanceInitFunc) tomato_widget_screen_instance_init, NULL };
		GType tomato_widget_screen_type_id;
		tomato_widget_screen_type_id = g_type_register_static (gtk_frame_get_type (), "TomatoWidgetScreen", &g_define_type_info, 0);
		g_once_init_leave (&tomato_widget_screen_type_id__volatile, tomato_widget_screen_type_id);
	}
	return tomato_widget_screen_type_id__volatile;
}



