/* Slide.c generated by valac 0.34.7, the Vala compiler
 * generated from Slide.vala, do not modify */

/* Copyright 2015 LuizAugustoMorais
*
* This file is part of Tomato.
*
* Tomato is free software: you can redistribute it
* and/or modify it under the terms of the GNU General Public License as
* published by the Free Software Foundation, either version 3 of the
* License, or (at your option) any later version.
*
* Tomato is distributed in the hope that it will be
* useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
* Public License for more details.
*
* You should have received a copy of the GNU General Public License along
* with Tomato. If not, see http://www.gnu.org/licenses/.
*/

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>


#define TOMATO_WIDGET_TYPE_SLIDE (tomato_widget_slide_get_type ())
#define TOMATO_WIDGET_SLIDE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TOMATO_WIDGET_TYPE_SLIDE, TomatoWidgetSlide))
#define TOMATO_WIDGET_SLIDE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TOMATO_WIDGET_TYPE_SLIDE, TomatoWidgetSlideClass))
#define TOMATO_WIDGET_IS_SLIDE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TOMATO_WIDGET_TYPE_SLIDE))
#define TOMATO_WIDGET_IS_SLIDE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TOMATO_WIDGET_TYPE_SLIDE))
#define TOMATO_WIDGET_SLIDE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TOMATO_WIDGET_TYPE_SLIDE, TomatoWidgetSlideClass))

typedef struct _TomatoWidgetSlide TomatoWidgetSlide;
typedef struct _TomatoWidgetSlideClass TomatoWidgetSlideClass;
typedef struct _TomatoWidgetSlidePrivate TomatoWidgetSlidePrivate;

#define TOMATO_WIDGET_TYPE_SCREEN (tomato_widget_screen_get_type ())
#define TOMATO_WIDGET_SCREEN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TOMATO_WIDGET_TYPE_SCREEN, TomatoWidgetScreen))
#define TOMATO_WIDGET_SCREEN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TOMATO_WIDGET_TYPE_SCREEN, TomatoWidgetScreenClass))
#define TOMATO_WIDGET_IS_SCREEN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TOMATO_WIDGET_TYPE_SCREEN))
#define TOMATO_WIDGET_IS_SCREEN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TOMATO_WIDGET_TYPE_SCREEN))
#define TOMATO_WIDGET_SCREEN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TOMATO_WIDGET_TYPE_SCREEN, TomatoWidgetScreenClass))

typedef struct _TomatoWidgetScreen TomatoWidgetScreen;
typedef struct _TomatoWidgetScreenClass TomatoWidgetScreenClass;
#define __g_list_free__g_object_unref0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__g_object_unref0_ (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _TomatoWidgetSlide {
	GtkStack parent_instance;
	TomatoWidgetSlidePrivate * priv;
};

struct _TomatoWidgetSlideClass {
	GtkStackClass parent_class;
};

struct _TomatoWidgetSlidePrivate {
	GList* screens;
};


static gpointer tomato_widget_slide_parent_class = NULL;

GType tomato_widget_slide_get_type (void) G_GNUC_CONST;
GType tomato_widget_screen_get_type (void) G_GNUC_CONST;
#define TOMATO_WIDGET_SLIDE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TOMATO_WIDGET_TYPE_SLIDE, TomatoWidgetSlidePrivate))
enum  {
	TOMATO_WIDGET_SLIDE_DUMMY_PROPERTY
};
static void _g_object_unref0_ (gpointer var);
static void _g_list_free__g_object_unref0_ (GList* self);
TomatoWidgetSlide* tomato_widget_slide_new (void);
TomatoWidgetSlide* tomato_widget_slide_construct (GType object_type);
void tomato_widget_slide_add_screen (TomatoWidgetSlide* self, TomatoWidgetScreen* screen);
gchar* tomato_widget_screen_get_name (TomatoWidgetScreen* self);
void tomato_widget_slide_set_visible_screen (TomatoWidgetSlide* self, const gchar* name, GtkStackTransitionType transition);
TomatoWidgetScreen* tomato_widget_slide_get_visible_screen (TomatoWidgetSlide* self);
TomatoWidgetScreen* tomato_widget_slide_find_screen (TomatoWidgetSlide* self, const gchar* name);
static void tomato_widget_slide_finalize (GObject* obj);


static void _g_object_unref0_ (gpointer var) {
#line 23 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
	(var == NULL) ? NULL : (var = (g_object_unref (var), NULL));
#line 90 "Slide.c"
}


static void _g_list_free__g_object_unref0_ (GList* self) {
#line 23 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
	g_list_foreach (self, (GFunc) _g_object_unref0_, NULL);
#line 23 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
	g_list_free (self);
#line 99 "Slide.c"
}


TomatoWidgetSlide* tomato_widget_slide_construct (GType object_type) {
	TomatoWidgetSlide * self = NULL;
#line 25 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
	self = (TomatoWidgetSlide*) g_object_new (object_type, NULL);
#line 26 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
	__g_list_free__g_object_unref0_0 (self->priv->screens);
#line 26 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
	self->priv->screens = NULL;
#line 27 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
	gtk_stack_set_transition_duration ((GtkStack*) self, (guint) 500);
#line 25 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
	return self;
#line 115 "Slide.c"
}


TomatoWidgetSlide* tomato_widget_slide_new (void) {
#line 25 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
	return tomato_widget_slide_construct (TOMATO_WIDGET_TYPE_SLIDE);
#line 122 "Slide.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 32 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
	return self ? g_object_ref (self) : NULL;
#line 129 "Slide.c"
}


void tomato_widget_slide_add_screen (TomatoWidgetSlide* self, TomatoWidgetScreen* screen) {
	TomatoWidgetScreen* _tmp0_ = NULL;
	TomatoWidgetScreen* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	TomatoWidgetScreen* _tmp4_ = NULL;
	TomatoWidgetScreen* _tmp5_ = NULL;
#line 30 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
	g_return_if_fail (self != NULL);
#line 30 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
	g_return_if_fail (screen != NULL);
#line 31 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
	_tmp0_ = screen;
#line 31 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
	_tmp1_ = screen;
#line 31 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
	_tmp2_ = tomato_widget_screen_get_name (_tmp1_);
#line 31 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
	_tmp3_ = _tmp2_;
#line 31 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
	gtk_stack_add_named ((GtkStack*) self, (GtkWidget*) _tmp0_, _tmp3_);
#line 31 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
	_g_free0 (_tmp3_);
#line 32 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
	_tmp4_ = screen;
#line 32 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
	_tmp5_ = _g_object_ref0 (_tmp4_);
#line 32 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
	self->priv->screens = g_list_append (self->priv->screens, _tmp5_);
#line 162 "Slide.c"
}


void tomato_widget_slide_set_visible_screen (TomatoWidgetSlide* self, const gchar* name, GtkStackTransitionType transition) {
	const gchar* _tmp0_ = NULL;
	GtkStackTransitionType _tmp1_ = 0;
#line 35 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
	g_return_if_fail (self != NULL);
#line 35 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
	g_return_if_fail (name != NULL);
#line 36 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
	_tmp0_ = name;
#line 36 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
	_tmp1_ = transition;
#line 36 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
	gtk_stack_set_visible_child_full ((GtkStack*) self, _tmp0_, _tmp1_);
#line 179 "Slide.c"
}


TomatoWidgetScreen* tomato_widget_slide_get_visible_screen (TomatoWidgetSlide* self) {
	TomatoWidgetScreen* result = NULL;
	const gchar* _tmp0_ = NULL;
	TomatoWidgetScreen* _tmp1_ = NULL;
#line 39 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 40 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
	_tmp0_ = gtk_stack_get_visible_child_name ((GtkStack*) self);
#line 40 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
	_tmp1_ = tomato_widget_slide_find_screen (self, _tmp0_);
#line 40 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
	result = _tmp1_;
#line 40 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
	return result;
#line 197 "Slide.c"
}


TomatoWidgetScreen* tomato_widget_slide_find_screen (TomatoWidgetSlide* self, const gchar* name) {
	TomatoWidgetScreen* result = NULL;
#line 43 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 43 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
	g_return_val_if_fail (name != NULL, NULL);
#line 207 "Slide.c"
	{
		guint i = 0U;
#line 44 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
		i = (guint) 0;
#line 212 "Slide.c"
		{
			gboolean _tmp0_ = FALSE;
#line 44 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
			_tmp0_ = TRUE;
#line 44 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
			while (TRUE) {
#line 219 "Slide.c"
				guint _tmp2_ = 0U;
				GList* _tmp3_ = NULL;
				guint _tmp4_ = 0U;
				GList* _tmp5_ = NULL;
				guint _tmp6_ = 0U;
				gconstpointer _tmp7_ = NULL;
				gchar* _tmp8_ = NULL;
				gchar* _tmp9_ = NULL;
				const gchar* _tmp10_ = NULL;
				gboolean _tmp11_ = FALSE;
#line 44 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
				if (!_tmp0_) {
#line 232 "Slide.c"
					guint _tmp1_ = 0U;
#line 44 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
					_tmp1_ = i;
#line 44 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
					i = _tmp1_ + 1;
#line 238 "Slide.c"
				}
#line 44 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
				_tmp0_ = FALSE;
#line 44 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
				_tmp2_ = i;
#line 44 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
				_tmp3_ = self->priv->screens;
#line 44 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
				_tmp4_ = g_list_length (_tmp3_);
#line 44 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
				if (!(_tmp2_ < _tmp4_)) {
#line 44 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
					break;
#line 252 "Slide.c"
				}
#line 45 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
				_tmp5_ = self->priv->screens;
#line 45 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
				_tmp6_ = i;
#line 45 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
				_tmp7_ = g_list_nth_data (_tmp5_, _tmp6_);
#line 45 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
				_tmp8_ = tomato_widget_screen_get_name ((TomatoWidgetScreen*) _tmp7_);
#line 45 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
				_tmp9_ = _tmp8_;
#line 45 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
				_tmp10_ = name;
#line 45 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
				_tmp11_ = g_strcmp0 (_tmp9_, _tmp10_) == 0;
#line 45 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
				_g_free0 (_tmp9_);
#line 45 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
				if (_tmp11_) {
#line 272 "Slide.c"
					GList* _tmp12_ = NULL;
					guint _tmp13_ = 0U;
					gconstpointer _tmp14_ = NULL;
					TomatoWidgetScreen* _tmp15_ = NULL;
#line 46 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
					_tmp12_ = self->priv->screens;
#line 46 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
					_tmp13_ = i;
#line 46 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
					_tmp14_ = g_list_nth_data (_tmp12_, _tmp13_);
#line 46 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
					_tmp15_ = _g_object_ref0 ((TomatoWidgetScreen*) _tmp14_);
#line 46 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
					result = _tmp15_;
#line 46 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
					return result;
#line 289 "Slide.c"
				}
			}
		}
	}
#line 47 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
	result = NULL;
#line 47 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
	return result;
#line 298 "Slide.c"
}


static void tomato_widget_slide_class_init (TomatoWidgetSlideClass * klass) {
#line 21 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
	tomato_widget_slide_parent_class = g_type_class_peek_parent (klass);
#line 21 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
	g_type_class_add_private (klass, sizeof (TomatoWidgetSlidePrivate));
#line 21 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
	G_OBJECT_CLASS (klass)->finalize = tomato_widget_slide_finalize;
#line 309 "Slide.c"
}


static void tomato_widget_slide_instance_init (TomatoWidgetSlide * self) {
#line 21 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
	self->priv = TOMATO_WIDGET_SLIDE_GET_PRIVATE (self);
#line 316 "Slide.c"
}


static void tomato_widget_slide_finalize (GObject* obj) {
	TomatoWidgetSlide * self;
#line 21 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TOMATO_WIDGET_TYPE_SLIDE, TomatoWidgetSlide);
#line 23 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
	__g_list_free__g_object_unref0_0 (self->priv->screens);
#line 21 "/home/lamm/Projetos/tomato/src/Widgets/Slide.vala"
	G_OBJECT_CLASS (tomato_widget_slide_parent_class)->finalize (obj);
#line 328 "Slide.c"
}


GType tomato_widget_slide_get_type (void) {
	static volatile gsize tomato_widget_slide_type_id__volatile = 0;
	if (g_once_init_enter (&tomato_widget_slide_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (TomatoWidgetSlideClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) tomato_widget_slide_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TomatoWidgetSlide), 0, (GInstanceInitFunc) tomato_widget_slide_instance_init, NULL };
		GType tomato_widget_slide_type_id;
		tomato_widget_slide_type_id = g_type_register_static (gtk_stack_get_type (), "TomatoWidgetSlide", &g_define_type_info, 0);
		g_once_init_leave (&tomato_widget_slide_type_id__volatile, tomato_widget_slide_type_id);
	}
	return tomato_widget_slide_type_id__volatile;
}



