/* Countdown.c generated by valac 0.34.7, the Vala compiler
 * generated from Countdown.vala, do not modify */

/* Copyright 2015 LuizAugustoMorais
*
* This file is part of Tomato.
*
* Tomato is free software: you can redistribute it
* and/or modify it under the terms of the GNU General Public License as
* published by the Free Software Foundation, either version 3 of the
* License, or (at your option) any later version.
*
* Tomato is distributed in the hope that it will be
* useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
* Public License for more details.
*
* You should have received a copy of the GNU General Public License along
* with Tomato. If not, see http://www.gnu.org/licenses/.
*/

#include <glib.h>
#include <glib-object.h>
#include <granite.h>
#include <stdlib.h>
#include <string.h>
#include <gobject/gvaluecollector.h>


#define TOMATO_UTIL_TYPE_COUNTDOWN (tomato_util_countdown_get_type ())
#define TOMATO_UTIL_COUNTDOWN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TOMATO_UTIL_TYPE_COUNTDOWN, TomatoUtilCountdown))
#define TOMATO_UTIL_COUNTDOWN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TOMATO_UTIL_TYPE_COUNTDOWN, TomatoUtilCountdownClass))
#define TOMATO_UTIL_IS_COUNTDOWN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TOMATO_UTIL_TYPE_COUNTDOWN))
#define TOMATO_UTIL_IS_COUNTDOWN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TOMATO_UTIL_TYPE_COUNTDOWN))
#define TOMATO_UTIL_COUNTDOWN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TOMATO_UTIL_TYPE_COUNTDOWN, TomatoUtilCountdownClass))

typedef struct _TomatoUtilCountdown TomatoUtilCountdown;
typedef struct _TomatoUtilCountdownClass TomatoUtilCountdownClass;
typedef struct _TomatoUtilCountdownPrivate TomatoUtilCountdownPrivate;

#define TOMATO_SERVICES_TYPE_SETTINGS (tomato_services_settings_get_type ())
#define TOMATO_SERVICES_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TOMATO_SERVICES_TYPE_SETTINGS, TomatoServicesSettings))
#define TOMATO_SERVICES_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TOMATO_SERVICES_TYPE_SETTINGS, TomatoServicesSettingsClass))
#define TOMATO_SERVICES_IS_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TOMATO_SERVICES_TYPE_SETTINGS))
#define TOMATO_SERVICES_IS_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TOMATO_SERVICES_TYPE_SETTINGS))
#define TOMATO_SERVICES_SETTINGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TOMATO_SERVICES_TYPE_SETTINGS, TomatoServicesSettingsClass))

typedef struct _TomatoServicesSettings TomatoServicesSettings;
typedef struct _TomatoServicesSettingsClass TomatoServicesSettingsClass;

#define TOMATO_UTIL_COUNTDOWN_TYPE_TIME (tomato_util_countdown_time_get_type ())
typedef struct _TomatoUtilCountdownTime TomatoUtilCountdownTime;
typedef struct _TomatoUtilParamSpecCountdown TomatoUtilParamSpecCountdown;

struct _TomatoUtilCountdown {
	GTypeInstance parent_instance;
	volatile int ref_count;
	TomatoUtilCountdownPrivate * priv;
};

struct _TomatoUtilCountdownClass {
	GTypeClass parent_class;
	void (*finalize) (TomatoUtilCountdown *self);
};

struct _TomatoUtilCountdownPrivate {
	gint current_time;
};

struct _TomatoUtilCountdownTime {
	gint hours;
	gint minutes;
	gint seconds;
};

struct _TomatoUtilParamSpecCountdown {
	GParamSpec parent_instance;
};


static gpointer tomato_util_countdown_parent_class = NULL;
extern TomatoServicesSettings* tomato_settings;

gpointer tomato_util_countdown_ref (gpointer instance);
void tomato_util_countdown_unref (gpointer instance);
GParamSpec* tomato_util_param_spec_countdown (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void tomato_util_value_set_countdown (GValue* value, gpointer v_object);
void tomato_util_value_take_countdown (GValue* value, gpointer v_object);
gpointer tomato_util_value_get_countdown (const GValue* value);
GType tomato_util_countdown_get_type (void) G_GNUC_CONST;
#define TOMATO_UTIL_COUNTDOWN_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TOMATO_UTIL_TYPE_COUNTDOWN, TomatoUtilCountdownPrivate))
enum  {
	TOMATO_UTIL_COUNTDOWN_DUMMY_PROPERTY
};
TomatoUtilCountdown* tomato_util_countdown_new (void);
TomatoUtilCountdown* tomato_util_countdown_construct (GType object_type);
void tomato_util_countdown_set_current_time (TomatoUtilCountdown* self, gint time);
GType tomato_services_settings_get_type (void) G_GNUC_CONST;
gint tomato_services_settings_get_pomodoro_duration (TomatoServicesSettings* self);
TomatoUtilCountdown* tomato_util_countdown_new_with_time (gint time);
TomatoUtilCountdown* tomato_util_countdown_construct_with_time (GType object_type, gint time);
gint tomato_util_countdown_tick (TomatoUtilCountdown* self);
gint tomato_util_countdown_get_current_time (TomatoUtilCountdown* self);
gchar* tomato_util_countdown_get_current_ftime (TomatoUtilCountdown* self, gboolean without_hours);
static GType tomato_util_countdown_time_get_type (void) G_GNUC_CONST G_GNUC_UNUSED;
static TomatoUtilCountdownTime* tomato_util_countdown_time_dup (const TomatoUtilCountdownTime* self);
static void tomato_util_countdown_time_free (TomatoUtilCountdownTime* self);
static void tomato_util_countdown_parse_time (TomatoUtilCountdown* self, gint time, TomatoUtilCountdownTime* result);
gboolean tomato_util_countdown_is_over (TomatoUtilCountdown* self);
static void tomato_util_countdown_finalize (TomatoUtilCountdown* obj);


TomatoUtilCountdown* tomato_util_countdown_construct (GType object_type) {
	TomatoUtilCountdown* self = NULL;
	TomatoServicesSettings* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
#line 31 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	self = (TomatoUtilCountdown*) g_type_create_instance (object_type);
#line 32 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	_tmp0_ = tomato_settings;
#line 32 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	_tmp1_ = tomato_services_settings_get_pomodoro_duration (_tmp0_);
#line 32 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	_tmp2_ = _tmp1_;
#line 32 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	tomato_util_countdown_set_current_time (self, _tmp2_ * 60);
#line 31 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	return self;
#line 131 "Countdown.c"
}


TomatoUtilCountdown* tomato_util_countdown_new (void) {
#line 31 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	return tomato_util_countdown_construct (TOMATO_UTIL_TYPE_COUNTDOWN);
#line 138 "Countdown.c"
}


TomatoUtilCountdown* tomato_util_countdown_construct_with_time (GType object_type, gint time) {
	TomatoUtilCountdown* self = NULL;
	gint _tmp0_ = 0;
#line 35 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	self = (TomatoUtilCountdown*) g_type_create_instance (object_type);
#line 36 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	_tmp0_ = time;
#line 36 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	tomato_util_countdown_set_current_time (self, _tmp0_);
#line 35 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	return self;
#line 153 "Countdown.c"
}


TomatoUtilCountdown* tomato_util_countdown_new_with_time (gint time) {
#line 35 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	return tomato_util_countdown_construct_with_time (TOMATO_UTIL_TYPE_COUNTDOWN, time);
#line 160 "Countdown.c"
}


gint tomato_util_countdown_tick (TomatoUtilCountdown* self) {
	gint result = 0;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
#line 39 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 40 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	_tmp0_ = self->priv->current_time;
#line 40 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	tomato_util_countdown_set_current_time (self, _tmp0_ - 1);
#line 41 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	_tmp1_ = self->priv->current_time;
#line 41 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	result = _tmp1_;
#line 41 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	return result;
#line 180 "Countdown.c"
}


gint tomato_util_countdown_get_current_time (TomatoUtilCountdown* self) {
	gint result = 0;
	gint _tmp0_ = 0;
#line 44 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 45 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	_tmp0_ = self->priv->current_time;
#line 45 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	result = _tmp0_;
#line 45 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	return result;
#line 195 "Countdown.c"
}


void tomato_util_countdown_set_current_time (TomatoUtilCountdown* self, gint time) {
	gint _tmp0_ = 0;
#line 48 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	g_return_if_fail (self != NULL);
#line 49 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	_tmp0_ = time;
#line 49 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	if (_tmp0_ >= 0) {
#line 207 "Countdown.c"
		gint _tmp1_ = 0;
#line 50 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
		_tmp1_ = time;
#line 50 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
		self->priv->current_time = _tmp1_;
#line 213 "Countdown.c"
	}
}


gchar* tomato_util_countdown_get_current_ftime (TomatoUtilCountdown* self, gboolean without_hours) {
	gchar* result = NULL;
	TomatoUtilCountdownTime t = {0};
	gint _tmp0_ = 0;
	TomatoUtilCountdownTime _tmp1_ = {0};
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
	TomatoUtilCountdownTime _tmp11_ = {0};
	gint _tmp12_ = 0;
	TomatoUtilCountdownTime _tmp13_ = {0};
	gint _tmp14_ = 0;
	TomatoUtilCountdownTime _tmp15_ = {0};
	gint _tmp16_ = 0;
	gchar* _tmp17_ = NULL;
#line 53 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 54 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	_tmp0_ = self->priv->current_time;
#line 54 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	tomato_util_countdown_parse_time (self, _tmp0_, &_tmp1_);
#line 54 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	t = _tmp1_;
#line 55 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	_tmp3_ = without_hours;
#line 55 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	if (_tmp3_) {
#line 244 "Countdown.c"
		TomatoUtilCountdownTime _tmp4_ = {0};
		gint _tmp5_ = 0;
#line 55 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
		_tmp4_ = t;
#line 55 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
		_tmp5_ = _tmp4_.hours;
#line 55 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
		_tmp2_ = _tmp5_ == 0;
#line 253 "Countdown.c"
	} else {
#line 55 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
		_tmp2_ = FALSE;
#line 257 "Countdown.c"
	}
#line 55 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	if (_tmp2_) {
#line 261 "Countdown.c"
		TomatoUtilCountdownTime _tmp6_ = {0};
		gint _tmp7_ = 0;
		TomatoUtilCountdownTime _tmp8_ = {0};
		gint _tmp9_ = 0;
		gchar* _tmp10_ = NULL;
#line 56 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
		_tmp6_ = t;
#line 56 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
		_tmp7_ = _tmp6_.minutes;
#line 56 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
		_tmp8_ = t;
#line 56 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
		_tmp9_ = _tmp8_.seconds;
#line 56 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
		_tmp10_ = g_strdup_printf ("%02d:%02d", _tmp7_, _tmp9_);
#line 56 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
		result = _tmp10_;
#line 56 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
		return result;
#line 281 "Countdown.c"
	}
#line 57 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	_tmp11_ = t;
#line 57 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	_tmp12_ = _tmp11_.hours;
#line 57 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	_tmp13_ = t;
#line 57 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	_tmp14_ = _tmp13_.minutes;
#line 57 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	_tmp15_ = t;
#line 57 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	_tmp16_ = _tmp15_.seconds;
#line 57 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	_tmp17_ = g_strdup_printf ("%02d:%02d:%02d", _tmp12_, _tmp14_, _tmp16_);
#line 57 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	result = _tmp17_;
#line 57 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	return result;
#line 301 "Countdown.c"
}


gboolean tomato_util_countdown_is_over (TomatoUtilCountdown* self) {
	gboolean result = FALSE;
	gint _tmp0_ = 0;
#line 60 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 61 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	_tmp0_ = self->priv->current_time;
#line 61 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	result = _tmp0_ == 0;
#line 61 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	return result;
#line 316 "Countdown.c"
}


static void tomato_util_countdown_parse_time (TomatoUtilCountdown* self, gint time, TomatoUtilCountdownTime* result) {
	TomatoUtilCountdownTime t = {0};
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
#line 64 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	g_return_if_fail (self != NULL);
#line 65 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	memset (&t, 0, sizeof (TomatoUtilCountdownTime));
#line 66 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	_tmp0_ = time;
#line 66 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	t.hours = _tmp0_ / 3600;
#line 67 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	_tmp1_ = time;
#line 67 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	time = _tmp1_ % 3600;
#line 68 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	_tmp2_ = time;
#line 68 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	t.minutes = _tmp2_ / 60;
#line 69 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	_tmp3_ = time;
#line 69 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	t.seconds = _tmp3_ % 60;
#line 70 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	*result = t;
#line 70 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	return;
#line 350 "Countdown.c"
}


static TomatoUtilCountdownTime* tomato_util_countdown_time_dup (const TomatoUtilCountdownTime* self) {
	TomatoUtilCountdownTime* dup;
#line 23 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	dup = g_new0 (TomatoUtilCountdownTime, 1);
#line 23 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	memcpy (dup, self, sizeof (TomatoUtilCountdownTime));
#line 23 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	return dup;
#line 362 "Countdown.c"
}


static void tomato_util_countdown_time_free (TomatoUtilCountdownTime* self) {
#line 23 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	g_free (self);
#line 369 "Countdown.c"
}


static GType tomato_util_countdown_time_get_type (void) {
	static volatile gsize tomato_util_countdown_time_type_id__volatile = 0;
	if (g_once_init_enter (&tomato_util_countdown_time_type_id__volatile)) {
		GType tomato_util_countdown_time_type_id;
		tomato_util_countdown_time_type_id = g_boxed_type_register_static ("TomatoUtilCountdownTime", (GBoxedCopyFunc) tomato_util_countdown_time_dup, (GBoxedFreeFunc) tomato_util_countdown_time_free);
		g_once_init_leave (&tomato_util_countdown_time_type_id__volatile, tomato_util_countdown_time_type_id);
	}
	return tomato_util_countdown_time_type_id__volatile;
}


static void tomato_util_value_countdown_init (GValue* value) {
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	value->data[0].v_pointer = NULL;
#line 387 "Countdown.c"
}


static void tomato_util_value_countdown_free_value (GValue* value) {
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	if (value->data[0].v_pointer) {
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
		tomato_util_countdown_unref (value->data[0].v_pointer);
#line 396 "Countdown.c"
	}
}


static void tomato_util_value_countdown_copy_value (const GValue* src_value, GValue* dest_value) {
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	if (src_value->data[0].v_pointer) {
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
		dest_value->data[0].v_pointer = tomato_util_countdown_ref (src_value->data[0].v_pointer);
#line 406 "Countdown.c"
	} else {
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
		dest_value->data[0].v_pointer = NULL;
#line 410 "Countdown.c"
	}
}


static gpointer tomato_util_value_countdown_peek_pointer (const GValue* value) {
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	return value->data[0].v_pointer;
#line 418 "Countdown.c"
}


static gchar* tomato_util_value_countdown_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	if (collect_values[0].v_pointer) {
#line 425 "Countdown.c"
		TomatoUtilCountdown* object;
		object = collect_values[0].v_pointer;
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
		if (object->parent_instance.g_class == NULL) {
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 432 "Countdown.c"
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 436 "Countdown.c"
		}
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
		value->data[0].v_pointer = tomato_util_countdown_ref (object);
#line 440 "Countdown.c"
	} else {
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
		value->data[0].v_pointer = NULL;
#line 444 "Countdown.c"
	}
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	return NULL;
#line 448 "Countdown.c"
}


static gchar* tomato_util_value_countdown_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	TomatoUtilCountdown** object_p;
	object_p = collect_values[0].v_pointer;
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	if (!object_p) {
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
#line 459 "Countdown.c"
	}
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	if (!value->data[0].v_pointer) {
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
		*object_p = NULL;
#line 465 "Countdown.c"
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
		*object_p = value->data[0].v_pointer;
#line 469 "Countdown.c"
	} else {
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
		*object_p = tomato_util_countdown_ref (value->data[0].v_pointer);
#line 473 "Countdown.c"
	}
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	return NULL;
#line 477 "Countdown.c"
}


GParamSpec* tomato_util_param_spec_countdown (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	TomatoUtilParamSpecCountdown* spec;
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	g_return_val_if_fail (g_type_is_a (object_type, TOMATO_UTIL_TYPE_COUNTDOWN), NULL);
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	G_PARAM_SPEC (spec)->value_type = object_type;
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	return G_PARAM_SPEC (spec);
#line 491 "Countdown.c"
}


gpointer tomato_util_value_get_countdown (const GValue* value) {
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TOMATO_UTIL_TYPE_COUNTDOWN), NULL);
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	return value->data[0].v_pointer;
#line 500 "Countdown.c"
}


void tomato_util_value_set_countdown (GValue* value, gpointer v_object) {
	TomatoUtilCountdown* old;
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TOMATO_UTIL_TYPE_COUNTDOWN));
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	old = value->data[0].v_pointer;
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	if (v_object) {
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TOMATO_UTIL_TYPE_COUNTDOWN));
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
		value->data[0].v_pointer = v_object;
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
		tomato_util_countdown_ref (value->data[0].v_pointer);
#line 520 "Countdown.c"
	} else {
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
		value->data[0].v_pointer = NULL;
#line 524 "Countdown.c"
	}
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	if (old) {
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
		tomato_util_countdown_unref (old);
#line 530 "Countdown.c"
	}
}


void tomato_util_value_take_countdown (GValue* value, gpointer v_object) {
	TomatoUtilCountdown* old;
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TOMATO_UTIL_TYPE_COUNTDOWN));
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	old = value->data[0].v_pointer;
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	if (v_object) {
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TOMATO_UTIL_TYPE_COUNTDOWN));
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
		value->data[0].v_pointer = v_object;
#line 549 "Countdown.c"
	} else {
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
		value->data[0].v_pointer = NULL;
#line 553 "Countdown.c"
	}
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	if (old) {
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
		tomato_util_countdown_unref (old);
#line 559 "Countdown.c"
	}
}


static void tomato_util_countdown_class_init (TomatoUtilCountdownClass * klass) {
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	tomato_util_countdown_parent_class = g_type_class_peek_parent (klass);
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	((TomatoUtilCountdownClass *) klass)->finalize = tomato_util_countdown_finalize;
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	g_type_class_add_private (klass, sizeof (TomatoUtilCountdownPrivate));
#line 571 "Countdown.c"
}


static void tomato_util_countdown_instance_init (TomatoUtilCountdown * self) {
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	self->priv = TOMATO_UTIL_COUNTDOWN_GET_PRIVATE (self);
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	self->ref_count = 1;
#line 580 "Countdown.c"
}


static void tomato_util_countdown_finalize (TomatoUtilCountdown* obj) {
	TomatoUtilCountdown * self;
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TOMATO_UTIL_TYPE_COUNTDOWN, TomatoUtilCountdown);
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	g_signal_handlers_destroy (self);
#line 590 "Countdown.c"
}


GType tomato_util_countdown_get_type (void) {
	static volatile gsize tomato_util_countdown_type_id__volatile = 0;
	if (g_once_init_enter (&tomato_util_countdown_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { tomato_util_value_countdown_init, tomato_util_value_countdown_free_value, tomato_util_value_countdown_copy_value, tomato_util_value_countdown_peek_pointer, "p", tomato_util_value_countdown_collect_value, "p", tomato_util_value_countdown_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (TomatoUtilCountdownClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) tomato_util_countdown_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TomatoUtilCountdown), 0, (GInstanceInitFunc) tomato_util_countdown_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType tomato_util_countdown_type_id;
		tomato_util_countdown_type_id = g_type_register_fundamental (g_type_fundamental_next (), "TomatoUtilCountdown", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&tomato_util_countdown_type_id__volatile, tomato_util_countdown_type_id);
	}
	return tomato_util_countdown_type_id__volatile;
}


gpointer tomato_util_countdown_ref (gpointer instance) {
	TomatoUtilCountdown* self;
	self = instance;
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	g_atomic_int_inc (&self->ref_count);
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	return instance;
#line 615 "Countdown.c"
}


void tomato_util_countdown_unref (gpointer instance) {
	TomatoUtilCountdown* self;
	self = instance;
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
		TOMATO_UTIL_COUNTDOWN_GET_CLASS (self)->finalize (self);
#line 21 "/home/lamm/Projetos/tomato/src/Util/Countdown.vala"
		g_type_free_instance ((GTypeInstance *) self);
#line 628 "Countdown.c"
	}
}



