/* Tomato.c generated by valac 0.34.7, the Vala compiler
 * generated from Tomato.vala, do not modify */

/* Copyright 2015 LuizAugustoMorais
*
* This file is part of Tomato.
*
* Tomato is free software: you can redistribute it
* and/or modify it under the terms of the GNU General Public License as
* published by the Free Software Foundation, either version 3 of the
* License, or (at your option) any later version.
*
* Tomato is distributed in the hope that it will be
* useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
* Public License for more details.
*
* You should have received a copy of the GNU General Public License along
* with Tomato. If not, see http://www.gnu.org/licenses/.
*/

#include <glib.h>
#include <glib-object.h>
#include <granite.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <locale.h>
#include <glib/gi18n-lib.h>
#include <gdk/gdk.h>


#define TOMATO_TYPE_STATUS (tomato_status_get_type ())

#define TOMATO_SERVICES_TYPE_SAVED_STATE (tomato_services_saved_state_get_type ())
#define TOMATO_SERVICES_SAVED_STATE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TOMATO_SERVICES_TYPE_SAVED_STATE, TomatoServicesSavedState))
#define TOMATO_SERVICES_SAVED_STATE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TOMATO_SERVICES_TYPE_SAVED_STATE, TomatoServicesSavedStateClass))
#define TOMATO_SERVICES_IS_SAVED_STATE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TOMATO_SERVICES_TYPE_SAVED_STATE))
#define TOMATO_SERVICES_IS_SAVED_STATE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TOMATO_SERVICES_TYPE_SAVED_STATE))
#define TOMATO_SERVICES_SAVED_STATE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TOMATO_SERVICES_TYPE_SAVED_STATE, TomatoServicesSavedStateClass))

typedef struct _TomatoServicesSavedState TomatoServicesSavedState;
typedef struct _TomatoServicesSavedStateClass TomatoServicesSavedStateClass;

#define TOMATO_SERVICES_TYPE_SETTINGS (tomato_services_settings_get_type ())
#define TOMATO_SERVICES_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TOMATO_SERVICES_TYPE_SETTINGS, TomatoServicesSettings))
#define TOMATO_SERVICES_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TOMATO_SERVICES_TYPE_SETTINGS, TomatoServicesSettingsClass))
#define TOMATO_SERVICES_IS_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TOMATO_SERVICES_TYPE_SETTINGS))
#define TOMATO_SERVICES_IS_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TOMATO_SERVICES_TYPE_SETTINGS))
#define TOMATO_SERVICES_SETTINGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TOMATO_SERVICES_TYPE_SETTINGS, TomatoServicesSettingsClass))

typedef struct _TomatoServicesSettings TomatoServicesSettings;
typedef struct _TomatoServicesSettingsClass TomatoServicesSettingsClass;

#define TOMATO_SERVICES_TYPE_PREFERENCES (tomato_services_preferences_get_type ())
#define TOMATO_SERVICES_PREFERENCES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TOMATO_SERVICES_TYPE_PREFERENCES, TomatoServicesPreferences))
#define TOMATO_SERVICES_PREFERENCES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TOMATO_SERVICES_TYPE_PREFERENCES, TomatoServicesPreferencesClass))
#define TOMATO_SERVICES_IS_PREFERENCES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TOMATO_SERVICES_TYPE_PREFERENCES))
#define TOMATO_SERVICES_IS_PREFERENCES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TOMATO_SERVICES_TYPE_PREFERENCES))
#define TOMATO_SERVICES_PREFERENCES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TOMATO_SERVICES_TYPE_PREFERENCES, TomatoServicesPreferencesClass))

typedef struct _TomatoServicesPreferences TomatoServicesPreferences;
typedef struct _TomatoServicesPreferencesClass TomatoServicesPreferencesClass;

#define TOMATO_MANAGERS_TYPE_NOTIFICATION_MANAGER (tomato_managers_notification_manager_get_type ())
#define TOMATO_MANAGERS_NOTIFICATION_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TOMATO_MANAGERS_TYPE_NOTIFICATION_MANAGER, TomatoManagersNotificationManager))
#define TOMATO_MANAGERS_NOTIFICATION_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TOMATO_MANAGERS_TYPE_NOTIFICATION_MANAGER, TomatoManagersNotificationManagerClass))
#define TOMATO_MANAGERS_IS_NOTIFICATION_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TOMATO_MANAGERS_TYPE_NOTIFICATION_MANAGER))
#define TOMATO_MANAGERS_IS_NOTIFICATION_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TOMATO_MANAGERS_TYPE_NOTIFICATION_MANAGER))
#define TOMATO_MANAGERS_NOTIFICATION_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TOMATO_MANAGERS_TYPE_NOTIFICATION_MANAGER, TomatoManagersNotificationManagerClass))

typedef struct _TomatoManagersNotificationManager TomatoManagersNotificationManager;
typedef struct _TomatoManagersNotificationManagerClass TomatoManagersNotificationManagerClass;

#define TOMATO_MANAGERS_TYPE_LAUNCHER_MANAGER (tomato_managers_launcher_manager_get_type ())
#define TOMATO_MANAGERS_LAUNCHER_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TOMATO_MANAGERS_TYPE_LAUNCHER_MANAGER, TomatoManagersLauncherManager))
#define TOMATO_MANAGERS_LAUNCHER_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TOMATO_MANAGERS_TYPE_LAUNCHER_MANAGER, TomatoManagersLauncherManagerClass))
#define TOMATO_MANAGERS_IS_LAUNCHER_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TOMATO_MANAGERS_TYPE_LAUNCHER_MANAGER))
#define TOMATO_MANAGERS_IS_LAUNCHER_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TOMATO_MANAGERS_TYPE_LAUNCHER_MANAGER))
#define TOMATO_MANAGERS_LAUNCHER_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TOMATO_MANAGERS_TYPE_LAUNCHER_MANAGER, TomatoManagersLauncherManagerClass))

typedef struct _TomatoManagersLauncherManager TomatoManagersLauncherManager;
typedef struct _TomatoManagersLauncherManagerClass TomatoManagersLauncherManagerClass;

#define TOMATO_MANAGERS_TYPE_WORK_MANAGER (tomato_managers_work_manager_get_type ())
#define TOMATO_MANAGERS_WORK_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TOMATO_MANAGERS_TYPE_WORK_MANAGER, TomatoManagersWorkManager))
#define TOMATO_MANAGERS_WORK_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TOMATO_MANAGERS_TYPE_WORK_MANAGER, TomatoManagersWorkManagerClass))
#define TOMATO_MANAGERS_IS_WORK_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TOMATO_MANAGERS_TYPE_WORK_MANAGER))
#define TOMATO_MANAGERS_IS_WORK_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TOMATO_MANAGERS_TYPE_WORK_MANAGER))
#define TOMATO_MANAGERS_WORK_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TOMATO_MANAGERS_TYPE_WORK_MANAGER, TomatoManagersWorkManagerClass))

typedef struct _TomatoManagersWorkManager TomatoManagersWorkManager;
typedef struct _TomatoManagersWorkManagerClass TomatoManagersWorkManagerClass;

#define TOMATO_TYPE_TOMATO_APP (tomato_tomato_app_get_type ())
#define TOMATO_TOMATO_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TOMATO_TYPE_TOMATO_APP, TomatoTomatoApp))
#define TOMATO_TOMATO_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TOMATO_TYPE_TOMATO_APP, TomatoTomatoAppClass))
#define TOMATO_IS_TOMATO_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TOMATO_TYPE_TOMATO_APP))
#define TOMATO_IS_TOMATO_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TOMATO_TYPE_TOMATO_APP))
#define TOMATO_TOMATO_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TOMATO_TYPE_TOMATO_APP, TomatoTomatoAppClass))

typedef struct _TomatoTomatoApp TomatoTomatoApp;
typedef struct _TomatoTomatoAppClass TomatoTomatoAppClass;
typedef struct _TomatoTomatoAppPrivate TomatoTomatoAppPrivate;

#define TOMATO_WINDOW_TYPE_MAIN_WINDOW (tomato_window_main_window_get_type ())
#define TOMATO_WINDOW_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TOMATO_WINDOW_TYPE_MAIN_WINDOW, TomatoWindowMainWindow))
#define TOMATO_WINDOW_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TOMATO_WINDOW_TYPE_MAIN_WINDOW, TomatoWindowMainWindowClass))
#define TOMATO_WINDOW_IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TOMATO_WINDOW_TYPE_MAIN_WINDOW))
#define TOMATO_WINDOW_IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TOMATO_WINDOW_TYPE_MAIN_WINDOW))
#define TOMATO_WINDOW_MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TOMATO_WINDOW_TYPE_MAIN_WINDOW, TomatoWindowMainWindowClass))

typedef struct _TomatoWindowMainWindow TomatoWindowMainWindow;
typedef struct _TomatoWindowMainWindowClass TomatoWindowMainWindowClass;

#define TOMATO_WINDOW_TYPE_PREFERENCES_DIALOG (tomato_window_preferences_dialog_get_type ())
#define TOMATO_WINDOW_PREFERENCES_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TOMATO_WINDOW_TYPE_PREFERENCES_DIALOG, TomatoWindowPreferencesDialog))
#define TOMATO_WINDOW_PREFERENCES_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TOMATO_WINDOW_TYPE_PREFERENCES_DIALOG, TomatoWindowPreferencesDialogClass))
#define TOMATO_WINDOW_IS_PREFERENCES_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TOMATO_WINDOW_TYPE_PREFERENCES_DIALOG))
#define TOMATO_WINDOW_IS_PREFERENCES_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TOMATO_WINDOW_TYPE_PREFERENCES_DIALOG))
#define TOMATO_WINDOW_PREFERENCES_DIALOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TOMATO_WINDOW_TYPE_PREFERENCES_DIALOG, TomatoWindowPreferencesDialogClass))

typedef struct _TomatoWindowPreferencesDialog TomatoWindowPreferencesDialog;
typedef struct _TomatoWindowPreferencesDialogClass TomatoWindowPreferencesDialogClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _tomato_managers_work_manager_unref0(var) ((var == NULL) ? NULL : (var = (tomato_managers_work_manager_unref (var), NULL)))
#define _tomato_managers_notification_manager_unref0(var) ((var == NULL) ? NULL : (var = (tomato_managers_notification_manager_unref (var), NULL)))
#define _tomato_managers_launcher_manager_unref0(var) ((var == NULL) ? NULL : (var = (tomato_managers_launcher_manager_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_rand_free0(var) ((var == NULL) ? NULL : (var = (g_rand_free (var), NULL)))

typedef enum  {
	TOMATO_STATUS_START,
	TOMATO_STATUS_POMODORO,
	TOMATO_STATUS_SHORT_BREAK,
	TOMATO_STATUS_LONG_BREAK
} TomatoStatus;

struct _TomatoTomatoApp {
	GraniteApplication parent_instance;
	TomatoTomatoAppPrivate * priv;
};

struct _TomatoTomatoAppClass {
	GraniteApplicationClass parent_class;
};

struct _TomatoTomatoAppPrivate {
	TomatoWindowMainWindow* window;
	TomatoWindowPreferencesDialog* pref_window;
	guint work_timeout_id;
	guint stop_timeout_id;
};


extern TomatoServicesSavedState* tomato_saved;
TomatoServicesSavedState* tomato_saved = NULL;
extern TomatoServicesSettings* tomato_settings;
TomatoServicesSettings* tomato_settings = NULL;
extern TomatoServicesPreferences* tomato_preferences;
TomatoServicesPreferences* tomato_preferences = NULL;
extern gint tomato_break_messages_index;
gint tomato_break_messages_index = 0;
extern TomatoManagersNotificationManager* tomato_notification;
TomatoManagersNotificationManager* tomato_notification = NULL;
extern TomatoManagersLauncherManager* tomato_launcher;
TomatoManagersLauncherManager* tomato_launcher = NULL;
extern TomatoManagersWorkManager* tomato_work;
TomatoManagersWorkManager* tomato_work = NULL;
extern gint tomato_stop_countdown;
gint tomato_stop_countdown = 14;
extern gboolean tomato_paused;
gboolean tomato_paused = TRUE;
extern gboolean tomato_stopped;
gboolean tomato_stopped = TRUE;
static gpointer tomato_tomato_app_parent_class = NULL;

GType tomato_status_get_type (void) G_GNUC_CONST;
GType tomato_services_saved_state_get_type (void) G_GNUC_CONST;
GType tomato_services_settings_get_type (void) G_GNUC_CONST;
GType tomato_services_preferences_get_type (void) G_GNUC_CONST;
gpointer tomato_managers_notification_manager_ref (gpointer instance);
void tomato_managers_notification_manager_unref (gpointer instance);
GParamSpec* tomato_managers_param_spec_notification_manager (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void tomato_managers_value_set_notification_manager (GValue* value, gpointer v_object);
void tomato_managers_value_take_notification_manager (GValue* value, gpointer v_object);
gpointer tomato_managers_value_get_notification_manager (const GValue* value);
GType tomato_managers_notification_manager_get_type (void) G_GNUC_CONST;
gpointer tomato_managers_launcher_manager_ref (gpointer instance);
void tomato_managers_launcher_manager_unref (gpointer instance);
GParamSpec* tomato_managers_param_spec_launcher_manager (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void tomato_managers_value_set_launcher_manager (GValue* value, gpointer v_object);
void tomato_managers_value_take_launcher_manager (GValue* value, gpointer v_object);
gpointer tomato_managers_value_get_launcher_manager (const GValue* value);
GType tomato_managers_launcher_manager_get_type (void) G_GNUC_CONST;
gpointer tomato_managers_work_manager_ref (gpointer instance);
void tomato_managers_work_manager_unref (gpointer instance);
GParamSpec* tomato_managers_param_spec_work_manager (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void tomato_managers_value_set_work_manager (GValue* value, gpointer v_object);
void tomato_managers_value_take_work_manager (GValue* value, gpointer v_object);
gpointer tomato_managers_value_get_work_manager (const GValue* value);
GType tomato_managers_work_manager_get_type (void) G_GNUC_CONST;
GType tomato_tomato_app_get_type (void) G_GNUC_CONST;
GType tomato_window_main_window_get_type (void) G_GNUC_CONST;
GType tomato_window_preferences_dialog_get_type (void) G_GNUC_CONST;
#define TOMATO_TOMATO_APP_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TOMATO_TYPE_TOMATO_APP, TomatoTomatoAppPrivate))
enum  {
	TOMATO_TOMATO_APP_DUMMY_PROPERTY
};
#define TOMATO_TOMATO_APP_TIME ((guint) 100)
TomatoTomatoApp* tomato_tomato_app_new (void);
TomatoTomatoApp* tomato_tomato_app_construct (GType object_type);
#define CONSTANTS_APP_NAME "Tomato"
TomatoServicesSavedState* tomato_services_saved_state_new (void);
TomatoServicesSavedState* tomato_services_saved_state_construct (GType object_type);
TomatoServicesSettings* tomato_services_settings_new (void);
TomatoServicesSettings* tomato_services_settings_construct (GType object_type);
TomatoServicesPreferences* tomato_services_preferences_new (void);
TomatoServicesPreferences* tomato_services_preferences_construct (GType object_type);
TomatoManagersWorkManager* tomato_managers_work_manager_new (void);
TomatoManagersWorkManager* tomato_managers_work_manager_construct (GType object_type);
TomatoManagersNotificationManager* tomato_managers_notification_manager_new (void);
TomatoManagersNotificationManager* tomato_managers_notification_manager_construct (GType object_type);
TomatoManagersLauncherManager* tomato_managers_launcher_manager_new (void);
TomatoManagersLauncherManager* tomato_managers_launcher_manager_construct (GType object_type);
#define CONSTANTS_DATADIR "/usr/share"
#define CONSTANTS_GETTEXT_PACKAGE "tomato"
void tomato_services_preferences_set_debug_mode (TomatoServicesPreferences* self, gboolean value);
static void tomato_tomato_app_real_activate (GApplication* base);
TomatoWindowMainWindow* tomato_window_main_window_new (TomatoTomatoApp* app);
TomatoWindowMainWindow* tomato_window_main_window_construct (GType object_type, TomatoTomatoApp* app);
static void tomato_tomato_app_connect_signals (TomatoTomatoApp* self);
static gboolean tomato_tomato_app_update_time (TomatoTomatoApp* self);
void tomato_managers_work_manager_tick (TomatoManagersWorkManager* self);
gboolean tomato_managers_work_manager_time_is_over (TomatoManagersWorkManager* self);
void tomato_managers_notification_manager_show_status (TomatoManagersNotificationManager* self);
static void tomato_tomato_app_next_status (TomatoTomatoApp* self);
gboolean tomato_services_preferences_get_pause_after_break (TomatoServicesPreferences* self);
TomatoStatus tomato_services_saved_state_get_status (TomatoServicesSavedState* self);
static void tomato_tomato_app_update_progress (TomatoTomatoApp* self);
static gboolean tomato_tomato_app_start_auto_stop (TomatoTomatoApp* self);
void tomato_window_main_window_update_stop (TomatoWindowMainWindow* self, const gchar* text);
static void tomato_tomato_app_on_stop_clicked (TomatoTomatoApp* self);
void tomato_managers_notification_manager_show (TomatoManagersNotificationManager* self, const gchar* title, const gchar* body);
static void tomato_tomato_app_finish_auto_stop (TomatoTomatoApp* self);
static void tomato_tomato_app_on_start_clicked (TomatoTomatoApp* self);
void tomato_managers_work_manager_start (TomatoManagersWorkManager* self);
static void tomato_tomato_app_play (TomatoTomatoApp* self);
static void tomato_tomato_app_on_resume_clicked (TomatoTomatoApp* self);
gboolean tomato_services_preferences_get_auto_stop (TomatoServicesPreferences* self);
static void tomato_tomato_app_on_pause_clicked (TomatoTomatoApp* self);
static void tomato_tomato_app_pause (TomatoTomatoApp* self);
static gboolean _tomato_tomato_app_start_auto_stop_gsource_func (gpointer self);
static void tomato_tomato_app_stop (TomatoTomatoApp* self);
void tomato_managers_work_manager_stop (TomatoManagersWorkManager* self);
void tomato_managers_work_manager_reset_countdown (TomatoManagersWorkManager* self);
static void tomato_tomato_app_on_skip_clicked (TomatoTomatoApp* self);
static void tomato_tomato_app_on_preferences_clicked (TomatoTomatoApp* self);
TomatoWindowPreferencesDialog* tomato_window_preferences_dialog_new (GtkWindow* parent);
TomatoWindowPreferencesDialog* tomato_window_preferences_dialog_construct (GType object_type, GtkWindow* parent);
static void tomato_tomato_app_connect_pref_signals (TomatoTomatoApp* self);
static void tomato_tomato_app_set_pause (TomatoTomatoApp* self, gboolean topause);
static gboolean _tomato_tomato_app_update_time_gsource_func (gpointer self);
void tomato_managers_launcher_manager_hide_progress (TomatoManagersLauncherManager* self);
void tomato_window_main_window_set_pause (TomatoWindowMainWindow* self, gboolean topause);
void tomato_window_main_window_update_progress (TomatoWindowMainWindow* self);
void tomato_managers_launcher_manager_update_progress (TomatoManagersLauncherManager* self);
void tomato_window_main_window_next_status (TomatoWindowMainWindow* self, GtkStackTransitionType transition);
static void _tomato_tomato_app_on_start_clicked_tomato_window_main_window_start_clicked (TomatoWindowMainWindow* _sender, gpointer self);
static void _tomato_tomato_app_on_resume_clicked_tomato_window_main_window_resume_clicked (TomatoWindowMainWindow* _sender, gpointer self);
static void _tomato_tomato_app_on_pause_clicked_tomato_window_main_window_pause_clicked (TomatoWindowMainWindow* _sender, gpointer self);
static void _tomato_tomato_app_on_stop_clicked_tomato_window_main_window_stop_clicked (TomatoWindowMainWindow* _sender, gpointer self);
static void _tomato_tomato_app_on_skip_clicked_tomato_window_main_window_skip_clicked (TomatoWindowMainWindow* _sender, gpointer self);
static void _tomato_tomato_app_on_preferences_clicked_tomato_window_main_window_preferences_clicked (TomatoWindowMainWindow* _sender, gpointer self);
static void _tomato_tomato_app_on_stop_clicked_tomato_tomato_app_paused_on_break (TomatoTomatoApp* _sender, gpointer self);
static gboolean __lambda18_ (TomatoTomatoApp* self, GdkEventWindowState* event);
void tomato_managers_launcher_manager_show_progress (TomatoManagersLauncherManager* self);
static gboolean ___lambda18__gtk_widget_window_state_event (GtkWidget* _sender, GdkEventWindowState* event, gpointer self);
static void __lambda12_ (TomatoTomatoApp* self);
void tomato_window_preferences_dialog_update_timing_sensitivity (TomatoWindowPreferencesDialog* self);
static void ___lambda12__tomato_window_preferences_dialog_pomodoro_changed (TomatoWindowPreferencesDialog* _sender, gpointer self);
static void __lambda13_ (TomatoTomatoApp* self);
static void ___lambda13__tomato_window_preferences_dialog_short_break_changed (TomatoWindowPreferencesDialog* _sender, gpointer self);
static void __lambda14_ (TomatoTomatoApp* self);
static void ___lambda14__tomato_window_preferences_dialog_long_break_changed (TomatoWindowPreferencesDialog* _sender, gpointer self);
static void __lambda15_ (TomatoTomatoApp* self);
static void ___lambda15__tomato_window_preferences_dialog_long_break_delay_changed (TomatoWindowPreferencesDialog* _sender, gpointer self);
static void __lambda16_ (TomatoTomatoApp* self);
void tomato_window_preferences_dialog_update_work_sensitivity (TomatoWindowPreferencesDialog* self);
static void ___lambda16__granite_services_settings_changed (GraniteServicesSettings* _sender, gpointer self);
static void __lambda17_ (TomatoTomatoApp* self);
void tomato_managers_work_manager_reset (TomatoManagersWorkManager* self);
static void ___lambda17__tomato_window_preferences_dialog_reset_work_clicked (TomatoWindowPreferencesDialog* _sender, gpointer self);
static GObject * tomato_tomato_app_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
#define CONSTANTS_EXEC_NAME "tomato"
#define CONSTANTS_VERSION "1.2.7"
#define CONSTANTS_ICON_NAME "tomato"
static void tomato_tomato_app_finalize (GObject* obj);
void tomato_main (gchar** args, int args_length1);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);

const gchar* TOMATO_break_messages[11] = {"Go have a coffee", "Drink some water", "Get up and dance!", "Have a break, have a tomato", "Get up! Stand up! Fight for your fingers!", "Take a break, save a life", "Woot! Break time, baby!", "It's coffee time!", "What about a beer?", "Take a walk outside", "Step away from the machine!"};

GType tomato_status_get_type (void) {
	static volatile gsize tomato_status_type_id__volatile = 0;
	if (g_once_init_enter (&tomato_status_type_id__volatile)) {
		static const GEnumValue values[] = {{TOMATO_STATUS_START, "TOMATO_STATUS_START", "start"}, {TOMATO_STATUS_POMODORO, "TOMATO_STATUS_POMODORO", "pomodoro"}, {TOMATO_STATUS_SHORT_BREAK, "TOMATO_STATUS_SHORT_BREAK", "short-break"}, {TOMATO_STATUS_LONG_BREAK, "TOMATO_STATUS_LONG_BREAK", "long-break"}, {0, NULL, NULL}};
		GType tomato_status_type_id;
		tomato_status_type_id = g_enum_register_static ("TomatoStatus", values);
		g_once_init_leave (&tomato_status_type_id__volatile, tomato_status_type_id);
	}
	return tomato_status_type_id__volatile;
}


TomatoTomatoApp* tomato_tomato_app_construct (GType object_type) {
	TomatoTomatoApp * self = NULL;
	GraniteServicesLogLevel _tmp0_ = 0;
	GraniteServicesLogLevel _tmp1_ = 0;
	TomatoServicesSavedState* _tmp2_ = NULL;
	TomatoServicesSettings* _tmp3_ = NULL;
	TomatoServicesPreferences* _tmp4_ = NULL;
	TomatoManagersWorkManager* _tmp5_ = NULL;
	TomatoManagersNotificationManager* _tmp6_ = NULL;
	TomatoManagersLauncherManager* _tmp7_ = NULL;
	gchar* langpack_dir = NULL;
	gchar* _tmp8_ = NULL;
	TomatoServicesPreferences* _tmp9_ = NULL;
#line 90 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	self = (TomatoTomatoApp*) granite_application_construct (object_type);
#line 92 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	granite_services_logger_initialize (CONSTANTS_APP_NAME);
#line 93 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp0_ = granite_services_logger_get_DisplayLevel ();
#line 93 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp1_ = _tmp0_;
#line 93 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	granite_services_logger_set_DisplayLevel (GRANITE_SERVICES_LOG_LEVEL_DEBUG);
#line 96 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp2_ = tomato_services_saved_state_new ();
#line 96 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_g_object_unref0 (tomato_saved);
#line 96 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_saved = _tmp2_;
#line 97 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp3_ = tomato_services_settings_new ();
#line 97 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_g_object_unref0 (tomato_settings);
#line 97 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_settings = _tmp3_;
#line 98 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp4_ = tomato_services_preferences_new ();
#line 98 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_g_object_unref0 (tomato_preferences);
#line 98 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_preferences = _tmp4_;
#line 101 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp5_ = tomato_managers_work_manager_new ();
#line 101 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tomato_managers_work_manager_unref0 (tomato_work);
#line 101 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_work = _tmp5_;
#line 102 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp6_ = tomato_managers_notification_manager_new ();
#line 102 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tomato_managers_notification_manager_unref0 (tomato_notification);
#line 102 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_notification = _tmp6_;
#line 103 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp7_ = tomato_managers_launcher_manager_new ();
#line 103 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tomato_managers_launcher_manager_unref0 (tomato_launcher);
#line 103 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_launcher = _tmp7_;
#line 106 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	setlocale (LC_ALL, "");
#line 107 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp8_ = g_build_filename (CONSTANTS_DATADIR, "locale", NULL);
#line 107 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	langpack_dir = _tmp8_;
#line 108 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	bindtextdomain (CONSTANTS_GETTEXT_PACKAGE, langpack_dir);
#line 109 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	bind_textdomain_codeset (CONSTANTS_GETTEXT_PACKAGE, "UTF-8");
#line 110 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	textdomain (CONSTANTS_GETTEXT_PACKAGE);
#line 113 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp9_ = tomato_preferences;
#line 113 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_services_preferences_set_debug_mode (_tmp9_, FALSE);
#line 90 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_g_free0 (langpack_dir);
#line 90 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	return self;
#line 398 "Tomato.c"
}


TomatoTomatoApp* tomato_tomato_app_new (void) {
#line 90 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	return tomato_tomato_app_construct (TOMATO_TYPE_TOMATO_APP);
#line 405 "Tomato.c"
}


static void tomato_tomato_app_real_activate (GApplication* base) {
	TomatoTomatoApp * self;
	TomatoWindowMainWindow* _tmp0_ = NULL;
#line 116 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	self = (TomatoTomatoApp*) base;
#line 117 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp0_ = self->priv->window;
#line 117 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	if (_tmp0_ == NULL) {
#line 418 "Tomato.c"
		TomatoWindowMainWindow* _tmp1_ = NULL;
#line 118 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp1_ = tomato_window_main_window_new (self);
#line 118 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		g_object_ref_sink (_tmp1_);
#line 118 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_g_object_unref0 (self->priv->window);
#line 118 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		self->priv->window = _tmp1_;
#line 119 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		tomato_tomato_app_connect_signals (self);
#line 120 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		gtk_main ();
#line 432 "Tomato.c"
	} else {
		TomatoWindowMainWindow* _tmp2_ = NULL;
#line 122 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		g_message ("Tomato.vala:122: There is an instance of tomato already open.");
#line 123 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp2_ = self->priv->window;
#line 123 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		gtk_window_present ((GtkWindow*) _tmp2_);
#line 441 "Tomato.c"
	}
}


static gboolean tomato_tomato_app_update_time (TomatoTomatoApp* self) {
	gboolean result = FALSE;
	GRand* rand = NULL;
	GRand* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp15_ = FALSE;
#line 127 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 128 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp0_ = g_rand_new ();
#line 128 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	rand = _tmp0_;
#line 129 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp1_ = tomato_paused;
#line 129 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	if (!_tmp1_) {
#line 462 "Tomato.c"
		TomatoManagersWorkManager* _tmp2_ = NULL;
		TomatoManagersWorkManager* _tmp3_ = NULL;
		gboolean _tmp4_ = FALSE;
#line 130 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp2_ = tomato_work;
#line 130 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		tomato_managers_work_manager_tick (_tmp2_);
#line 131 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp3_ = tomato_work;
#line 131 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp4_ = tomato_managers_work_manager_time_is_over (_tmp3_);
#line 131 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		if (_tmp4_) {
#line 476 "Tomato.c"
			GRand* _tmp5_ = NULL;
			gint32 _tmp6_ = 0;
			TomatoManagersNotificationManager* _tmp7_ = NULL;
			gboolean _tmp8_ = FALSE;
			TomatoServicesPreferences* _tmp9_ = NULL;
			gboolean _tmp10_ = FALSE;
			gboolean _tmp11_ = FALSE;
#line 132 "/home/lamm/Projetos/tomato/src/Tomato.vala"
			_tmp5_ = rand;
#line 132 "/home/lamm/Projetos/tomato/src/Tomato.vala"
			_tmp6_ = g_rand_int_range (_tmp5_, (gint32) 0, (gint32) G_N_ELEMENTS (TOMATO_break_messages));
#line 132 "/home/lamm/Projetos/tomato/src/Tomato.vala"
			tomato_break_messages_index = (gint) _tmp6_;
#line 133 "/home/lamm/Projetos/tomato/src/Tomato.vala"
			_tmp7_ = tomato_notification;
#line 133 "/home/lamm/Projetos/tomato/src/Tomato.vala"
			tomato_managers_notification_manager_show_status (_tmp7_);
#line 134 "/home/lamm/Projetos/tomato/src/Tomato.vala"
			tomato_tomato_app_next_status (self);
#line 135 "/home/lamm/Projetos/tomato/src/Tomato.vala"
			_tmp9_ = tomato_preferences;
#line 135 "/home/lamm/Projetos/tomato/src/Tomato.vala"
			_tmp10_ = tomato_services_preferences_get_pause_after_break (_tmp9_);
#line 135 "/home/lamm/Projetos/tomato/src/Tomato.vala"
			_tmp11_ = _tmp10_;
#line 135 "/home/lamm/Projetos/tomato/src/Tomato.vala"
			if (_tmp11_) {
#line 504 "Tomato.c"
				TomatoServicesSavedState* _tmp12_ = NULL;
				TomatoStatus _tmp13_ = 0;
				TomatoStatus _tmp14_ = 0;
#line 135 "/home/lamm/Projetos/tomato/src/Tomato.vala"
				_tmp12_ = tomato_saved;
#line 135 "/home/lamm/Projetos/tomato/src/Tomato.vala"
				_tmp13_ = tomato_services_saved_state_get_status (_tmp12_);
#line 135 "/home/lamm/Projetos/tomato/src/Tomato.vala"
				_tmp14_ = _tmp13_;
#line 135 "/home/lamm/Projetos/tomato/src/Tomato.vala"
				_tmp8_ = _tmp14_ == TOMATO_STATUS_POMODORO;
#line 516 "Tomato.c"
			} else {
#line 135 "/home/lamm/Projetos/tomato/src/Tomato.vala"
				_tmp8_ = FALSE;
#line 520 "Tomato.c"
			}
#line 135 "/home/lamm/Projetos/tomato/src/Tomato.vala"
			if (_tmp8_) {
#line 136 "/home/lamm/Projetos/tomato/src/Tomato.vala"
				g_signal_emit_by_name (self, "paused-on-break");
#line 137 "/home/lamm/Projetos/tomato/src/Tomato.vala"
				result = FALSE;
#line 137 "/home/lamm/Projetos/tomato/src/Tomato.vala"
				_g_rand_free0 (rand);
#line 137 "/home/lamm/Projetos/tomato/src/Tomato.vala"
				return result;
#line 532 "Tomato.c"
			}
		}
#line 140 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		tomato_tomato_app_update_progress (self);
#line 537 "Tomato.c"
	}
#line 141 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp15_ = tomato_paused;
#line 141 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	result = !_tmp15_;
#line 141 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_g_rand_free0 (rand);
#line 141 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	return result;
#line 547 "Tomato.c"
}


static gboolean tomato_tomato_app_start_auto_stop (TomatoTomatoApp* self) {
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp15_ = FALSE;
#line 144 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 145 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp1_ = tomato_paused;
#line 145 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	if (_tmp1_) {
#line 562 "Tomato.c"
		gboolean _tmp2_ = FALSE;
#line 145 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp2_ = tomato_stopped;
#line 145 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp0_ = !_tmp2_;
#line 568 "Tomato.c"
	} else {
#line 145 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp0_ = FALSE;
#line 572 "Tomato.c"
	}
#line 145 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	if (_tmp0_) {
#line 576 "Tomato.c"
		TomatoWindowMainWindow* _tmp3_ = NULL;
		const gchar* _tmp4_ = NULL;
		gint _tmp5_ = 0;
		gchar* _tmp6_ = NULL;
		gchar* _tmp7_ = NULL;
		gchar* _tmp8_ = NULL;
		gchar* _tmp9_ = NULL;
		gint _tmp10_ = 0;
		gint _tmp11_ = 0;
#line 146 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp3_ = self->priv->window;
#line 146 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp4_ = _ ("Stopping in ");
#line 146 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp5_ = tomato_stop_countdown;
#line 146 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp6_ = g_strdup_printf ("%d", _tmp5_);
#line 146 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp7_ = _tmp6_;
#line 146 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp8_ = g_strconcat (_tmp4_, _tmp7_, NULL);
#line 146 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp9_ = _tmp8_;
#line 146 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		tomato_window_main_window_update_stop (_tmp3_, _tmp9_);
#line 146 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_g_free0 (_tmp9_);
#line 146 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_g_free0 (_tmp7_);
#line 147 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp10_ = tomato_stop_countdown;
#line 147 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		tomato_stop_countdown = _tmp10_ - 1;
#line 148 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp11_ = tomato_stop_countdown;
#line 148 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		if (_tmp11_ == -1) {
#line 614 "Tomato.c"
			TomatoManagersNotificationManager* _tmp12_ = NULL;
			const gchar* _tmp13_ = NULL;
			const gchar* _tmp14_ = NULL;
#line 149 "/home/lamm/Projetos/tomato/src/Tomato.vala"
			tomato_tomato_app_on_stop_clicked (self);
#line 150 "/home/lamm/Projetos/tomato/src/Tomato.vala"
			tomato_stop_countdown = 14;
#line 151 "/home/lamm/Projetos/tomato/src/Tomato.vala"
			_tmp12_ = tomato_notification;
#line 151 "/home/lamm/Projetos/tomato/src/Tomato.vala"
			_tmp13_ = _ ("Pomodoro was interrupted");
#line 151 "/home/lamm/Projetos/tomato/src/Tomato.vala"
			_tmp14_ = _ ("Tomato was paused for a long time. You might have lost focus. Try a ne" \
"w pomodoro!");
#line 151 "/home/lamm/Projetos/tomato/src/Tomato.vala"
			tomato_managers_notification_manager_show (_tmp12_, _tmp13_, _tmp14_);
#line 630 "Tomato.c"
		}
	}
#line 153 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp15_ = tomato_paused;
#line 153 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	result = _tmp15_;
#line 153 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	return result;
#line 639 "Tomato.c"
}


static void tomato_tomato_app_finish_auto_stop (TomatoTomatoApp* self) {
	guint _tmp0_ = 0U;
	TomatoWindowMainWindow* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
#line 156 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	g_return_if_fail (self != NULL);
#line 157 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp0_ = self->priv->stop_timeout_id;
#line 157 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	g_source_remove (_tmp0_);
#line 158 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	self->priv->stop_timeout_id = (guint) 0;
#line 159 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_stop_countdown = 14;
#line 160 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp1_ = self->priv->window;
#line 160 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp2_ = _ ("Stop");
#line 160 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_window_main_window_update_stop (_tmp1_, _tmp2_);
#line 161 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	g_message ("Tomato.vala:161: Finished auto stop");
#line 665 "Tomato.c"
}


static void tomato_tomato_app_on_start_clicked (TomatoTomatoApp* self) {
	TomatoManagersWorkManager* _tmp0_ = NULL;
#line 165 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	g_return_if_fail (self != NULL);
#line 166 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp0_ = tomato_work;
#line 166 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_managers_work_manager_start (_tmp0_);
#line 167 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_tomato_app_next_status (self);
#line 168 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_tomato_app_update_progress (self);
#line 169 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_tomato_app_play (self);
#line 683 "Tomato.c"
}


static void tomato_tomato_app_on_resume_clicked (TomatoTomatoApp* self) {
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	TomatoServicesPreferences* _tmp2_ = NULL;
	gboolean _tmp3_ = FALSE;
	gboolean _tmp4_ = FALSE;
#line 172 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	g_return_if_fail (self != NULL);
#line 173 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp2_ = tomato_preferences;
#line 173 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp3_ = tomato_services_preferences_get_auto_stop (_tmp2_);
#line 173 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp4_ = _tmp3_;
#line 173 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	if (_tmp4_) {
#line 703 "Tomato.c"
		guint _tmp5_ = 0U;
#line 173 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp5_ = self->priv->stop_timeout_id;
#line 173 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp1_ = _tmp5_ != ((guint) 0);
#line 709 "Tomato.c"
	} else {
#line 173 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp1_ = FALSE;
#line 713 "Tomato.c"
	}
#line 173 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	if (_tmp1_) {
#line 717 "Tomato.c"
		gboolean _tmp6_ = FALSE;
#line 173 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp6_ = tomato_stopped;
#line 173 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp0_ = !_tmp6_;
#line 723 "Tomato.c"
	} else {
#line 173 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp0_ = FALSE;
#line 727 "Tomato.c"
	}
#line 173 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	if (_tmp0_) {
#line 174 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		tomato_tomato_app_finish_auto_stop (self);
#line 733 "Tomato.c"
	}
#line 176 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_tomato_app_play (self);
#line 737 "Tomato.c"
}


static gboolean _tomato_tomato_app_start_auto_stop_gsource_func (gpointer self) {
	gboolean result;
	result = tomato_tomato_app_start_auto_stop ((TomatoTomatoApp*) self);
#line 185 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	return result;
#line 746 "Tomato.c"
}


static void tomato_tomato_app_on_pause_clicked (TomatoTomatoApp* self) {
	gboolean _tmp0_ = FALSE;
	TomatoServicesPreferences* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
#line 179 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	g_return_if_fail (self != NULL);
#line 180 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_tomato_app_pause (self);
#line 181 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_tomato_app_update_progress (self);
#line 183 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp1_ = tomato_preferences;
#line 183 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp2_ = tomato_services_preferences_get_auto_stop (_tmp1_);
#line 183 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp3_ = _tmp2_;
#line 183 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	if (_tmp3_) {
#line 769 "Tomato.c"
		TomatoServicesSavedState* _tmp4_ = NULL;
		TomatoStatus _tmp5_ = 0;
		TomatoStatus _tmp6_ = 0;
#line 183 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp4_ = tomato_saved;
#line 183 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp5_ = tomato_services_saved_state_get_status (_tmp4_);
#line 183 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp6_ = _tmp5_;
#line 183 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp0_ = _tmp6_ == TOMATO_STATUS_POMODORO;
#line 781 "Tomato.c"
	} else {
#line 183 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp0_ = FALSE;
#line 785 "Tomato.c"
	}
#line 183 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	if (_tmp0_) {
#line 789 "Tomato.c"
		guint _tmp7_ = 0U;
#line 184 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		g_message ("Tomato.vala:184: Auto stop countdown started");
#line 185 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp7_ = g_timeout_add_full (G_PRIORITY_DEFAULT, TOMATO_TOMATO_APP_TIME, _tomato_tomato_app_start_auto_stop_gsource_func, g_object_ref (self), g_object_unref);
#line 185 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		self->priv->stop_timeout_id = _tmp7_;
#line 797 "Tomato.c"
	} else {
#line 187 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		self->priv->stop_timeout_id = (guint) 0;
#line 801 "Tomato.c"
	}
}


static void tomato_tomato_app_on_stop_clicked (TomatoTomatoApp* self) {
	TomatoManagersWorkManager* _tmp0_ = NULL;
	TomatoManagersWorkManager* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
	TomatoServicesPreferences* _tmp4_ = NULL;
	gboolean _tmp5_ = FALSE;
	gboolean _tmp6_ = FALSE;
#line 191 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	g_return_if_fail (self != NULL);
#line 192 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_tomato_app_stop (self);
#line 193 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp0_ = tomato_work;
#line 193 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_managers_work_manager_stop (_tmp0_);
#line 194 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp1_ = tomato_work;
#line 194 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_managers_work_manager_reset_countdown (_tmp1_);
#line 195 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_tomato_app_next_status (self);
#line 197 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp4_ = tomato_preferences;
#line 197 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp5_ = tomato_services_preferences_get_auto_stop (_tmp4_);
#line 197 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp6_ = _tmp5_;
#line 197 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	if (_tmp6_) {
#line 836 "Tomato.c"
		guint _tmp7_ = 0U;
#line 197 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp7_ = self->priv->stop_timeout_id;
#line 197 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp3_ = _tmp7_ != ((guint) 0);
#line 842 "Tomato.c"
	} else {
#line 197 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp3_ = FALSE;
#line 846 "Tomato.c"
	}
#line 197 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	if (_tmp3_) {
#line 850 "Tomato.c"
		gboolean _tmp8_ = FALSE;
#line 197 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp8_ = tomato_stopped;
#line 197 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp2_ = _tmp8_;
#line 856 "Tomato.c"
	} else {
#line 197 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp2_ = FALSE;
#line 860 "Tomato.c"
	}
#line 197 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	if (_tmp2_) {
#line 198 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		tomato_tomato_app_finish_auto_stop (self);
#line 866 "Tomato.c"
	}
}


static void tomato_tomato_app_on_skip_clicked (TomatoTomatoApp* self) {
#line 202 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	g_return_if_fail (self != NULL);
#line 203 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_tomato_app_on_stop_clicked (self);
#line 876 "Tomato.c"
}


static void tomato_tomato_app_on_preferences_clicked (TomatoTomatoApp* self) {
	TomatoWindowMainWindow* _tmp0_ = NULL;
	TomatoWindowPreferencesDialog* _tmp1_ = NULL;
	TomatoWindowPreferencesDialog* _tmp2_ = NULL;
#line 206 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	g_return_if_fail (self != NULL);
#line 208 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp0_ = self->priv->window;
#line 208 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp1_ = tomato_window_preferences_dialog_new ((GtkWindow*) _tmp0_);
#line 208 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	g_object_ref_sink (_tmp1_);
#line 208 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_g_object_unref0 (self->priv->pref_window);
#line 208 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	self->priv->pref_window = _tmp1_;
#line 209 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp2_ = self->priv->pref_window;
#line 209 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	gtk_widget_show_all ((GtkWidget*) _tmp2_);
#line 211 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_tomato_app_connect_pref_signals (self);
#line 902 "Tomato.c"
}


static gboolean _tomato_tomato_app_update_time_gsource_func (gpointer self) {
	gboolean result;
	result = tomato_tomato_app_update_time ((TomatoTomatoApp*) self);
#line 219 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	return result;
#line 911 "Tomato.c"
}


static void tomato_tomato_app_play (TomatoTomatoApp* self) {
	guint _tmp0_ = 0U;
	guint _tmp2_ = 0U;
#line 214 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	g_return_if_fail (self != NULL);
#line 215 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_tomato_app_set_pause (self, FALSE);
#line 217 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp0_ = self->priv->work_timeout_id;
#line 217 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	if (_tmp0_ != ((guint) 0)) {
#line 926 "Tomato.c"
		guint _tmp1_ = 0U;
#line 218 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp1_ = self->priv->work_timeout_id;
#line 218 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		g_source_remove (_tmp1_);
#line 932 "Tomato.c"
	}
#line 219 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp2_ = g_timeout_add_full (G_PRIORITY_DEFAULT, TOMATO_TOMATO_APP_TIME, _tomato_tomato_app_update_time_gsource_func, g_object_ref (self), g_object_unref);
#line 219 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	self->priv->work_timeout_id = _tmp2_;
#line 938 "Tomato.c"
}


static void tomato_tomato_app_pause (TomatoTomatoApp* self) {
	TomatoManagersLauncherManager* _tmp0_ = NULL;
	guint _tmp1_ = 0U;
#line 222 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	g_return_if_fail (self != NULL);
#line 223 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_tomato_app_set_pause (self, TRUE);
#line 224 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp0_ = tomato_launcher;
#line 224 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_managers_launcher_manager_hide_progress (_tmp0_);
#line 226 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp1_ = self->priv->work_timeout_id;
#line 226 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	if (_tmp1_ != ((guint) 0)) {
#line 957 "Tomato.c"
		guint _tmp2_ = 0U;
#line 227 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp2_ = self->priv->work_timeout_id;
#line 227 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		g_source_remove (_tmp2_);
#line 228 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		self->priv->work_timeout_id = (guint) 0;
#line 965 "Tomato.c"
	}
}


static void tomato_tomato_app_stop (TomatoTomatoApp* self) {
#line 232 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	g_return_if_fail (self != NULL);
#line 233 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_stopped = TRUE;
#line 234 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_tomato_app_pause (self);
#line 977 "Tomato.c"
}


static void tomato_tomato_app_set_pause (TomatoTomatoApp* self, gboolean topause) {
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	TomatoWindowMainWindow* _tmp3_ = NULL;
	gboolean _tmp4_ = FALSE;
#line 237 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	g_return_if_fail (self != NULL);
#line 238 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp0_ = topause;
#line 238 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_paused = _tmp0_;
#line 239 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp1_ = tomato_paused;
#line 239 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	if (!_tmp1_) {
#line 996 "Tomato.c"
		gboolean _tmp2_ = FALSE;
#line 240 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp2_ = tomato_paused;
#line 240 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		tomato_stopped = _tmp2_;
#line 1002 "Tomato.c"
	}
#line 241 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp3_ = self->priv->window;
#line 241 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp4_ = topause;
#line 241 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_window_main_window_set_pause (_tmp3_, _tmp4_);
#line 1010 "Tomato.c"
}


static void tomato_tomato_app_update_progress (TomatoTomatoApp* self) {
	TomatoWindowMainWindow* _tmp0_ = NULL;
	TomatoManagersLauncherManager* _tmp1_ = NULL;
#line 244 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	g_return_if_fail (self != NULL);
#line 245 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp0_ = self->priv->window;
#line 245 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_window_main_window_update_progress (_tmp0_);
#line 246 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp1_ = tomato_launcher;
#line 246 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_managers_launcher_manager_update_progress (_tmp1_);
#line 1027 "Tomato.c"
}


static void tomato_tomato_app_next_status (TomatoTomatoApp* self) {
	TomatoWindowMainWindow* _tmp0_ = NULL;
#line 249 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	g_return_if_fail (self != NULL);
#line 250 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp0_ = self->priv->window;
#line 250 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_window_main_window_next_status (_tmp0_, GTK_STACK_TRANSITION_TYPE_NONE);
#line 1039 "Tomato.c"
}


static void _tomato_tomato_app_on_start_clicked_tomato_window_main_window_start_clicked (TomatoWindowMainWindow* _sender, gpointer self) {
#line 254 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_tomato_app_on_start_clicked ((TomatoTomatoApp*) self);
#line 1046 "Tomato.c"
}


static void _tomato_tomato_app_on_resume_clicked_tomato_window_main_window_resume_clicked (TomatoWindowMainWindow* _sender, gpointer self) {
#line 255 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_tomato_app_on_resume_clicked ((TomatoTomatoApp*) self);
#line 1053 "Tomato.c"
}


static void _tomato_tomato_app_on_pause_clicked_tomato_window_main_window_pause_clicked (TomatoWindowMainWindow* _sender, gpointer self) {
#line 256 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_tomato_app_on_pause_clicked ((TomatoTomatoApp*) self);
#line 1060 "Tomato.c"
}


static void _tomato_tomato_app_on_stop_clicked_tomato_window_main_window_stop_clicked (TomatoWindowMainWindow* _sender, gpointer self) {
#line 257 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_tomato_app_on_stop_clicked ((TomatoTomatoApp*) self);
#line 1067 "Tomato.c"
}


static void _tomato_tomato_app_on_skip_clicked_tomato_window_main_window_skip_clicked (TomatoWindowMainWindow* _sender, gpointer self) {
#line 258 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_tomato_app_on_skip_clicked ((TomatoTomatoApp*) self);
#line 1074 "Tomato.c"
}


static void _tomato_tomato_app_on_preferences_clicked_tomato_window_main_window_preferences_clicked (TomatoWindowMainWindow* _sender, gpointer self) {
#line 259 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_tomato_app_on_preferences_clicked ((TomatoTomatoApp*) self);
#line 1081 "Tomato.c"
}


static void _tomato_tomato_app_on_stop_clicked_tomato_tomato_app_paused_on_break (TomatoTomatoApp* _sender, gpointer self) {
#line 260 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_tomato_app_on_stop_clicked ((TomatoTomatoApp*) self);
#line 1088 "Tomato.c"
}


static gboolean __lambda18_ (TomatoTomatoApp* self, GdkEventWindowState* event) {
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	GdkEventWindowState* _tmp1_ = NULL;
	GdkWindowState _tmp2_ = 0;
#line 262 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	g_return_val_if_fail (event != NULL, FALSE);
#line 263 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp1_ = event;
#line 263 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp2_ = _tmp1_->new_window_state;
#line 263 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	if (_tmp2_ != GDK_WINDOW_STATE_FOCUSED) {
#line 1105 "Tomato.c"
		gboolean _tmp3_ = FALSE;
#line 263 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp3_ = tomato_paused;
#line 263 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp0_ = !_tmp3_;
#line 1111 "Tomato.c"
	} else {
#line 263 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp0_ = FALSE;
#line 1115 "Tomato.c"
	}
#line 263 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	if (_tmp0_) {
#line 1119 "Tomato.c"
		TomatoManagersLauncherManager* _tmp4_ = NULL;
#line 264 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp4_ = tomato_launcher;
#line 264 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		tomato_managers_launcher_manager_show_progress (_tmp4_);
#line 1125 "Tomato.c"
	} else {
		TomatoManagersLauncherManager* _tmp5_ = NULL;
#line 266 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp5_ = tomato_launcher;
#line 266 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		tomato_managers_launcher_manager_hide_progress (_tmp5_);
#line 1132 "Tomato.c"
	}
#line 267 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	result = TRUE;
#line 267 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	return result;
#line 1138 "Tomato.c"
}


static gboolean ___lambda18__gtk_widget_window_state_event (GtkWidget* _sender, GdkEventWindowState* event, gpointer self) {
	gboolean result;
	result = __lambda18_ ((TomatoTomatoApp*) self, event);
#line 262 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	return result;
#line 1147 "Tomato.c"
}


static void tomato_tomato_app_connect_signals (TomatoTomatoApp* self) {
	TomatoWindowMainWindow* _tmp0_ = NULL;
	TomatoWindowMainWindow* _tmp1_ = NULL;
	TomatoWindowMainWindow* _tmp2_ = NULL;
	TomatoWindowMainWindow* _tmp3_ = NULL;
	TomatoWindowMainWindow* _tmp4_ = NULL;
	TomatoWindowMainWindow* _tmp5_ = NULL;
	TomatoWindowMainWindow* _tmp6_ = NULL;
#line 253 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	g_return_if_fail (self != NULL);
#line 254 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp0_ = self->priv->window;
#line 254 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	g_signal_connect_object (_tmp0_, "start-clicked", (GCallback) _tomato_tomato_app_on_start_clicked_tomato_window_main_window_start_clicked, self, 0);
#line 255 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp1_ = self->priv->window;
#line 255 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	g_signal_connect_object (_tmp1_, "resume-clicked", (GCallback) _tomato_tomato_app_on_resume_clicked_tomato_window_main_window_resume_clicked, self, 0);
#line 256 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp2_ = self->priv->window;
#line 256 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	g_signal_connect_object (_tmp2_, "pause-clicked", (GCallback) _tomato_tomato_app_on_pause_clicked_tomato_window_main_window_pause_clicked, self, 0);
#line 257 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp3_ = self->priv->window;
#line 257 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	g_signal_connect_object (_tmp3_, "stop-clicked", (GCallback) _tomato_tomato_app_on_stop_clicked_tomato_window_main_window_stop_clicked, self, 0);
#line 258 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp4_ = self->priv->window;
#line 258 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	g_signal_connect_object (_tmp4_, "skip-clicked", (GCallback) _tomato_tomato_app_on_skip_clicked_tomato_window_main_window_skip_clicked, self, 0);
#line 259 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp5_ = self->priv->window;
#line 259 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	g_signal_connect_object (_tmp5_, "preferences-clicked", (GCallback) _tomato_tomato_app_on_preferences_clicked_tomato_window_main_window_preferences_clicked, self, 0);
#line 260 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	g_signal_connect_object (self, "paused-on-break", (GCallback) _tomato_tomato_app_on_stop_clicked_tomato_tomato_app_paused_on_break, self, 0);
#line 262 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp6_ = self->priv->window;
#line 262 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	g_signal_connect_object ((GtkWidget*) _tmp6_, "window-state-event", (GCallback) ___lambda18__gtk_widget_window_state_event, self, 0);
#line 1191 "Tomato.c"
}


static void __lambda12_ (TomatoTomatoApp* self) {
	TomatoServicesSavedState* _tmp0_ = NULL;
	TomatoStatus _tmp1_ = 0;
	TomatoStatus _tmp2_ = 0;
	TomatoWindowPreferencesDialog* _tmp5_ = NULL;
#line 274 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp0_ = tomato_saved;
#line 274 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp1_ = tomato_services_saved_state_get_status (_tmp0_);
#line 274 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp2_ = _tmp1_;
#line 274 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	if (_tmp2_ == TOMATO_STATUS_START) {
#line 1208 "Tomato.c"
		TomatoManagersWorkManager* _tmp3_ = NULL;
		TomatoWindowMainWindow* _tmp4_ = NULL;
#line 275 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp3_ = tomato_work;
#line 275 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		tomato_managers_work_manager_reset_countdown (_tmp3_);
#line 276 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		_tmp4_ = self->priv->window;
#line 276 "/home/lamm/Projetos/tomato/src/Tomato.vala"
		tomato_window_main_window_update_progress (_tmp4_);
#line 1219 "Tomato.c"
	}
#line 278 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp5_ = self->priv->pref_window;
#line 278 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_window_preferences_dialog_update_timing_sensitivity (_tmp5_);
#line 279 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	g_message ("Tomato.vala:279: Pomodoro scale changed");
#line 1227 "Tomato.c"
}


static void ___lambda12__tomato_window_preferences_dialog_pomodoro_changed (TomatoWindowPreferencesDialog* _sender, gpointer self) {
#line 273 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	__lambda12_ ((TomatoTomatoApp*) self);
#line 1234 "Tomato.c"
}


static void __lambda13_ (TomatoTomatoApp* self) {
	TomatoWindowPreferencesDialog* _tmp0_ = NULL;
#line 283 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp0_ = self->priv->pref_window;
#line 283 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_window_preferences_dialog_update_timing_sensitivity (_tmp0_);
#line 284 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	g_message ("Tomato.vala:284: Short break scale changed");
#line 1246 "Tomato.c"
}


static void ___lambda13__tomato_window_preferences_dialog_short_break_changed (TomatoWindowPreferencesDialog* _sender, gpointer self) {
#line 282 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	__lambda13_ ((TomatoTomatoApp*) self);
#line 1253 "Tomato.c"
}


static void __lambda14_ (TomatoTomatoApp* self) {
	TomatoWindowPreferencesDialog* _tmp0_ = NULL;
#line 288 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp0_ = self->priv->pref_window;
#line 288 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_window_preferences_dialog_update_timing_sensitivity (_tmp0_);
#line 289 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	g_message ("Tomato.vala:289: Long break scale changed");
#line 1265 "Tomato.c"
}


static void ___lambda14__tomato_window_preferences_dialog_long_break_changed (TomatoWindowPreferencesDialog* _sender, gpointer self) {
#line 287 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	__lambda14_ ((TomatoTomatoApp*) self);
#line 1272 "Tomato.c"
}


static void __lambda15_ (TomatoTomatoApp* self) {
	TomatoWindowPreferencesDialog* _tmp0_ = NULL;
#line 293 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp0_ = self->priv->pref_window;
#line 293 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_window_preferences_dialog_update_timing_sensitivity (_tmp0_);
#line 1282 "Tomato.c"
}


static void ___lambda15__tomato_window_preferences_dialog_long_break_delay_changed (TomatoWindowPreferencesDialog* _sender, gpointer self) {
#line 292 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	__lambda15_ ((TomatoTomatoApp*) self);
#line 1289 "Tomato.c"
}


static void __lambda16_ (TomatoTomatoApp* self) {
	TomatoWindowPreferencesDialog* _tmp0_ = NULL;
	TomatoWindowPreferencesDialog* _tmp1_ = NULL;
#line 298 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp0_ = self->priv->pref_window;
#line 298 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_window_preferences_dialog_update_timing_sensitivity (_tmp0_);
#line 299 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp1_ = self->priv->pref_window;
#line 299 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_window_preferences_dialog_update_work_sensitivity (_tmp1_);
#line 1304 "Tomato.c"
}


static void ___lambda16__granite_services_settings_changed (GraniteServicesSettings* _sender, gpointer self) {
#line 297 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	__lambda16_ ((TomatoTomatoApp*) self);
#line 1311 "Tomato.c"
}


static void __lambda17_ (TomatoTomatoApp* self) {
	TomatoManagersWorkManager* _tmp0_ = NULL;
	TomatoWindowPreferencesDialog* _tmp1_ = NULL;
#line 304 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp0_ = tomato_work;
#line 304 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_managers_work_manager_reset (_tmp0_);
#line 305 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_tomato_app_on_stop_clicked (self);
#line 306 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp1_ = self->priv->pref_window;
#line 306 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_window_preferences_dialog_update_work_sensitivity (_tmp1_);
#line 1328 "Tomato.c"
}


static void ___lambda17__tomato_window_preferences_dialog_reset_work_clicked (TomatoWindowPreferencesDialog* _sender, gpointer self) {
#line 303 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	__lambda17_ ((TomatoTomatoApp*) self);
#line 1335 "Tomato.c"
}


static void tomato_tomato_app_connect_pref_signals (TomatoTomatoApp* self) {
	TomatoWindowPreferencesDialog* _tmp0_ = NULL;
	TomatoWindowPreferencesDialog* _tmp1_ = NULL;
	TomatoWindowPreferencesDialog* _tmp2_ = NULL;
	TomatoWindowPreferencesDialog* _tmp3_ = NULL;
	TomatoServicesPreferences* _tmp4_ = NULL;
	TomatoWindowPreferencesDialog* _tmp5_ = NULL;
#line 271 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	g_return_if_fail (self != NULL);
#line 273 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp0_ = self->priv->pref_window;
#line 273 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	g_signal_connect_object (_tmp0_, "pomodoro-changed", (GCallback) ___lambda12__tomato_window_preferences_dialog_pomodoro_changed, self, 0);
#line 282 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp1_ = self->priv->pref_window;
#line 282 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	g_signal_connect_object (_tmp1_, "short-break-changed", (GCallback) ___lambda13__tomato_window_preferences_dialog_short_break_changed, self, 0);
#line 287 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp2_ = self->priv->pref_window;
#line 287 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	g_signal_connect_object (_tmp2_, "long-break-changed", (GCallback) ___lambda14__tomato_window_preferences_dialog_long_break_changed, self, 0);
#line 292 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp3_ = self->priv->pref_window;
#line 292 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	g_signal_connect_object (_tmp3_, "long-break-delay-changed", (GCallback) ___lambda15__tomato_window_preferences_dialog_long_break_delay_changed, self, 0);
#line 297 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp4_ = tomato_preferences;
#line 297 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	g_signal_connect_object ((GraniteServicesSettings*) _tmp4_, "changed", (GCallback) ___lambda16__granite_services_settings_changed, self, 0);
#line 303 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp5_ = self->priv->pref_window;
#line 303 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	g_signal_connect_object (_tmp5_, "reset-work-clicked", (GCallback) ___lambda17__tomato_window_preferences_dialog_reset_work_clicked, self, 0);
#line 1372 "Tomato.c"
}


static GObject * tomato_tomato_app_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	TomatoTomatoApp * self;
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	gchar* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	gchar** _tmp12_ = NULL;
	gchar* _tmp13_ = NULL;
	gchar* _tmp14_ = NULL;
	gchar** _tmp15_ = NULL;
	gchar* _tmp16_ = NULL;
#line 57 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	parent_class = G_OBJECT_CLASS (tomato_tomato_app_parent_class);
#line 57 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 57 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TOMATO_TYPE_TOMATO_APP, TomatoTomatoApp);
#line 58 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp0_ = g_strdup (CONSTANTS_APP_NAME);
#line 58 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_g_free0 (((GraniteApplication*) self)->program_name);
#line 58 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	((GraniteApplication*) self)->program_name = _tmp0_;
#line 59 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp1_ = g_strdup (CONSTANTS_EXEC_NAME);
#line 59 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_g_free0 (((GraniteApplication*) self)->exec_name);
#line 59 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	((GraniteApplication*) self)->exec_name = _tmp1_;
#line 60 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp2_ = g_strdup (CONSTANTS_VERSION);
#line 60 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_g_free0 (((GraniteApplication*) self)->build_version);
#line 60 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	((GraniteApplication*) self)->build_version = _tmp2_;
#line 62 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp3_ = g_strdup ("2017");
#line 62 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_g_free0 (((GraniteApplication*) self)->app_years);
#line 62 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	((GraniteApplication*) self)->app_years = _tmp3_;
#line 63 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp4_ = g_strdup (CONSTANTS_ICON_NAME);
#line 63 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_g_free0 (((GraniteApplication*) self)->app_icon);
#line 63 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	((GraniteApplication*) self)->app_icon = _tmp4_;
#line 64 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp5_ = g_strdup ("com.github.luizaugustomm.tomato.desktop");
#line 64 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_g_free0 (((GraniteApplication*) self)->app_launcher);
#line 64 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	((GraniteApplication*) self)->app_launcher = _tmp5_;
#line 65 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	g_application_set_application_id ((GApplication*) self, "com.github.luizaugustomm.tomato");
#line 67 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp6_ = g_strdup ("http://launchpad.net/tomatoapp");
#line 67 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_g_free0 (((GraniteApplication*) self)->main_url);
#line 67 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	((GraniteApplication*) self)->main_url = _tmp6_;
#line 68 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp7_ = g_strdup ("http://bugs.launchpad.net/tomatoapp");
#line 68 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_g_free0 (((GraniteApplication*) self)->bug_url);
#line 68 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	((GraniteApplication*) self)->bug_url = _tmp7_;
#line 69 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp8_ = g_strdup ("http://answers.launchpad.net/tomatoapp");
#line 69 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_g_free0 (((GraniteApplication*) self)->help_url);
#line 69 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	((GraniteApplication*) self)->help_url = _tmp8_;
#line 70 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp9_ = g_strdup ("http://translations.launchpad.net/tomatoapp");
#line 70 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_g_free0 (((GraniteApplication*) self)->translate_url);
#line 70 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	((GraniteApplication*) self)->translate_url = _tmp9_;
#line 72 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp10_ = g_strdup ("Luiz Augusto Morais <luizaugustomm@gmail.com>");
#line 72 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp11_ = g_strdup ("Sam Thomas <sgpthomas@gmail.com>");
#line 72 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp12_ = g_new0 (gchar*, 2 + 1);
#line 72 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp12_[0] = _tmp10_;
#line 72 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp12_[1] = _tmp11_;
#line 72 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	((GraniteApplication*) self)->about_authors = (_vala_array_free (((GraniteApplication*) self)->about_authors, ((GraniteApplication*) self)->about_authors_length1, (GDestroyNotify) g_free), NULL);
#line 72 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	((GraniteApplication*) self)->about_authors = _tmp12_;
#line 72 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	((GraniteApplication*) self)->about_authors_length1 = 2;
#line 74 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	((GraniteApplication*) self)->about_license_type = GTK_LICENSE_GPL_3_0;
#line 75 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp13_ = g_strdup ("Luiz Augusto Morais <luizaugustomm@gmail.com>");
#line 75 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp14_ = g_strdup ("Sam Thomas <sgpthomas@gmail.com>");
#line 75 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp15_ = g_new0 (gchar*, 2 + 1);
#line 75 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp15_[0] = _tmp13_;
#line 75 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp15_[1] = _tmp14_;
#line 75 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	((GraniteApplication*) self)->about_artists = (_vala_array_free (((GraniteApplication*) self)->about_artists, ((GraniteApplication*) self)->about_artists_length1, (GDestroyNotify) g_free), NULL);
#line 75 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	((GraniteApplication*) self)->about_artists = _tmp15_;
#line 75 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	((GraniteApplication*) self)->about_artists_length1 = 2;
#line 77 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp16_ = g_strdup ("Launchpad Translators");
#line 77 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_g_free0 (((GraniteApplication*) self)->about_translators);
#line 77 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	((GraniteApplication*) self)->about_translators = _tmp16_;
#line 57 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	return obj;
#line 1507 "Tomato.c"
}


static void tomato_tomato_app_class_init (TomatoTomatoAppClass * klass) {
#line 55 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_tomato_app_parent_class = g_type_class_peek_parent (klass);
#line 55 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	g_type_class_add_private (klass, sizeof (TomatoTomatoAppPrivate));
#line 55 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	((GApplicationClass *) klass)->activate = (void (*)(GApplication*)) tomato_tomato_app_real_activate;
#line 55 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	G_OBJECT_CLASS (klass)->constructor = tomato_tomato_app_constructor;
#line 55 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	G_OBJECT_CLASS (klass)->finalize = tomato_tomato_app_finalize;
#line 55 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	g_signal_new ("paused_on_break", TOMATO_TYPE_TOMATO_APP, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
#line 1524 "Tomato.c"
}


static void tomato_tomato_app_instance_init (TomatoTomatoApp * self) {
#line 55 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	self->priv = TOMATO_TOMATO_APP_GET_PRIVATE (self);
#line 86 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	self->priv->work_timeout_id = (guint) 0;
#line 87 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	self->priv->stop_timeout_id = (guint) 0;
#line 1535 "Tomato.c"
}


static void tomato_tomato_app_finalize (GObject* obj) {
	TomatoTomatoApp * self;
#line 55 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TOMATO_TYPE_TOMATO_APP, TomatoTomatoApp);
#line 82 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_g_object_unref0 (self->priv->window);
#line 83 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_g_object_unref0 (self->priv->pref_window);
#line 55 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	G_OBJECT_CLASS (tomato_tomato_app_parent_class)->finalize (obj);
#line 1549 "Tomato.c"
}


GType tomato_tomato_app_get_type (void) {
	static volatile gsize tomato_tomato_app_type_id__volatile = 0;
	if (g_once_init_enter (&tomato_tomato_app_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (TomatoTomatoAppClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) tomato_tomato_app_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TomatoTomatoApp), 0, (GInstanceInitFunc) tomato_tomato_app_instance_init, NULL };
		GType tomato_tomato_app_type_id;
		tomato_tomato_app_type_id = g_type_register_static (GRANITE_TYPE_APPLICATION, "TomatoTomatoApp", &g_define_type_info, 0);
		g_once_init_leave (&tomato_tomato_app_type_id__volatile, tomato_tomato_app_type_id);
	}
	return tomato_tomato_app_type_id__volatile;
}


void tomato_main (gchar** args, int args_length1) {
	TomatoTomatoApp* app = NULL;
	TomatoTomatoApp* _tmp0_ = NULL;
	gchar** _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
#line 312 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	gtk_init (&args_length1, &args);
#line 314 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp0_ = tomato_tomato_app_new ();
#line 314 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	app = _tmp0_;
#line 315 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp1_ = args;
#line 315 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_tmp1__length1 = args_length1;
#line 315 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	granite_application_run ((GraniteApplication*) app, _tmp1_, _tmp1__length1);
#line 311 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	_g_object_unref0 (app);
#line 1584 "Tomato.c"
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
#line 311 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	tomato_main (argv, argc);
#line 311 "/home/lamm/Projetos/tomato/src/Tomato.vala"
	return 0;
#line 1596 "Tomato.c"
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



