/* LauncherManager.c generated by valac 0.34.7, the Vala compiler
 * generated from LauncherManager.vala, do not modify */

/* Copyright 2015 LuizAugustoMorais
*
* This file is part of Tomato.
*
* Tomato is free software: you can redistribute it
* and/or modify it under the terms of the GNU General Public License as
* published by the Free Software Foundation, either version 3 of the
* License, or (at your option) any later version.
*
* Tomato is distributed in the hope that it will be
* useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
* Public License for more details.
*
* You should have received a copy of the GNU General Public License along
* with Tomato. If not, see http://www.gnu.org/licenses/.
*/

#include <glib.h>
#include <glib-object.h>
#include <unity.h>
#include <float.h>
#include <math.h>
#include <granite.h>
#include <gobject/gvaluecollector.h>


#define TOMATO_MANAGERS_TYPE_LAUNCHER_MANAGER (tomato_managers_launcher_manager_get_type ())
#define TOMATO_MANAGERS_LAUNCHER_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TOMATO_MANAGERS_TYPE_LAUNCHER_MANAGER, TomatoManagersLauncherManager))
#define TOMATO_MANAGERS_LAUNCHER_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TOMATO_MANAGERS_TYPE_LAUNCHER_MANAGER, TomatoManagersLauncherManagerClass))
#define TOMATO_MANAGERS_IS_LAUNCHER_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TOMATO_MANAGERS_TYPE_LAUNCHER_MANAGER))
#define TOMATO_MANAGERS_IS_LAUNCHER_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TOMATO_MANAGERS_TYPE_LAUNCHER_MANAGER))
#define TOMATO_MANAGERS_LAUNCHER_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TOMATO_MANAGERS_TYPE_LAUNCHER_MANAGER, TomatoManagersLauncherManagerClass))

typedef struct _TomatoManagersLauncherManager TomatoManagersLauncherManager;
typedef struct _TomatoManagersLauncherManagerClass TomatoManagersLauncherManagerClass;
typedef struct _TomatoManagersLauncherManagerPrivate TomatoManagersLauncherManagerPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define TOMATO_SERVICES_TYPE_SAVED_STATE (tomato_services_saved_state_get_type ())
#define TOMATO_SERVICES_SAVED_STATE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TOMATO_SERVICES_TYPE_SAVED_STATE, TomatoServicesSavedState))
#define TOMATO_SERVICES_SAVED_STATE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TOMATO_SERVICES_TYPE_SAVED_STATE, TomatoServicesSavedStateClass))
#define TOMATO_SERVICES_IS_SAVED_STATE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TOMATO_SERVICES_TYPE_SAVED_STATE))
#define TOMATO_SERVICES_IS_SAVED_STATE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TOMATO_SERVICES_TYPE_SAVED_STATE))
#define TOMATO_SERVICES_SAVED_STATE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TOMATO_SERVICES_TYPE_SAVED_STATE, TomatoServicesSavedStateClass))

typedef struct _TomatoServicesSavedState TomatoServicesSavedState;
typedef struct _TomatoServicesSavedStateClass TomatoServicesSavedStateClass;

#define TOMATO_TYPE_STATUS (tomato_status_get_type ())

#define TOMATO_SERVICES_TYPE_SETTINGS (tomato_services_settings_get_type ())
#define TOMATO_SERVICES_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TOMATO_SERVICES_TYPE_SETTINGS, TomatoServicesSettings))
#define TOMATO_SERVICES_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TOMATO_SERVICES_TYPE_SETTINGS, TomatoServicesSettingsClass))
#define TOMATO_SERVICES_IS_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TOMATO_SERVICES_TYPE_SETTINGS))
#define TOMATO_SERVICES_IS_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TOMATO_SERVICES_TYPE_SETTINGS))
#define TOMATO_SERVICES_SETTINGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TOMATO_SERVICES_TYPE_SETTINGS, TomatoServicesSettingsClass))

typedef struct _TomatoServicesSettings TomatoServicesSettings;
typedef struct _TomatoServicesSettingsClass TomatoServicesSettingsClass;

#define TOMATO_MANAGERS_TYPE_WORK_MANAGER (tomato_managers_work_manager_get_type ())
#define TOMATO_MANAGERS_WORK_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TOMATO_MANAGERS_TYPE_WORK_MANAGER, TomatoManagersWorkManager))
#define TOMATO_MANAGERS_WORK_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TOMATO_MANAGERS_TYPE_WORK_MANAGER, TomatoManagersWorkManagerClass))
#define TOMATO_MANAGERS_IS_WORK_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TOMATO_MANAGERS_TYPE_WORK_MANAGER))
#define TOMATO_MANAGERS_IS_WORK_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TOMATO_MANAGERS_TYPE_WORK_MANAGER))
#define TOMATO_MANAGERS_WORK_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TOMATO_MANAGERS_TYPE_WORK_MANAGER, TomatoManagersWorkManagerClass))

typedef struct _TomatoManagersWorkManager TomatoManagersWorkManager;
typedef struct _TomatoManagersWorkManagerClass TomatoManagersWorkManagerClass;
typedef struct _TomatoManagersParamSpecLauncherManager TomatoManagersParamSpecLauncherManager;

struct _TomatoManagersLauncherManager {
	GTypeInstance parent_instance;
	volatile int ref_count;
	TomatoManagersLauncherManagerPrivate * priv;
};

struct _TomatoManagersLauncherManagerClass {
	GTypeClass parent_class;
	void (*finalize) (TomatoManagersLauncherManager *self);
};

struct _TomatoManagersLauncherManagerPrivate {
	UnityLauncherEntry* launcher;
};

typedef enum  {
	TOMATO_STATUS_START,
	TOMATO_STATUS_POMODORO,
	TOMATO_STATUS_SHORT_BREAK,
	TOMATO_STATUS_LONG_BREAK
} TomatoStatus;

struct _TomatoManagersParamSpecLauncherManager {
	GParamSpec parent_instance;
};


static gpointer tomato_managers_launcher_manager_parent_class = NULL;
extern TomatoServicesSavedState* tomato_saved;
extern TomatoServicesSettings* tomato_settings;
extern TomatoManagersWorkManager* tomato_work;

gpointer tomato_managers_launcher_manager_ref (gpointer instance);
void tomato_managers_launcher_manager_unref (gpointer instance);
GParamSpec* tomato_managers_param_spec_launcher_manager (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void tomato_managers_value_set_launcher_manager (GValue* value, gpointer v_object);
void tomato_managers_value_take_launcher_manager (GValue* value, gpointer v_object);
gpointer tomato_managers_value_get_launcher_manager (const GValue* value);
GType tomato_managers_launcher_manager_get_type (void) G_GNUC_CONST;
#define TOMATO_MANAGERS_LAUNCHER_MANAGER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TOMATO_MANAGERS_TYPE_LAUNCHER_MANAGER, TomatoManagersLauncherManagerPrivate))
enum  {
	TOMATO_MANAGERS_LAUNCHER_MANAGER_DUMMY_PROPERTY
};
TomatoManagersLauncherManager* tomato_managers_launcher_manager_new (void);
TomatoManagersLauncherManager* tomato_managers_launcher_manager_construct (GType object_type);
void tomato_managers_launcher_manager_update_progress (TomatoManagersLauncherManager* self);
GType tomato_services_saved_state_get_type (void) G_GNUC_CONST;
GType tomato_status_get_type (void) G_GNUC_CONST;
TomatoStatus tomato_services_saved_state_get_status (TomatoServicesSavedState* self);
GType tomato_services_settings_get_type (void) G_GNUC_CONST;
gint tomato_services_settings_get_short_break_duration (TomatoServicesSettings* self);
gint tomato_services_settings_get_long_break_duration (TomatoServicesSettings* self);
gint tomato_services_settings_get_pomodoro_duration (TomatoServicesSettings* self);
gpointer tomato_managers_work_manager_ref (gpointer instance);
void tomato_managers_work_manager_unref (gpointer instance);
GParamSpec* tomato_managers_param_spec_work_manager (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void tomato_managers_value_set_work_manager (GValue* value, gpointer v_object);
void tomato_managers_value_take_work_manager (GValue* value, gpointer v_object);
gpointer tomato_managers_value_get_work_manager (const GValue* value);
GType tomato_managers_work_manager_get_type (void) G_GNUC_CONST;
gint tomato_managers_work_manager_raw_countdown (TomatoManagersWorkManager* self);
gboolean tomato_managers_launcher_manager_has_progress (TomatoManagersLauncherManager* self);
void tomato_managers_launcher_manager_show_progress (TomatoManagersLauncherManager* self);
void tomato_managers_launcher_manager_hide_progress (TomatoManagersLauncherManager* self);
static void tomato_managers_launcher_manager_finalize (TomatoManagersLauncherManager* obj);


TomatoManagersLauncherManager* tomato_managers_launcher_manager_construct (GType object_type) {
	TomatoManagersLauncherManager* self = NULL;
	UnityLauncherEntry* _tmp0_ = NULL;
#line 25 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	self = (TomatoManagersLauncherManager*) g_type_create_instance (object_type);
#line 26 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	_tmp0_ = unity_launcher_entry_get_for_desktop_id ("com.github.luizaugustomm.tomato.desktop");
#line 26 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	_g_object_unref0 (self->priv->launcher);
#line 26 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	self->priv->launcher = _tmp0_;
#line 27 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	tomato_managers_launcher_manager_update_progress (self);
#line 25 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	return self;
#line 159 "LauncherManager.c"
}


TomatoManagersLauncherManager* tomato_managers_launcher_manager_new (void) {
#line 25 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	return tomato_managers_launcher_manager_construct (TOMATO_MANAGERS_TYPE_LAUNCHER_MANAGER);
#line 166 "LauncherManager.c"
}


void tomato_managers_launcher_manager_update_progress (TomatoManagersLauncherManager* self) {
	gdouble duration = 0.0;
	TomatoServicesSavedState* _tmp0_ = NULL;
	TomatoStatus _tmp1_ = 0;
	TomatoStatus _tmp2_ = 0;
	UnityLauncherEntry* _tmp15_ = NULL;
	TomatoManagersWorkManager* _tmp16_ = NULL;
	gint _tmp17_ = 0;
	gdouble _tmp18_ = 0.0;
#line 31 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	g_return_if_fail (self != NULL);
#line 33 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	_tmp0_ = tomato_saved;
#line 33 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	_tmp1_ = tomato_services_saved_state_get_status (_tmp0_);
#line 33 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	_tmp2_ = _tmp1_;
#line 33 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	if (_tmp2_ == TOMATO_STATUS_SHORT_BREAK) {
#line 189 "LauncherManager.c"
		TomatoServicesSettings* _tmp3_ = NULL;
		gint _tmp4_ = 0;
		gint _tmp5_ = 0;
#line 34 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
		_tmp3_ = tomato_settings;
#line 34 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
		_tmp4_ = tomato_services_settings_get_short_break_duration (_tmp3_);
#line 34 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
		_tmp5_ = _tmp4_;
#line 34 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
		duration = _tmp5_ * 60.0;
#line 201 "LauncherManager.c"
	} else {
		TomatoServicesSavedState* _tmp6_ = NULL;
		TomatoStatus _tmp7_ = 0;
		TomatoStatus _tmp8_ = 0;
#line 36 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
		_tmp6_ = tomato_saved;
#line 36 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
		_tmp7_ = tomato_services_saved_state_get_status (_tmp6_);
#line 36 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
		_tmp8_ = _tmp7_;
#line 36 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
		if (_tmp8_ == TOMATO_STATUS_LONG_BREAK) {
#line 214 "LauncherManager.c"
			TomatoServicesSettings* _tmp9_ = NULL;
			gint _tmp10_ = 0;
			gint _tmp11_ = 0;
#line 37 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
			_tmp9_ = tomato_settings;
#line 37 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
			_tmp10_ = tomato_services_settings_get_long_break_duration (_tmp9_);
#line 37 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
			_tmp11_ = _tmp10_;
#line 37 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
			duration = _tmp11_ * 60.0;
#line 226 "LauncherManager.c"
		} else {
			TomatoServicesSettings* _tmp12_ = NULL;
			gint _tmp13_ = 0;
			gint _tmp14_ = 0;
#line 40 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
			_tmp12_ = tomato_settings;
#line 40 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
			_tmp13_ = tomato_services_settings_get_pomodoro_duration (_tmp12_);
#line 40 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
			_tmp14_ = _tmp13_;
#line 40 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
			duration = _tmp14_ * 60.0;
#line 239 "LauncherManager.c"
		}
	}
#line 43 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	_tmp15_ = self->priv->launcher;
#line 43 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	_tmp16_ = tomato_work;
#line 43 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	_tmp17_ = tomato_managers_work_manager_raw_countdown (_tmp16_);
#line 43 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	_tmp18_ = duration;
#line 43 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	unity_launcher_entry_set_progress (_tmp15_, 1 - (_tmp17_ / _tmp18_));
#line 252 "LauncherManager.c"
}


gboolean tomato_managers_launcher_manager_has_progress (TomatoManagersLauncherManager* self) {
	gboolean result = FALSE;
	UnityLauncherEntry* _tmp0_ = NULL;
	gdouble _tmp1_ = 0.0;
	gdouble _tmp2_ = 0.0;
#line 46 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 47 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	_tmp0_ = self->priv->launcher;
#line 47 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	_tmp1_ = unity_launcher_entry_get_progress (_tmp0_);
#line 47 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	_tmp2_ = _tmp1_;
#line 47 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	result = _tmp2_ != ((gdouble) 0);
#line 47 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	return result;
#line 273 "LauncherManager.c"
}


void tomato_managers_launcher_manager_show_progress (TomatoManagersLauncherManager* self) {
	UnityLauncherEntry* _tmp0_ = NULL;
#line 50 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	g_return_if_fail (self != NULL);
#line 51 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	_tmp0_ = self->priv->launcher;
#line 51 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	unity_launcher_entry_set_progress_visible (_tmp0_, TRUE);
#line 285 "LauncherManager.c"
}


void tomato_managers_launcher_manager_hide_progress (TomatoManagersLauncherManager* self) {
	UnityLauncherEntry* _tmp0_ = NULL;
#line 54 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	g_return_if_fail (self != NULL);
#line 55 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	_tmp0_ = self->priv->launcher;
#line 55 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	unity_launcher_entry_set_progress_visible (_tmp0_, FALSE);
#line 297 "LauncherManager.c"
}


static void tomato_managers_value_launcher_manager_init (GValue* value) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	value->data[0].v_pointer = NULL;
#line 304 "LauncherManager.c"
}


static void tomato_managers_value_launcher_manager_free_value (GValue* value) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	if (value->data[0].v_pointer) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
		tomato_managers_launcher_manager_unref (value->data[0].v_pointer);
#line 313 "LauncherManager.c"
	}
}


static void tomato_managers_value_launcher_manager_copy_value (const GValue* src_value, GValue* dest_value) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	if (src_value->data[0].v_pointer) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
		dest_value->data[0].v_pointer = tomato_managers_launcher_manager_ref (src_value->data[0].v_pointer);
#line 323 "LauncherManager.c"
	} else {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
		dest_value->data[0].v_pointer = NULL;
#line 327 "LauncherManager.c"
	}
}


static gpointer tomato_managers_value_launcher_manager_peek_pointer (const GValue* value) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	return value->data[0].v_pointer;
#line 335 "LauncherManager.c"
}


static gchar* tomato_managers_value_launcher_manager_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	if (collect_values[0].v_pointer) {
#line 342 "LauncherManager.c"
		TomatoManagersLauncherManager* object;
		object = collect_values[0].v_pointer;
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
		if (object->parent_instance.g_class == NULL) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 349 "LauncherManager.c"
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 353 "LauncherManager.c"
		}
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
		value->data[0].v_pointer = tomato_managers_launcher_manager_ref (object);
#line 357 "LauncherManager.c"
	} else {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
		value->data[0].v_pointer = NULL;
#line 361 "LauncherManager.c"
	}
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	return NULL;
#line 365 "LauncherManager.c"
}


static gchar* tomato_managers_value_launcher_manager_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	TomatoManagersLauncherManager** object_p;
	object_p = collect_values[0].v_pointer;
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	if (!object_p) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
#line 376 "LauncherManager.c"
	}
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	if (!value->data[0].v_pointer) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
		*object_p = NULL;
#line 382 "LauncherManager.c"
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
		*object_p = value->data[0].v_pointer;
#line 386 "LauncherManager.c"
	} else {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
		*object_p = tomato_managers_launcher_manager_ref (value->data[0].v_pointer);
#line 390 "LauncherManager.c"
	}
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	return NULL;
#line 394 "LauncherManager.c"
}


GParamSpec* tomato_managers_param_spec_launcher_manager (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	TomatoManagersParamSpecLauncherManager* spec;
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	g_return_val_if_fail (g_type_is_a (object_type, TOMATO_MANAGERS_TYPE_LAUNCHER_MANAGER), NULL);
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	G_PARAM_SPEC (spec)->value_type = object_type;
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	return G_PARAM_SPEC (spec);
#line 408 "LauncherManager.c"
}


gpointer tomato_managers_value_get_launcher_manager (const GValue* value) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TOMATO_MANAGERS_TYPE_LAUNCHER_MANAGER), NULL);
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	return value->data[0].v_pointer;
#line 417 "LauncherManager.c"
}


void tomato_managers_value_set_launcher_manager (GValue* value, gpointer v_object) {
	TomatoManagersLauncherManager* old;
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TOMATO_MANAGERS_TYPE_LAUNCHER_MANAGER));
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	old = value->data[0].v_pointer;
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	if (v_object) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TOMATO_MANAGERS_TYPE_LAUNCHER_MANAGER));
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
		value->data[0].v_pointer = v_object;
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
		tomato_managers_launcher_manager_ref (value->data[0].v_pointer);
#line 437 "LauncherManager.c"
	} else {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
		value->data[0].v_pointer = NULL;
#line 441 "LauncherManager.c"
	}
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	if (old) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
		tomato_managers_launcher_manager_unref (old);
#line 447 "LauncherManager.c"
	}
}


void tomato_managers_value_take_launcher_manager (GValue* value, gpointer v_object) {
	TomatoManagersLauncherManager* old;
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TOMATO_MANAGERS_TYPE_LAUNCHER_MANAGER));
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	old = value->data[0].v_pointer;
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	if (v_object) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TOMATO_MANAGERS_TYPE_LAUNCHER_MANAGER));
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
		value->data[0].v_pointer = v_object;
#line 466 "LauncherManager.c"
	} else {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
		value->data[0].v_pointer = NULL;
#line 470 "LauncherManager.c"
	}
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	if (old) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
		tomato_managers_launcher_manager_unref (old);
#line 476 "LauncherManager.c"
	}
}


static void tomato_managers_launcher_manager_class_init (TomatoManagersLauncherManagerClass * klass) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	tomato_managers_launcher_manager_parent_class = g_type_class_peek_parent (klass);
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	((TomatoManagersLauncherManagerClass *) klass)->finalize = tomato_managers_launcher_manager_finalize;
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	g_type_class_add_private (klass, sizeof (TomatoManagersLauncherManagerPrivate));
#line 488 "LauncherManager.c"
}


static void tomato_managers_launcher_manager_instance_init (TomatoManagersLauncherManager * self) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	self->priv = TOMATO_MANAGERS_LAUNCHER_MANAGER_GET_PRIVATE (self);
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	self->ref_count = 1;
#line 497 "LauncherManager.c"
}


static void tomato_managers_launcher_manager_finalize (TomatoManagersLauncherManager* obj) {
	TomatoManagersLauncherManager * self;
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TOMATO_MANAGERS_TYPE_LAUNCHER_MANAGER, TomatoManagersLauncherManager);
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	g_signal_handlers_destroy (self);
#line 23 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	_g_object_unref0 (self->priv->launcher);
#line 509 "LauncherManager.c"
}


GType tomato_managers_launcher_manager_get_type (void) {
	static volatile gsize tomato_managers_launcher_manager_type_id__volatile = 0;
	if (g_once_init_enter (&tomato_managers_launcher_manager_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { tomato_managers_value_launcher_manager_init, tomato_managers_value_launcher_manager_free_value, tomato_managers_value_launcher_manager_copy_value, tomato_managers_value_launcher_manager_peek_pointer, "p", tomato_managers_value_launcher_manager_collect_value, "p", tomato_managers_value_launcher_manager_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (TomatoManagersLauncherManagerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) tomato_managers_launcher_manager_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TomatoManagersLauncherManager), 0, (GInstanceInitFunc) tomato_managers_launcher_manager_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType tomato_managers_launcher_manager_type_id;
		tomato_managers_launcher_manager_type_id = g_type_register_fundamental (g_type_fundamental_next (), "TomatoManagersLauncherManager", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&tomato_managers_launcher_manager_type_id__volatile, tomato_managers_launcher_manager_type_id);
	}
	return tomato_managers_launcher_manager_type_id__volatile;
}


gpointer tomato_managers_launcher_manager_ref (gpointer instance) {
	TomatoManagersLauncherManager* self;
	self = instance;
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	g_atomic_int_inc (&self->ref_count);
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	return instance;
#line 534 "LauncherManager.c"
}


void tomato_managers_launcher_manager_unref (gpointer instance) {
	TomatoManagersLauncherManager* self;
	self = instance;
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
		TOMATO_MANAGERS_LAUNCHER_MANAGER_GET_CLASS (self)->finalize (self);
#line 21 "/home/lamm/Projetos/tomato/src/Managers/LauncherManager.vala"
		g_type_free_instance ((GTypeInstance *) self);
#line 547 "LauncherManager.c"
	}
}



