/* NotificationManager.c generated by valac 0.34.7, the Vala compiler
 * generated from NotificationManager.vala, do not modify */

/* Copyright 2015 LuizAugustoMorais
*
* This file is part of Tomato.
*
* Tomato is free software: you can redistribute it
* and/or modify it under the terms of the GNU General Public License as
* published by the Free Software Foundation, either version 3 of the
* License, or (at your option) any later version.
*
* Tomato is distributed in the hope that it will be
* useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
* Public License for more details.
*
* You should have received a copy of the GNU General Public License along
* with Tomato. If not, see http://www.gnu.org/licenses/.
*/

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <granite.h>
#include <glib/gi18n-lib.h>
#include <gio/gio.h>
#include <gtk/gtk.h>
#include <gobject/gvaluecollector.h>


#define TOMATO_MANAGERS_TYPE_NOTIFICATION_MANAGER (tomato_managers_notification_manager_get_type ())
#define TOMATO_MANAGERS_NOTIFICATION_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TOMATO_MANAGERS_TYPE_NOTIFICATION_MANAGER, TomatoManagersNotificationManager))
#define TOMATO_MANAGERS_NOTIFICATION_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TOMATO_MANAGERS_TYPE_NOTIFICATION_MANAGER, TomatoManagersNotificationManagerClass))
#define TOMATO_MANAGERS_IS_NOTIFICATION_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TOMATO_MANAGERS_TYPE_NOTIFICATION_MANAGER))
#define TOMATO_MANAGERS_IS_NOTIFICATION_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TOMATO_MANAGERS_TYPE_NOTIFICATION_MANAGER))
#define TOMATO_MANAGERS_NOTIFICATION_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TOMATO_MANAGERS_TYPE_NOTIFICATION_MANAGER, TomatoManagersNotificationManagerClass))

typedef struct _TomatoManagersNotificationManager TomatoManagersNotificationManager;
typedef struct _TomatoManagersNotificationManagerClass TomatoManagersNotificationManagerClass;
typedef struct _TomatoManagersNotificationManagerPrivate TomatoManagersNotificationManagerPrivate;

#define TOMATO_MANAGERS_TYPE_SOUND_MANAGER (tomato_managers_sound_manager_get_type ())
#define TOMATO_MANAGERS_SOUND_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TOMATO_MANAGERS_TYPE_SOUND_MANAGER, TomatoManagersSoundManager))
#define TOMATO_MANAGERS_SOUND_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TOMATO_MANAGERS_TYPE_SOUND_MANAGER, TomatoManagersSoundManagerClass))
#define TOMATO_MANAGERS_IS_SOUND_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TOMATO_MANAGERS_TYPE_SOUND_MANAGER))
#define TOMATO_MANAGERS_IS_SOUND_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TOMATO_MANAGERS_TYPE_SOUND_MANAGER))
#define TOMATO_MANAGERS_SOUND_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TOMATO_MANAGERS_TYPE_SOUND_MANAGER, TomatoManagersSoundManagerClass))

typedef struct _TomatoManagersSoundManager TomatoManagersSoundManager;
typedef struct _TomatoManagersSoundManagerClass TomatoManagersSoundManagerClass;
#define _tomato_managers_sound_manager_unref0(var) ((var == NULL) ? NULL : (var = (tomato_managers_sound_manager_unref (var), NULL)))

#define TOMATO_SERVICES_TYPE_SAVED_STATE (tomato_services_saved_state_get_type ())
#define TOMATO_SERVICES_SAVED_STATE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TOMATO_SERVICES_TYPE_SAVED_STATE, TomatoServicesSavedState))
#define TOMATO_SERVICES_SAVED_STATE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TOMATO_SERVICES_TYPE_SAVED_STATE, TomatoServicesSavedStateClass))
#define TOMATO_SERVICES_IS_SAVED_STATE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TOMATO_SERVICES_TYPE_SAVED_STATE))
#define TOMATO_SERVICES_IS_SAVED_STATE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TOMATO_SERVICES_TYPE_SAVED_STATE))
#define TOMATO_SERVICES_SAVED_STATE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TOMATO_SERVICES_TYPE_SAVED_STATE, TomatoServicesSavedStateClass))

typedef struct _TomatoServicesSavedState TomatoServicesSavedState;
typedef struct _TomatoServicesSavedStateClass TomatoServicesSavedStateClass;

#define TOMATO_TYPE_STATUS (tomato_status_get_type ())
#define _g_free0(var) (var = (g_free (var), NULL))

#define TOMATO_SERVICES_TYPE_PREFERENCES (tomato_services_preferences_get_type ())
#define TOMATO_SERVICES_PREFERENCES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TOMATO_SERVICES_TYPE_PREFERENCES, TomatoServicesPreferences))
#define TOMATO_SERVICES_PREFERENCES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TOMATO_SERVICES_TYPE_PREFERENCES, TomatoServicesPreferencesClass))
#define TOMATO_SERVICES_IS_PREFERENCES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TOMATO_SERVICES_TYPE_PREFERENCES))
#define TOMATO_SERVICES_IS_PREFERENCES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TOMATO_SERVICES_TYPE_PREFERENCES))
#define TOMATO_SERVICES_PREFERENCES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TOMATO_SERVICES_TYPE_PREFERENCES, TomatoServicesPreferencesClass))

typedef struct _TomatoServicesPreferences TomatoServicesPreferences;
typedef struct _TomatoServicesPreferencesClass TomatoServicesPreferencesClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _TomatoManagersParamSpecNotificationManager TomatoManagersParamSpecNotificationManager;

struct _TomatoManagersNotificationManager {
	GTypeInstance parent_instance;
	volatile int ref_count;
	TomatoManagersNotificationManagerPrivate * priv;
};

struct _TomatoManagersNotificationManagerClass {
	GTypeClass parent_class;
	void (*finalize) (TomatoManagersNotificationManager *self);
};

struct _TomatoManagersNotificationManagerPrivate {
	TomatoManagersSoundManager* sound;
};

typedef enum  {
	TOMATO_STATUS_START,
	TOMATO_STATUS_POMODORO,
	TOMATO_STATUS_SHORT_BREAK,
	TOMATO_STATUS_LONG_BREAK
} TomatoStatus;

struct _TomatoManagersParamSpecNotificationManager {
	GParamSpec parent_instance;
};


static gpointer tomato_managers_notification_manager_parent_class = NULL;
extern TomatoServicesSavedState* tomato_saved;
extern gint tomato_break_messages_index;
extern TomatoServicesPreferences* tomato_preferences;

gpointer tomato_managers_notification_manager_ref (gpointer instance);
void tomato_managers_notification_manager_unref (gpointer instance);
GParamSpec* tomato_managers_param_spec_notification_manager (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void tomato_managers_value_set_notification_manager (GValue* value, gpointer v_object);
void tomato_managers_value_take_notification_manager (GValue* value, gpointer v_object);
gpointer tomato_managers_value_get_notification_manager (const GValue* value);
GType tomato_managers_notification_manager_get_type (void) G_GNUC_CONST;
gpointer tomato_managers_sound_manager_ref (gpointer instance);
void tomato_managers_sound_manager_unref (gpointer instance);
GParamSpec* tomato_managers_param_spec_sound_manager (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void tomato_managers_value_set_sound_manager (GValue* value, gpointer v_object);
void tomato_managers_value_take_sound_manager (GValue* value, gpointer v_object);
gpointer tomato_managers_value_get_sound_manager (const GValue* value);
GType tomato_managers_sound_manager_get_type (void) G_GNUC_CONST;
#define TOMATO_MANAGERS_NOTIFICATION_MANAGER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TOMATO_MANAGERS_TYPE_NOTIFICATION_MANAGER, TomatoManagersNotificationManagerPrivate))
enum  {
	TOMATO_MANAGERS_NOTIFICATION_MANAGER_DUMMY_PROPERTY
};
TomatoManagersNotificationManager* tomato_managers_notification_manager_new (void);
TomatoManagersNotificationManager* tomato_managers_notification_manager_construct (GType object_type);
TomatoManagersSoundManager* tomato_managers_sound_manager_new (void);
TomatoManagersSoundManager* tomato_managers_sound_manager_construct (GType object_type);
void tomato_managers_notification_manager_show_status (TomatoManagersNotificationManager* self);
GType tomato_services_saved_state_get_type (void) G_GNUC_CONST;
GType tomato_status_get_type (void) G_GNUC_CONST;
TomatoStatus tomato_services_saved_state_get_status (TomatoServicesSavedState* self);
GType tomato_services_preferences_get_type (void) G_GNUC_CONST;
gboolean tomato_services_preferences_get_pomodoro_sound_enabled (TomatoServicesPreferences* self);
void tomato_managers_sound_manager_play (TomatoManagersSoundManager* self);
void tomato_managers_notification_manager_show (TomatoManagersNotificationManager* self, const gchar* title, const gchar* body);
static void tomato_managers_notification_manager_finalize (TomatoManagersNotificationManager* obj);

extern const gchar* TOMATO_break_messages[11];

TomatoManagersNotificationManager* tomato_managers_notification_manager_construct (GType object_type) {
	TomatoManagersNotificationManager* self = NULL;
	TomatoManagersSoundManager* _tmp0_ = NULL;
#line 26 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	self = (TomatoManagersNotificationManager*) g_type_create_instance (object_type);
#line 27 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	_tmp0_ = tomato_managers_sound_manager_new ();
#line 27 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	_tomato_managers_sound_manager_unref0 (self->priv->sound);
#line 27 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	self->priv->sound = _tmp0_;
#line 26 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	return self;
#line 160 "NotificationManager.c"
}


TomatoManagersNotificationManager* tomato_managers_notification_manager_new (void) {
#line 26 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	return tomato_managers_notification_manager_construct (TOMATO_MANAGERS_TYPE_NOTIFICATION_MANAGER);
#line 167 "NotificationManager.c"
}


void tomato_managers_notification_manager_show_status (TomatoManagersNotificationManager* self) {
	gchar* title = NULL;
	gchar* body = NULL;
	TomatoServicesSavedState* _tmp0_ = NULL;
	TomatoStatus _tmp1_ = 0;
	TomatoStatus _tmp2_ = 0;
	TomatoServicesPreferences* _tmp22_ = NULL;
	gboolean _tmp23_ = FALSE;
	gboolean _tmp24_ = FALSE;
	const gchar* _tmp26_ = NULL;
	const gchar* _tmp27_ = NULL;
#line 30 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	g_return_if_fail (self != NULL);
#line 32 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	_tmp0_ = tomato_saved;
#line 32 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	_tmp1_ = tomato_services_saved_state_get_status (_tmp0_);
#line 32 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	_tmp2_ = _tmp1_;
#line 32 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	if (_tmp2_ == TOMATO_STATUS_POMODORO) {
#line 192 "NotificationManager.c"
		const gchar* _tmp3_ = NULL;
		gchar* _tmp4_ = NULL;
		const gchar* _tmp5_ = NULL;
		gchar* _tmp6_ = NULL;
#line 33 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
		_tmp3_ = _ ("Pomodoro Time");
#line 33 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
		_tmp4_ = g_strdup (_tmp3_);
#line 33 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
		_g_free0 (title);
#line 33 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
		title = _tmp4_;
#line 34 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
		_tmp5_ = _ ("Get back to work!");
#line 34 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
		_tmp6_ = g_strdup (_tmp5_);
#line 34 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
		_g_free0 (body);
#line 34 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
		body = _tmp6_;
#line 213 "NotificationManager.c"
	} else {
		TomatoServicesSavedState* _tmp7_ = NULL;
		TomatoStatus _tmp8_ = 0;
		TomatoStatus _tmp9_ = 0;
#line 35 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
		_tmp7_ = tomato_saved;
#line 35 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
		_tmp8_ = tomato_services_saved_state_get_status (_tmp7_);
#line 35 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
		_tmp9_ = _tmp8_;
#line 35 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
		if (_tmp9_ == TOMATO_STATUS_SHORT_BREAK) {
#line 226 "NotificationManager.c"
			const gchar* _tmp10_ = NULL;
			gchar* _tmp11_ = NULL;
			gint _tmp12_ = 0;
			const gchar* _tmp13_ = NULL;
			const gchar* _tmp14_ = NULL;
			gchar* _tmp15_ = NULL;
#line 36 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
			_tmp10_ = _ ("Short Break");
#line 36 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
			_tmp11_ = g_strdup (_tmp10_);
#line 36 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
			_g_free0 (title);
#line 36 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
			title = _tmp11_;
#line 37 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
			_tmp12_ = tomato_break_messages_index;
#line 37 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
			_tmp13_ = TOMATO_break_messages[_tmp12_];
#line 37 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
			_tmp14_ = _ (_tmp13_);
#line 37 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
			_tmp15_ = g_strdup (_tmp14_);
#line 37 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
			_g_free0 (body);
#line 37 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
			body = _tmp15_;
#line 253 "NotificationManager.c"
		} else {
			const gchar* _tmp16_ = NULL;
			gchar* _tmp17_ = NULL;
			gint _tmp18_ = 0;
			const gchar* _tmp19_ = NULL;
			const gchar* _tmp20_ = NULL;
			gchar* _tmp21_ = NULL;
#line 39 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
			_tmp16_ = _ ("Long Break!");
#line 39 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
			_tmp17_ = g_strdup (_tmp16_);
#line 39 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
			_g_free0 (title);
#line 39 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
			title = _tmp17_;
#line 40 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
			_tmp18_ = tomato_break_messages_index;
#line 40 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
			_tmp19_ = TOMATO_break_messages[_tmp18_];
#line 40 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
			_tmp20_ = _ (_tmp19_);
#line 40 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
			_tmp21_ = g_strdup (_tmp20_);
#line 40 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
			_g_free0 (body);
#line 40 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
			body = _tmp21_;
#line 281 "NotificationManager.c"
		}
	}
#line 42 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	_tmp22_ = tomato_preferences;
#line 42 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	_tmp23_ = tomato_services_preferences_get_pomodoro_sound_enabled (_tmp22_);
#line 42 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	_tmp24_ = _tmp23_;
#line 42 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	if (_tmp24_) {
#line 292 "NotificationManager.c"
		TomatoManagersSoundManager* _tmp25_ = NULL;
#line 43 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
		_tmp25_ = self->priv->sound;
#line 43 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
		tomato_managers_sound_manager_play (_tmp25_);
#line 298 "NotificationManager.c"
	}
#line 45 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	_tmp26_ = title;
#line 45 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	_tmp27_ = body;
#line 45 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	tomato_managers_notification_manager_show (self, _tmp26_, _tmp27_);
#line 30 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	_g_free0 (body);
#line 30 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	_g_free0 (title);
#line 310 "NotificationManager.c"
}


void tomato_managers_notification_manager_show (TomatoManagersNotificationManager* self, const gchar* title, const gchar* body) {
	GNotification* notification = NULL;
	const gchar* _tmp0_ = NULL;
	GNotification* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	GtkImage* image = NULL;
	GtkImage* _tmp3_ = NULL;
	GIcon* _tmp4_ = NULL;
	GIcon* _tmp5_ = NULL;
	GIcon* _tmp6_ = NULL;
	GApplication* _tmp7_ = NULL;
#line 48 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	g_return_if_fail (self != NULL);
#line 48 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	g_return_if_fail (title != NULL);
#line 48 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	g_return_if_fail (body != NULL);
#line 49 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	_tmp0_ = title;
#line 49 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	_tmp1_ = g_notification_new (_tmp0_);
#line 49 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	notification = _tmp1_;
#line 50 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	_tmp2_ = body;
#line 50 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	g_notification_set_body (notification, _tmp2_);
#line 51 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	_tmp3_ = (GtkImage*) gtk_image_new_from_icon_name ("tomato", GTK_ICON_SIZE_DIALOG);
#line 51 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	g_object_ref_sink (_tmp3_);
#line 51 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	image = _tmp3_;
#line 52 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	g_object_get (image, "gicon", &_tmp4_, NULL);
#line 52 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	_tmp5_ = _tmp4_;
#line 52 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	_tmp6_ = _tmp5_;
#line 52 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	g_notification_set_icon (notification, _tmp6_);
#line 52 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	_g_object_unref0 (_tmp6_);
#line 53 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	_tmp7_ = g_application_get_default ();
#line 53 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	g_application_send_notification (_tmp7_, "com.github.luizaugustomm.tomato", notification);
#line 48 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	_g_object_unref0 (image);
#line 48 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	_g_object_unref0 (notification);
#line 365 "NotificationManager.c"
}


static void tomato_managers_value_notification_manager_init (GValue* value) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	value->data[0].v_pointer = NULL;
#line 372 "NotificationManager.c"
}


static void tomato_managers_value_notification_manager_free_value (GValue* value) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	if (value->data[0].v_pointer) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
		tomato_managers_notification_manager_unref (value->data[0].v_pointer);
#line 381 "NotificationManager.c"
	}
}


static void tomato_managers_value_notification_manager_copy_value (const GValue* src_value, GValue* dest_value) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	if (src_value->data[0].v_pointer) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
		dest_value->data[0].v_pointer = tomato_managers_notification_manager_ref (src_value->data[0].v_pointer);
#line 391 "NotificationManager.c"
	} else {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
		dest_value->data[0].v_pointer = NULL;
#line 395 "NotificationManager.c"
	}
}


static gpointer tomato_managers_value_notification_manager_peek_pointer (const GValue* value) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	return value->data[0].v_pointer;
#line 403 "NotificationManager.c"
}


static gchar* tomato_managers_value_notification_manager_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	if (collect_values[0].v_pointer) {
#line 410 "NotificationManager.c"
		TomatoManagersNotificationManager* object;
		object = collect_values[0].v_pointer;
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
		if (object->parent_instance.g_class == NULL) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 417 "NotificationManager.c"
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 421 "NotificationManager.c"
		}
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
		value->data[0].v_pointer = tomato_managers_notification_manager_ref (object);
#line 425 "NotificationManager.c"
	} else {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
		value->data[0].v_pointer = NULL;
#line 429 "NotificationManager.c"
	}
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	return NULL;
#line 433 "NotificationManager.c"
}


static gchar* tomato_managers_value_notification_manager_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	TomatoManagersNotificationManager** object_p;
	object_p = collect_values[0].v_pointer;
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	if (!object_p) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
#line 444 "NotificationManager.c"
	}
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	if (!value->data[0].v_pointer) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
		*object_p = NULL;
#line 450 "NotificationManager.c"
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
		*object_p = value->data[0].v_pointer;
#line 454 "NotificationManager.c"
	} else {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
		*object_p = tomato_managers_notification_manager_ref (value->data[0].v_pointer);
#line 458 "NotificationManager.c"
	}
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	return NULL;
#line 462 "NotificationManager.c"
}


GParamSpec* tomato_managers_param_spec_notification_manager (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	TomatoManagersParamSpecNotificationManager* spec;
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	g_return_val_if_fail (g_type_is_a (object_type, TOMATO_MANAGERS_TYPE_NOTIFICATION_MANAGER), NULL);
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	G_PARAM_SPEC (spec)->value_type = object_type;
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	return G_PARAM_SPEC (spec);
#line 476 "NotificationManager.c"
}


gpointer tomato_managers_value_get_notification_manager (const GValue* value) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TOMATO_MANAGERS_TYPE_NOTIFICATION_MANAGER), NULL);
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	return value->data[0].v_pointer;
#line 485 "NotificationManager.c"
}


void tomato_managers_value_set_notification_manager (GValue* value, gpointer v_object) {
	TomatoManagersNotificationManager* old;
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TOMATO_MANAGERS_TYPE_NOTIFICATION_MANAGER));
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	old = value->data[0].v_pointer;
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	if (v_object) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TOMATO_MANAGERS_TYPE_NOTIFICATION_MANAGER));
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
		value->data[0].v_pointer = v_object;
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
		tomato_managers_notification_manager_ref (value->data[0].v_pointer);
#line 505 "NotificationManager.c"
	} else {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
		value->data[0].v_pointer = NULL;
#line 509 "NotificationManager.c"
	}
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	if (old) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
		tomato_managers_notification_manager_unref (old);
#line 515 "NotificationManager.c"
	}
}


void tomato_managers_value_take_notification_manager (GValue* value, gpointer v_object) {
	TomatoManagersNotificationManager* old;
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TOMATO_MANAGERS_TYPE_NOTIFICATION_MANAGER));
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	old = value->data[0].v_pointer;
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	if (v_object) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TOMATO_MANAGERS_TYPE_NOTIFICATION_MANAGER));
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
		value->data[0].v_pointer = v_object;
#line 534 "NotificationManager.c"
	} else {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
		value->data[0].v_pointer = NULL;
#line 538 "NotificationManager.c"
	}
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	if (old) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
		tomato_managers_notification_manager_unref (old);
#line 544 "NotificationManager.c"
	}
}


static void tomato_managers_notification_manager_class_init (TomatoManagersNotificationManagerClass * klass) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	tomato_managers_notification_manager_parent_class = g_type_class_peek_parent (klass);
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	((TomatoManagersNotificationManagerClass *) klass)->finalize = tomato_managers_notification_manager_finalize;
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	g_type_class_add_private (klass, sizeof (TomatoManagersNotificationManagerPrivate));
#line 556 "NotificationManager.c"
}


static void tomato_managers_notification_manager_instance_init (TomatoManagersNotificationManager * self) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	self->priv = TOMATO_MANAGERS_NOTIFICATION_MANAGER_GET_PRIVATE (self);
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	self->ref_count = 1;
#line 565 "NotificationManager.c"
}


static void tomato_managers_notification_manager_finalize (TomatoManagersNotificationManager* obj) {
	TomatoManagersNotificationManager * self;
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TOMATO_MANAGERS_TYPE_NOTIFICATION_MANAGER, TomatoManagersNotificationManager);
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	g_signal_handlers_destroy (self);
#line 23 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	_tomato_managers_sound_manager_unref0 (self->priv->sound);
#line 577 "NotificationManager.c"
}


GType tomato_managers_notification_manager_get_type (void) {
	static volatile gsize tomato_managers_notification_manager_type_id__volatile = 0;
	if (g_once_init_enter (&tomato_managers_notification_manager_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { tomato_managers_value_notification_manager_init, tomato_managers_value_notification_manager_free_value, tomato_managers_value_notification_manager_copy_value, tomato_managers_value_notification_manager_peek_pointer, "p", tomato_managers_value_notification_manager_collect_value, "p", tomato_managers_value_notification_manager_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (TomatoManagersNotificationManagerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) tomato_managers_notification_manager_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TomatoManagersNotificationManager), 0, (GInstanceInitFunc) tomato_managers_notification_manager_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType tomato_managers_notification_manager_type_id;
		tomato_managers_notification_manager_type_id = g_type_register_fundamental (g_type_fundamental_next (), "TomatoManagersNotificationManager", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&tomato_managers_notification_manager_type_id__volatile, tomato_managers_notification_manager_type_id);
	}
	return tomato_managers_notification_manager_type_id__volatile;
}


gpointer tomato_managers_notification_manager_ref (gpointer instance) {
	TomatoManagersNotificationManager* self;
	self = instance;
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	g_atomic_int_inc (&self->ref_count);
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	return instance;
#line 602 "NotificationManager.c"
}


void tomato_managers_notification_manager_unref (gpointer instance) {
	TomatoManagersNotificationManager* self;
	self = instance;
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
		TOMATO_MANAGERS_NOTIFICATION_MANAGER_GET_CLASS (self)->finalize (self);
#line 21 "/home/lamm/Projetos/tomato/src/Managers/NotificationManager.vala"
		g_type_free_instance ((GTypeInstance *) self);
#line 615 "NotificationManager.c"
	}
}



