/* WorkManager.c generated by valac 0.34.7, the Vala compiler
 * generated from WorkManager.vala, do not modify */

/* Copyright 2015 LuizAugustoMorais
*
* This file is part of Tomato.
*
* Tomato is free software: you can redistribute it
* and/or modify it under the terms of the GNU General Public License as
* published by the Free Software Foundation, either version 3 of the
* License, or (at your option) any later version.
*
* Tomato is distributed in the hope that it will be
* useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
* Public License for more details.
*
* You should have received a copy of the GNU General Public License along
* with Tomato. If not, see http://www.gnu.org/licenses/.
*/

#include <glib.h>
#include <glib-object.h>
#include <granite.h>
#include <stdlib.h>
#include <string.h>
#include <gobject/gvaluecollector.h>


#define TOMATO_MANAGERS_TYPE_WORK_MANAGER (tomato_managers_work_manager_get_type ())
#define TOMATO_MANAGERS_WORK_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TOMATO_MANAGERS_TYPE_WORK_MANAGER, TomatoManagersWorkManager))
#define TOMATO_MANAGERS_WORK_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TOMATO_MANAGERS_TYPE_WORK_MANAGER, TomatoManagersWorkManagerClass))
#define TOMATO_MANAGERS_IS_WORK_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TOMATO_MANAGERS_TYPE_WORK_MANAGER))
#define TOMATO_MANAGERS_IS_WORK_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TOMATO_MANAGERS_TYPE_WORK_MANAGER))
#define TOMATO_MANAGERS_WORK_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TOMATO_MANAGERS_TYPE_WORK_MANAGER, TomatoManagersWorkManagerClass))

typedef struct _TomatoManagersWorkManager TomatoManagersWorkManager;
typedef struct _TomatoManagersWorkManagerClass TomatoManagersWorkManagerClass;
typedef struct _TomatoManagersWorkManagerPrivate TomatoManagersWorkManagerPrivate;

#define TOMATO_UTIL_TYPE_COUNTDOWN (tomato_util_countdown_get_type ())
#define TOMATO_UTIL_COUNTDOWN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TOMATO_UTIL_TYPE_COUNTDOWN, TomatoUtilCountdown))
#define TOMATO_UTIL_COUNTDOWN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TOMATO_UTIL_TYPE_COUNTDOWN, TomatoUtilCountdownClass))
#define TOMATO_UTIL_IS_COUNTDOWN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TOMATO_UTIL_TYPE_COUNTDOWN))
#define TOMATO_UTIL_IS_COUNTDOWN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TOMATO_UTIL_TYPE_COUNTDOWN))
#define TOMATO_UTIL_COUNTDOWN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TOMATO_UTIL_TYPE_COUNTDOWN, TomatoUtilCountdownClass))

typedef struct _TomatoUtilCountdown TomatoUtilCountdown;
typedef struct _TomatoUtilCountdownClass TomatoUtilCountdownClass;

#define TOMATO_UTIL_TYPE_TIMER (tomato_util_timer_get_type ())
#define TOMATO_UTIL_TIMER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TOMATO_UTIL_TYPE_TIMER, TomatoUtilTimer))
#define TOMATO_UTIL_TIMER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TOMATO_UTIL_TYPE_TIMER, TomatoUtilTimerClass))
#define TOMATO_UTIL_IS_TIMER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TOMATO_UTIL_TYPE_TIMER))
#define TOMATO_UTIL_IS_TIMER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TOMATO_UTIL_TYPE_TIMER))
#define TOMATO_UTIL_TIMER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TOMATO_UTIL_TYPE_TIMER, TomatoUtilTimerClass))

typedef struct _TomatoUtilTimer TomatoUtilTimer;
typedef struct _TomatoUtilTimerClass TomatoUtilTimerClass;
#define _tomato_util_countdown_unref0(var) ((var == NULL) ? NULL : (var = (tomato_util_countdown_unref (var), NULL)))
#define _tomato_util_timer_unref0(var) ((var == NULL) ? NULL : (var = (tomato_util_timer_unref (var), NULL)))

#define TOMATO_SERVICES_TYPE_SAVED_STATE (tomato_services_saved_state_get_type ())
#define TOMATO_SERVICES_SAVED_STATE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TOMATO_SERVICES_TYPE_SAVED_STATE, TomatoServicesSavedState))
#define TOMATO_SERVICES_SAVED_STATE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TOMATO_SERVICES_TYPE_SAVED_STATE, TomatoServicesSavedStateClass))
#define TOMATO_SERVICES_IS_SAVED_STATE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TOMATO_SERVICES_TYPE_SAVED_STATE))
#define TOMATO_SERVICES_IS_SAVED_STATE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TOMATO_SERVICES_TYPE_SAVED_STATE))
#define TOMATO_SERVICES_SAVED_STATE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TOMATO_SERVICES_TYPE_SAVED_STATE, TomatoServicesSavedStateClass))

typedef struct _TomatoServicesSavedState TomatoServicesSavedState;
typedef struct _TomatoServicesSavedStateClass TomatoServicesSavedStateClass;

#define TOMATO_SERVICES_TYPE_PREFERENCES (tomato_services_preferences_get_type ())
#define TOMATO_SERVICES_PREFERENCES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TOMATO_SERVICES_TYPE_PREFERENCES, TomatoServicesPreferences))
#define TOMATO_SERVICES_PREFERENCES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TOMATO_SERVICES_TYPE_PREFERENCES, TomatoServicesPreferencesClass))
#define TOMATO_SERVICES_IS_PREFERENCES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TOMATO_SERVICES_TYPE_PREFERENCES))
#define TOMATO_SERVICES_IS_PREFERENCES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TOMATO_SERVICES_TYPE_PREFERENCES))
#define TOMATO_SERVICES_PREFERENCES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TOMATO_SERVICES_TYPE_PREFERENCES, TomatoServicesPreferencesClass))

typedef struct _TomatoServicesPreferences TomatoServicesPreferences;
typedef struct _TomatoServicesPreferencesClass TomatoServicesPreferencesClass;

#define TOMATO_TYPE_STATUS (tomato_status_get_type ())

#define TOMATO_SERVICES_TYPE_SETTINGS (tomato_services_settings_get_type ())
#define TOMATO_SERVICES_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TOMATO_SERVICES_TYPE_SETTINGS, TomatoServicesSettings))
#define TOMATO_SERVICES_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TOMATO_SERVICES_TYPE_SETTINGS, TomatoServicesSettingsClass))
#define TOMATO_SERVICES_IS_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TOMATO_SERVICES_TYPE_SETTINGS))
#define TOMATO_SERVICES_IS_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TOMATO_SERVICES_TYPE_SETTINGS))
#define TOMATO_SERVICES_SETTINGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TOMATO_SERVICES_TYPE_SETTINGS, TomatoServicesSettingsClass))

typedef struct _TomatoServicesSettings TomatoServicesSettings;
typedef struct _TomatoServicesSettingsClass TomatoServicesSettingsClass;
typedef struct _TomatoManagersParamSpecWorkManager TomatoManagersParamSpecWorkManager;

struct _TomatoManagersWorkManager {
	GTypeInstance parent_instance;
	volatile int ref_count;
	TomatoManagersWorkManagerPrivate * priv;
};

struct _TomatoManagersWorkManagerClass {
	GTypeClass parent_class;
	void (*finalize) (TomatoManagersWorkManager *self);
};

struct _TomatoManagersWorkManagerPrivate {
	TomatoUtilCountdown* countdown;
	TomatoUtilTimer* total_time;
	gint ticks;
};

typedef enum  {
	TOMATO_STATUS_START,
	TOMATO_STATUS_POMODORO,
	TOMATO_STATUS_SHORT_BREAK,
	TOMATO_STATUS_LONG_BREAK
} TomatoStatus;

struct _TomatoManagersParamSpecWorkManager {
	GParamSpec parent_instance;
};


static gpointer tomato_managers_work_manager_parent_class = NULL;
extern TomatoServicesSavedState* tomato_saved;
extern TomatoServicesPreferences* tomato_preferences;
extern TomatoServicesSettings* tomato_settings;

gpointer tomato_managers_work_manager_ref (gpointer instance);
void tomato_managers_work_manager_unref (gpointer instance);
GParamSpec* tomato_managers_param_spec_work_manager (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void tomato_managers_value_set_work_manager (GValue* value, gpointer v_object);
void tomato_managers_value_take_work_manager (GValue* value, gpointer v_object);
gpointer tomato_managers_value_get_work_manager (const GValue* value);
GType tomato_managers_work_manager_get_type (void) G_GNUC_CONST;
gpointer tomato_util_countdown_ref (gpointer instance);
void tomato_util_countdown_unref (gpointer instance);
GParamSpec* tomato_util_param_spec_countdown (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void tomato_util_value_set_countdown (GValue* value, gpointer v_object);
void tomato_util_value_take_countdown (GValue* value, gpointer v_object);
gpointer tomato_util_value_get_countdown (const GValue* value);
GType tomato_util_countdown_get_type (void) G_GNUC_CONST;
gpointer tomato_util_timer_ref (gpointer instance);
void tomato_util_timer_unref (gpointer instance);
GParamSpec* tomato_util_param_spec_timer (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void tomato_util_value_set_timer (GValue* value, gpointer v_object);
void tomato_util_value_take_timer (GValue* value, gpointer v_object);
gpointer tomato_util_value_get_timer (const GValue* value);
GType tomato_util_timer_get_type (void) G_GNUC_CONST;
#define TOMATO_MANAGERS_WORK_MANAGER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TOMATO_MANAGERS_TYPE_WORK_MANAGER, TomatoManagersWorkManagerPrivate))
enum  {
	TOMATO_MANAGERS_WORK_MANAGER_DUMMY_PROPERTY
};
TomatoManagersWorkManager* tomato_managers_work_manager_new (void);
TomatoManagersWorkManager* tomato_managers_work_manager_construct (GType object_type);
TomatoUtilCountdown* tomato_util_countdown_new (void);
TomatoUtilCountdown* tomato_util_countdown_construct (GType object_type);
TomatoUtilTimer* tomato_util_timer_new (void);
TomatoUtilTimer* tomato_util_timer_construct (GType object_type);
GType tomato_services_saved_state_get_type (void) G_GNUC_CONST;
gboolean tomato_services_saved_state_is_date_today (TomatoServicesSavedState* self);
GType tomato_services_preferences_get_type (void) G_GNUC_CONST;
gboolean tomato_services_preferences_get_reset_work_everyday (TomatoServicesPreferences* self);
void tomato_managers_work_manager_reset (TomatoManagersWorkManager* self);
static void tomato_managers_work_manager_set_countdown (TomatoManagersWorkManager* self, gint time);
gint tomato_services_saved_state_get_countdown (TomatoServicesSavedState* self);
static void tomato_managers_work_manager_set_total_time (TomatoManagersWorkManager* self, gint time);
gint tomato_services_saved_state_get_total_time (TomatoServicesSavedState* self);
void tomato_services_saved_state_update_date (TomatoServicesSavedState* self);
gint tomato_managers_work_manager_raw_countdown (TomatoManagersWorkManager* self);
gint tomato_util_countdown_get_current_time (TomatoUtilCountdown* self);
gchar* tomato_managers_work_manager_formatted_countdown (TomatoManagersWorkManager* self);
gchar* tomato_util_countdown_get_current_ftime (TomatoUtilCountdown* self, gboolean without_hours);
gchar* tomato_managers_work_manager_formatted_total_time (TomatoManagersWorkManager* self);
gchar* tomato_util_timer_get_current_ftime (TomatoUtilTimer* self);
void tomato_managers_work_manager_start (TomatoManagersWorkManager* self);
GType tomato_status_get_type (void) G_GNUC_CONST;
void tomato_managers_work_manager_set_status (TomatoManagersWorkManager* self, TomatoStatus status);
void tomato_managers_work_manager_stop (TomatoManagersWorkManager* self);
void tomato_managers_work_manager_tick (TomatoManagersWorkManager* self);
gint tomato_util_countdown_tick (TomatoUtilCountdown* self);
void tomato_services_saved_state_set_countdown (TomatoServicesSavedState* self, gint value);
TomatoStatus tomato_services_saved_state_get_status (TomatoServicesSavedState* self);
gint tomato_util_timer_tick (TomatoUtilTimer* self);
void tomato_services_saved_state_set_total_time (TomatoServicesSavedState* self, gint value);
void tomato_services_saved_state_set_status (TomatoServicesSavedState* self, TomatoStatus value);
gboolean tomato_managers_work_manager_time_is_over (TomatoManagersWorkManager* self);
gboolean tomato_util_countdown_is_over (TomatoUtilCountdown* self);
gint tomato_services_saved_state_get_pomodoro_count (TomatoServicesSavedState* self);
void tomato_services_saved_state_set_pomodoro_count (TomatoServicesSavedState* self, gint value);
static void tomato_managers_work_manager_update_status (TomatoManagersWorkManager* self);
void tomato_managers_work_manager_reset_countdown (TomatoManagersWorkManager* self);
GType tomato_services_settings_get_type (void) G_GNUC_CONST;
gint tomato_services_settings_get_pomodoro_duration (TomatoServicesSettings* self);
gint tomato_services_settings_get_short_break_duration (TomatoServicesSettings* self);
gint tomato_services_settings_get_long_break_duration (TomatoServicesSettings* self);
void tomato_util_countdown_set_current_time (TomatoUtilCountdown* self, gint time);
void tomato_util_timer_set_current_time (TomatoUtilTimer* self, gint time);
gint tomato_services_settings_get_long_break_delay (TomatoServicesSettings* self);
static void tomato_managers_work_manager_finalize (TomatoManagersWorkManager* obj);


TomatoManagersWorkManager* tomato_managers_work_manager_construct (GType object_type) {
	TomatoManagersWorkManager* self = NULL;
	TomatoUtilCountdown* _tmp0_ = NULL;
	TomatoUtilTimer* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	TomatoServicesSavedState* _tmp3_ = NULL;
	gboolean _tmp4_ = FALSE;
	TomatoServicesSavedState* _tmp14_ = NULL;
#line 28 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	self = (TomatoManagersWorkManager*) g_type_create_instance (object_type);
#line 29 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	_tmp0_ = tomato_util_countdown_new ();
#line 29 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	_tomato_util_countdown_unref0 (self->priv->countdown);
#line 29 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	self->priv->countdown = _tmp0_;
#line 30 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	_tmp1_ = tomato_util_timer_new ();
#line 30 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	_tomato_util_timer_unref0 (self->priv->total_time);
#line 30 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	self->priv->total_time = _tmp1_;
#line 32 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	_tmp3_ = tomato_saved;
#line 32 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	_tmp4_ = tomato_services_saved_state_is_date_today (_tmp3_);
#line 32 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	if (!_tmp4_) {
#line 233 "WorkManager.c"
		TomatoServicesPreferences* _tmp5_ = NULL;
		gboolean _tmp6_ = FALSE;
		gboolean _tmp7_ = FALSE;
#line 32 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		_tmp5_ = tomato_preferences;
#line 32 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		_tmp6_ = tomato_services_preferences_get_reset_work_everyday (_tmp5_);
#line 32 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		_tmp7_ = _tmp6_;
#line 32 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		_tmp2_ = _tmp7_;
#line 245 "WorkManager.c"
	} else {
#line 32 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		_tmp2_ = FALSE;
#line 249 "WorkManager.c"
	}
#line 32 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	if (_tmp2_) {
#line 33 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		tomato_managers_work_manager_reset (self);
#line 255 "WorkManager.c"
	} else {
		TomatoServicesSavedState* _tmp8_ = NULL;
		gint _tmp9_ = 0;
		gint _tmp10_ = 0;
		TomatoServicesSavedState* _tmp11_ = NULL;
		gint _tmp12_ = 0;
		gint _tmp13_ = 0;
#line 35 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		_tmp8_ = tomato_saved;
#line 35 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		_tmp9_ = tomato_services_saved_state_get_countdown (_tmp8_);
#line 35 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		_tmp10_ = _tmp9_;
#line 35 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		tomato_managers_work_manager_set_countdown (self, _tmp10_);
#line 36 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		_tmp11_ = tomato_saved;
#line 36 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		_tmp12_ = tomato_services_saved_state_get_total_time (_tmp11_);
#line 36 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		_tmp13_ = _tmp12_;
#line 36 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		tomato_managers_work_manager_set_total_time (self, _tmp13_);
#line 279 "WorkManager.c"
	}
#line 38 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	_tmp14_ = tomato_saved;
#line 38 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	tomato_services_saved_state_update_date (_tmp14_);
#line 28 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	return self;
#line 287 "WorkManager.c"
}


TomatoManagersWorkManager* tomato_managers_work_manager_new (void) {
#line 28 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	return tomato_managers_work_manager_construct (TOMATO_MANAGERS_TYPE_WORK_MANAGER);
#line 294 "WorkManager.c"
}


gint tomato_managers_work_manager_raw_countdown (TomatoManagersWorkManager* self) {
	gint result = 0;
	TomatoUtilCountdown* _tmp0_ = NULL;
	gint _tmp1_ = 0;
#line 41 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 42 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	_tmp0_ = self->priv->countdown;
#line 42 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	_tmp1_ = tomato_util_countdown_get_current_time (_tmp0_);
#line 42 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	result = _tmp1_;
#line 42 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	return result;
#line 312 "WorkManager.c"
}


gchar* tomato_managers_work_manager_formatted_countdown (TomatoManagersWorkManager* self) {
	gchar* result = NULL;
	TomatoUtilCountdown* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
#line 45 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 46 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	_tmp0_ = self->priv->countdown;
#line 46 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	_tmp1_ = tomato_util_countdown_get_current_ftime (_tmp0_, TRUE);
#line 46 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	result = _tmp1_;
#line 46 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	return result;
#line 330 "WorkManager.c"
}


gchar* tomato_managers_work_manager_formatted_total_time (TomatoManagersWorkManager* self) {
	gchar* result = NULL;
	TomatoUtilTimer* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
#line 49 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 50 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	_tmp0_ = self->priv->total_time;
#line 50 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	_tmp1_ = tomato_util_timer_get_current_ftime (_tmp0_);
#line 50 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	result = _tmp1_;
#line 50 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	return result;
#line 348 "WorkManager.c"
}


void tomato_managers_work_manager_start (TomatoManagersWorkManager* self) {
#line 53 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	g_return_if_fail (self != NULL);
#line 54 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	tomato_managers_work_manager_set_status (self, TOMATO_STATUS_POMODORO);
#line 357 "WorkManager.c"
}


void tomato_managers_work_manager_stop (TomatoManagersWorkManager* self) {
#line 57 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	g_return_if_fail (self != NULL);
#line 58 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	tomato_managers_work_manager_set_status (self, TOMATO_STATUS_START);
#line 59 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	g_message ("WorkManager.vala:59: New status -> Start");
#line 368 "WorkManager.c"
}


void tomato_managers_work_manager_tick (TomatoManagersWorkManager* self) {
	TomatoServicesSavedState* _tmp0_ = NULL;
	TomatoUtilCountdown* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	TomatoServicesSavedState* _tmp3_ = NULL;
	TomatoStatus _tmp4_ = 0;
	TomatoStatus _tmp5_ = 0;
#line 62 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	g_return_if_fail (self != NULL);
#line 63 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	_tmp0_ = tomato_saved;
#line 63 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	_tmp1_ = self->priv->countdown;
#line 63 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	_tmp2_ = tomato_util_countdown_tick (_tmp1_);
#line 63 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	tomato_services_saved_state_set_countdown (_tmp0_, _tmp2_);
#line 65 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	_tmp3_ = tomato_saved;
#line 65 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	_tmp4_ = tomato_services_saved_state_get_status (_tmp3_);
#line 65 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	_tmp5_ = _tmp4_;
#line 65 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	if (_tmp5_ == TOMATO_STATUS_POMODORO) {
#line 397 "WorkManager.c"
		gint _tmp6_ = 0;
#line 66 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		_tmp6_ = self->priv->ticks;
#line 66 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		if (_tmp6_ == 60) {
#line 403 "WorkManager.c"
			TomatoServicesSavedState* _tmp7_ = NULL;
			TomatoUtilTimer* _tmp8_ = NULL;
			gint _tmp9_ = 0;
#line 67 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
			_tmp7_ = tomato_saved;
#line 67 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
			_tmp8_ = self->priv->total_time;
#line 67 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
			_tmp9_ = tomato_util_timer_tick (_tmp8_);
#line 67 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
			tomato_services_saved_state_set_total_time (_tmp7_, _tmp9_);
#line 68 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
			self->priv->ticks = 1;
#line 69 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
			g_message ("WorkManager.vala:69: +1 minute worked");
#line 419 "WorkManager.c"
		} else {
			gint _tmp10_ = 0;
#line 71 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
			_tmp10_ = self->priv->ticks;
#line 71 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
			self->priv->ticks = _tmp10_ + 1;
#line 426 "WorkManager.c"
		}
	}
}


void tomato_managers_work_manager_set_status (TomatoManagersWorkManager* self, TomatoStatus status) {
	TomatoServicesSavedState* _tmp0_ = NULL;
	TomatoStatus _tmp1_ = 0;
#line 76 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	g_return_if_fail (self != NULL);
#line 77 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	_tmp0_ = tomato_saved;
#line 77 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	_tmp1_ = status;
#line 77 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	tomato_services_saved_state_set_status (_tmp0_, _tmp1_);
#line 443 "WorkManager.c"
}


gboolean tomato_managers_work_manager_time_is_over (TomatoManagersWorkManager* self) {
	gboolean result = FALSE;
	gboolean is_over = FALSE;
	TomatoUtilCountdown* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
#line 80 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 81 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	_tmp0_ = self->priv->countdown;
#line 81 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	_tmp1_ = tomato_util_countdown_is_over (_tmp0_);
#line 81 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	is_over = _tmp1_;
#line 82 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	_tmp2_ = is_over;
#line 82 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	if (_tmp2_) {
#line 465 "WorkManager.c"
		TomatoServicesSavedState* _tmp3_ = NULL;
		TomatoStatus _tmp4_ = 0;
		TomatoStatus _tmp5_ = 0;
#line 83 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		_tmp3_ = tomato_saved;
#line 83 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		_tmp4_ = tomato_services_saved_state_get_status (_tmp3_);
#line 83 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		_tmp5_ = _tmp4_;
#line 83 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		if (_tmp5_ == TOMATO_STATUS_POMODORO) {
#line 477 "WorkManager.c"
			TomatoServicesSavedState* _tmp6_ = NULL;
			TomatoServicesSavedState* _tmp7_ = NULL;
			gint _tmp8_ = 0;
			gint _tmp9_ = 0;
#line 84 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
			_tmp6_ = tomato_saved;
#line 84 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
			_tmp7_ = tomato_saved;
#line 84 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
			_tmp8_ = tomato_services_saved_state_get_pomodoro_count (_tmp7_);
#line 84 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
			_tmp9_ = _tmp8_;
#line 84 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
			tomato_services_saved_state_set_pomodoro_count (_tmp7_, _tmp9_ + 1);
#line 492 "WorkManager.c"
		}
#line 85 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		tomato_managers_work_manager_update_status (self);
#line 86 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		tomato_managers_work_manager_reset_countdown (self);
#line 498 "WorkManager.c"
	}
#line 88 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	result = is_over;
#line 88 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	return result;
#line 504 "WorkManager.c"
}


void tomato_managers_work_manager_reset (TomatoManagersWorkManager* self) {
	TomatoServicesSavedState* _tmp0_ = NULL;
#line 91 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	g_return_if_fail (self != NULL);
#line 92 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	tomato_managers_work_manager_stop (self);
#line 93 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	self->priv->ticks = 1;
#line 95 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	tomato_managers_work_manager_reset_countdown (self);
#line 96 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	tomato_managers_work_manager_set_total_time (self, 0);
#line 98 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	_tmp0_ = tomato_saved;
#line 98 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	tomato_services_saved_state_set_pomodoro_count (_tmp0_, 0);
#line 524 "WorkManager.c"
}


void tomato_managers_work_manager_reset_countdown (TomatoManagersWorkManager* self) {
	TomatoServicesSavedState* _tmp0_ = NULL;
	TomatoStatus _tmp1_ = 0;
	TomatoStatus _tmp2_ = 0;
#line 101 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	g_return_if_fail (self != NULL);
#line 102 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	_tmp0_ = tomato_saved;
#line 102 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	_tmp1_ = tomato_services_saved_state_get_status (_tmp0_);
#line 102 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	_tmp2_ = _tmp1_;
#line 102 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	switch (_tmp2_) {
#line 102 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		case TOMATO_STATUS_START:
#line 102 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		case TOMATO_STATUS_POMODORO:
#line 546 "WorkManager.c"
		{
			TomatoServicesSettings* _tmp3_ = NULL;
			gint _tmp4_ = 0;
			gint _tmp5_ = 0;
#line 105 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
			_tmp3_ = tomato_settings;
#line 105 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
			_tmp4_ = tomato_services_settings_get_pomodoro_duration (_tmp3_);
#line 105 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
			_tmp5_ = _tmp4_;
#line 105 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
			tomato_managers_work_manager_set_countdown (self, _tmp5_ * 60);
#line 106 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
			break;
#line 561 "WorkManager.c"
		}
#line 102 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		case TOMATO_STATUS_SHORT_BREAK:
#line 565 "WorkManager.c"
		{
			TomatoServicesSettings* _tmp6_ = NULL;
			gint _tmp7_ = 0;
			gint _tmp8_ = 0;
#line 108 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
			_tmp6_ = tomato_settings;
#line 108 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
			_tmp7_ = tomato_services_settings_get_short_break_duration (_tmp6_);
#line 108 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
			_tmp8_ = _tmp7_;
#line 108 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
			tomato_managers_work_manager_set_countdown (self, _tmp8_ * 60);
#line 109 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
			break;
#line 580 "WorkManager.c"
		}
#line 102 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		case TOMATO_STATUS_LONG_BREAK:
#line 584 "WorkManager.c"
		{
			TomatoServicesSettings* _tmp9_ = NULL;
			gint _tmp10_ = 0;
			gint _tmp11_ = 0;
#line 111 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
			_tmp9_ = tomato_settings;
#line 111 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
			_tmp10_ = tomato_services_settings_get_long_break_duration (_tmp9_);
#line 111 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
			_tmp11_ = _tmp10_;
#line 111 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
			tomato_managers_work_manager_set_countdown (self, _tmp11_ * 60);
#line 112 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
			break;
#line 599 "WorkManager.c"
		}
		default:
#line 102 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		break;
#line 604 "WorkManager.c"
	}
}


static void tomato_managers_work_manager_set_countdown (TomatoManagersWorkManager* self, gint time) {
	TomatoUtilCountdown* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	TomatoServicesSavedState* _tmp2_ = NULL;
	gint _tmp3_ = 0;
#line 120 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	g_return_if_fail (self != NULL);
#line 121 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	_tmp0_ = self->priv->countdown;
#line 121 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	_tmp1_ = time;
#line 121 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	tomato_util_countdown_set_current_time (_tmp0_, _tmp1_);
#line 122 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	_tmp2_ = tomato_saved;
#line 122 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	_tmp3_ = time;
#line 122 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	tomato_services_saved_state_set_countdown (_tmp2_, _tmp3_);
#line 628 "WorkManager.c"
}


static void tomato_managers_work_manager_set_total_time (TomatoManagersWorkManager* self, gint time) {
	TomatoUtilTimer* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	TomatoServicesSavedState* _tmp2_ = NULL;
	gint _tmp3_ = 0;
#line 125 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	g_return_if_fail (self != NULL);
#line 126 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	_tmp0_ = self->priv->total_time;
#line 126 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	_tmp1_ = time;
#line 126 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	tomato_util_timer_set_current_time (_tmp0_, _tmp1_);
#line 127 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	_tmp2_ = tomato_saved;
#line 127 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	_tmp3_ = time;
#line 127 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	tomato_services_saved_state_set_total_time (_tmp2_, _tmp3_);
#line 651 "WorkManager.c"
}


static void tomato_managers_work_manager_update_status (TomatoManagersWorkManager* self) {
	gboolean _tmp0_ = FALSE;
	TomatoServicesSavedState* _tmp1_ = NULL;
	TomatoStatus _tmp2_ = 0;
	TomatoStatus _tmp3_ = 0;
#line 130 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	g_return_if_fail (self != NULL);
#line 131 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	_tmp1_ = tomato_saved;
#line 131 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	_tmp2_ = tomato_services_saved_state_get_status (_tmp1_);
#line 131 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	_tmp3_ = _tmp2_;
#line 131 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	if (_tmp3_ == TOMATO_STATUS_POMODORO) {
#line 670 "WorkManager.c"
		TomatoServicesSavedState* _tmp4_ = NULL;
		gint _tmp5_ = 0;
		gint _tmp6_ = 0;
		TomatoServicesSettings* _tmp7_ = NULL;
		gint _tmp8_ = 0;
		gint _tmp9_ = 0;
#line 131 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		_tmp4_ = tomato_saved;
#line 131 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		_tmp5_ = tomato_services_saved_state_get_pomodoro_count (_tmp4_);
#line 131 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		_tmp6_ = _tmp5_;
#line 131 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		_tmp7_ = tomato_settings;
#line 131 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		_tmp8_ = tomato_services_settings_get_long_break_delay (_tmp7_);
#line 131 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		_tmp9_ = _tmp8_;
#line 131 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		_tmp0_ = (_tmp6_ % _tmp9_) == 0;
#line 691 "WorkManager.c"
	} else {
#line 131 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		_tmp0_ = FALSE;
#line 695 "WorkManager.c"
	}
#line 131 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	if (_tmp0_) {
#line 132 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		tomato_managers_work_manager_set_status (self, TOMATO_STATUS_LONG_BREAK);
#line 133 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		g_message ("WorkManager.vala:133: New status -> Long Break");
#line 703 "WorkManager.c"
	} else {
		gboolean _tmp10_ = FALSE;
		TomatoServicesSavedState* _tmp11_ = NULL;
		TomatoStatus _tmp12_ = 0;
		TomatoStatus _tmp13_ = 0;
#line 134 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		_tmp11_ = tomato_saved;
#line 134 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		_tmp12_ = tomato_services_saved_state_get_status (_tmp11_);
#line 134 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		_tmp13_ = _tmp12_;
#line 134 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		if (_tmp13_ == TOMATO_STATUS_POMODORO) {
#line 717 "WorkManager.c"
			TomatoServicesSavedState* _tmp14_ = NULL;
			gint _tmp15_ = 0;
			gint _tmp16_ = 0;
			TomatoServicesSettings* _tmp17_ = NULL;
			gint _tmp18_ = 0;
			gint _tmp19_ = 0;
#line 134 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
			_tmp14_ = tomato_saved;
#line 134 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
			_tmp15_ = tomato_services_saved_state_get_pomodoro_count (_tmp14_);
#line 134 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
			_tmp16_ = _tmp15_;
#line 134 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
			_tmp17_ = tomato_settings;
#line 134 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
			_tmp18_ = tomato_services_settings_get_long_break_delay (_tmp17_);
#line 134 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
			_tmp19_ = _tmp18_;
#line 134 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
			_tmp10_ = (_tmp16_ % _tmp19_) != 0;
#line 738 "WorkManager.c"
		} else {
#line 134 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
			_tmp10_ = FALSE;
#line 742 "WorkManager.c"
		}
#line 134 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		if (_tmp10_) {
#line 135 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
			tomato_managers_work_manager_set_status (self, TOMATO_STATUS_SHORT_BREAK);
#line 136 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
			g_message ("WorkManager.vala:136: New status -> Short Break");
#line 750 "WorkManager.c"
		} else {
#line 138 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
			tomato_managers_work_manager_set_status (self, TOMATO_STATUS_POMODORO);
#line 139 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
			g_message ("WorkManager.vala:139: New status -> Pomodoro");
#line 756 "WorkManager.c"
		}
	}
}


static void tomato_managers_value_work_manager_init (GValue* value) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	value->data[0].v_pointer = NULL;
#line 765 "WorkManager.c"
}


static void tomato_managers_value_work_manager_free_value (GValue* value) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	if (value->data[0].v_pointer) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		tomato_managers_work_manager_unref (value->data[0].v_pointer);
#line 774 "WorkManager.c"
	}
}


static void tomato_managers_value_work_manager_copy_value (const GValue* src_value, GValue* dest_value) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	if (src_value->data[0].v_pointer) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		dest_value->data[0].v_pointer = tomato_managers_work_manager_ref (src_value->data[0].v_pointer);
#line 784 "WorkManager.c"
	} else {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		dest_value->data[0].v_pointer = NULL;
#line 788 "WorkManager.c"
	}
}


static gpointer tomato_managers_value_work_manager_peek_pointer (const GValue* value) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	return value->data[0].v_pointer;
#line 796 "WorkManager.c"
}


static gchar* tomato_managers_value_work_manager_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	if (collect_values[0].v_pointer) {
#line 803 "WorkManager.c"
		TomatoManagersWorkManager* object;
		object = collect_values[0].v_pointer;
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		if (object->parent_instance.g_class == NULL) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 810 "WorkManager.c"
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 814 "WorkManager.c"
		}
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		value->data[0].v_pointer = tomato_managers_work_manager_ref (object);
#line 818 "WorkManager.c"
	} else {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		value->data[0].v_pointer = NULL;
#line 822 "WorkManager.c"
	}
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	return NULL;
#line 826 "WorkManager.c"
}


static gchar* tomato_managers_value_work_manager_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	TomatoManagersWorkManager** object_p;
	object_p = collect_values[0].v_pointer;
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	if (!object_p) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
#line 837 "WorkManager.c"
	}
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	if (!value->data[0].v_pointer) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		*object_p = NULL;
#line 843 "WorkManager.c"
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		*object_p = value->data[0].v_pointer;
#line 847 "WorkManager.c"
	} else {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		*object_p = tomato_managers_work_manager_ref (value->data[0].v_pointer);
#line 851 "WorkManager.c"
	}
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	return NULL;
#line 855 "WorkManager.c"
}


GParamSpec* tomato_managers_param_spec_work_manager (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	TomatoManagersParamSpecWorkManager* spec;
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	g_return_val_if_fail (g_type_is_a (object_type, TOMATO_MANAGERS_TYPE_WORK_MANAGER), NULL);
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	G_PARAM_SPEC (spec)->value_type = object_type;
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	return G_PARAM_SPEC (spec);
#line 869 "WorkManager.c"
}


gpointer tomato_managers_value_get_work_manager (const GValue* value) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TOMATO_MANAGERS_TYPE_WORK_MANAGER), NULL);
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	return value->data[0].v_pointer;
#line 878 "WorkManager.c"
}


void tomato_managers_value_set_work_manager (GValue* value, gpointer v_object) {
	TomatoManagersWorkManager* old;
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TOMATO_MANAGERS_TYPE_WORK_MANAGER));
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	old = value->data[0].v_pointer;
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	if (v_object) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TOMATO_MANAGERS_TYPE_WORK_MANAGER));
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		value->data[0].v_pointer = v_object;
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		tomato_managers_work_manager_ref (value->data[0].v_pointer);
#line 898 "WorkManager.c"
	} else {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		value->data[0].v_pointer = NULL;
#line 902 "WorkManager.c"
	}
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	if (old) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		tomato_managers_work_manager_unref (old);
#line 908 "WorkManager.c"
	}
}


void tomato_managers_value_take_work_manager (GValue* value, gpointer v_object) {
	TomatoManagersWorkManager* old;
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TOMATO_MANAGERS_TYPE_WORK_MANAGER));
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	old = value->data[0].v_pointer;
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	if (v_object) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TOMATO_MANAGERS_TYPE_WORK_MANAGER));
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		value->data[0].v_pointer = v_object;
#line 927 "WorkManager.c"
	} else {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		value->data[0].v_pointer = NULL;
#line 931 "WorkManager.c"
	}
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	if (old) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		tomato_managers_work_manager_unref (old);
#line 937 "WorkManager.c"
	}
}


static void tomato_managers_work_manager_class_init (TomatoManagersWorkManagerClass * klass) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	tomato_managers_work_manager_parent_class = g_type_class_peek_parent (klass);
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	((TomatoManagersWorkManagerClass *) klass)->finalize = tomato_managers_work_manager_finalize;
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	g_type_class_add_private (klass, sizeof (TomatoManagersWorkManagerPrivate));
#line 949 "WorkManager.c"
}


static void tomato_managers_work_manager_instance_init (TomatoManagersWorkManager * self) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	self->priv = TOMATO_MANAGERS_WORK_MANAGER_GET_PRIVATE (self);
#line 26 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	self->priv->ticks = 1;
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	self->ref_count = 1;
#line 960 "WorkManager.c"
}


static void tomato_managers_work_manager_finalize (TomatoManagersWorkManager* obj) {
	TomatoManagersWorkManager * self;
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TOMATO_MANAGERS_TYPE_WORK_MANAGER, TomatoManagersWorkManager);
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	g_signal_handlers_destroy (self);
#line 23 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	_tomato_util_countdown_unref0 (self->priv->countdown);
#line 24 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	_tomato_util_timer_unref0 (self->priv->total_time);
#line 974 "WorkManager.c"
}


GType tomato_managers_work_manager_get_type (void) {
	static volatile gsize tomato_managers_work_manager_type_id__volatile = 0;
	if (g_once_init_enter (&tomato_managers_work_manager_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { tomato_managers_value_work_manager_init, tomato_managers_value_work_manager_free_value, tomato_managers_value_work_manager_copy_value, tomato_managers_value_work_manager_peek_pointer, "p", tomato_managers_value_work_manager_collect_value, "p", tomato_managers_value_work_manager_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (TomatoManagersWorkManagerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) tomato_managers_work_manager_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TomatoManagersWorkManager), 0, (GInstanceInitFunc) tomato_managers_work_manager_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType tomato_managers_work_manager_type_id;
		tomato_managers_work_manager_type_id = g_type_register_fundamental (g_type_fundamental_next (), "TomatoManagersWorkManager", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&tomato_managers_work_manager_type_id__volatile, tomato_managers_work_manager_type_id);
	}
	return tomato_managers_work_manager_type_id__volatile;
}


gpointer tomato_managers_work_manager_ref (gpointer instance) {
	TomatoManagersWorkManager* self;
	self = instance;
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	g_atomic_int_inc (&self->ref_count);
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	return instance;
#line 999 "WorkManager.c"
}


void tomato_managers_work_manager_unref (gpointer instance) {
	TomatoManagersWorkManager* self;
	self = instance;
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		TOMATO_MANAGERS_WORK_MANAGER_GET_CLASS (self)->finalize (self);
#line 21 "/home/lamm/Projetos/tomato/src/Managers/WorkManager.vala"
		g_type_free_instance ((GTypeInstance *) self);
#line 1012 "WorkManager.c"
	}
}



